### ISSUE TITLE
Account History - Clicking the '+' on the button adds a the word 'Details' to the button

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1000]
If I click, the '+' on the Details button in Chrome or Safari, 'Details' is added to the button so the button text is now '+- Details Details.'
Continuing to do so, results in something like this.

![screen shot 2015-02-12 at 3 33 58 pm](https://cloud.githubusercontent.com/assets/9256525/6177468/c17569b8-b2cc-11e4-952e-746957ddd054.png)

Clicking anywhere else on the button doesn't seem to have this effect.

**Comment by tarakieffer** [comment]
Now when I click on the word "Details" to expand, I am not able to collapse the details.

![screen shot 2015-02-13 at 7 50 11 am](https://cloud.githubusercontent.com/assets/9256525/6188262/03fcc9d8-b355-11e4-8b69-6335d6d33276.png)

**Comment by pkarman** [comment]
ah DOM. I love you.

fixed in branch and pushed to stage.

**Comment by tarakieffer** [comment]
Huzzah!  Looks good now.
