### ISSUE TITLE
Account History - Details do not display for both premium and basic transcripts if in the same month

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1001]
user 1028 - Sept 2014 has both premium and basic usage

Only the premium activity lines are displaying.

![screen shot 2015-02-12 at 4 10 12 pm](https://cloud.githubusercontent.com/assets/9256525/6178180/2801a9bc-b2d2-11e4-8b8a-0087928276e3.png)

**Comment by pkarman** [comment]
I think that's a UX bug rather than a data bug. All the transcripts are shown regardless of basic/premium distinction. I should tweek the layout and/or add colors or a transcript type column to indicate that.

**Comment by tarakieffer** [comment]
I think the UX tweak will be helpful, but also I am only seeing 4 files that look like the premium transcripts, not the two basic transcripts.

Basic Transcripts
![screen shot 2015-02-12 at 4 37 39 pm](https://cloud.githubusercontent.com/assets/9256525/6178546/9d38bd94-b2d5-11e4-9532-30bd4c89e80c.png)

Premium transcripts
![screen shot 2015-02-12 at 4 37 13 pm](https://cloud.githubusercontent.com/assets/9256525/6178545/9d36b22e-b2d5-11e4-8339-35161a935ec5.png)

**Comment by tarakieffer** [comment]
All files are displaying when there is a mix of basic and premium.  

I am not seeing an obvious distinction of which one is which.  @pkarman should I be?

![screen shot 2015-02-13 at 9 32 34 am](https://cloud.githubusercontent.com/assets/9256525/6189834/46df2b66-b363-11e4-9703-d232db0a7ed2.png)

**Comment by pkarman** [comment]
ah no, I hadn't added the transcript type. Just added that column.

I also changed the background color of detail rows to distinguish them more easily.

**Comment by tarakieffer** [comment]
All lines are displaying including Preview and they are labeled as such.  Considering this good for this ticket.
![screen shot 2015-02-13 at 5 44 58 pm](https://cloud.githubusercontent.com/assets/9256525/6197260/23a1f260-b3a8-11e4-99ad-25467e60d257.png)
