### ISSUE TITLE
"Upload failed" message showing for non-failed uploads?

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1002]
From user 1729: "When I upload a file I inevitably get an "upload failed" message until, much later, there's a "transcribing" message. Disconcerting, as I have no idea if I need to re-upload or not! (If you check my collection page now, you'll see just what I've described.)"

**Comment by pkarman** [comment]
@Saltzshaker mentioned this the other day too. I haven't been able to duplicate yet myself, but to be safe, I am ratcheting back the logic that identifies failed uploads to something closer to what it was a week ago.
