### ISSUE TITLE
optimize transcript_usage

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1008]
orgs with large numbers of transcripts get timeout issues when logging in because the /api/me endpoint automatically loads all transcript usage detail history for all time.

optimize this:

* defer loading till hitting the /account UI
* only load N months of data
* consider caching monthly_usage details in its own table

**Comment by pkarman** [comment]
there's a small optimization in the monthly-billing branch that only loads the current month details by default. moving this out to next milestone since I won't get it fully optimized by eod tomorrow.

**Comment by pkarman** [comment]
now in loretta branch:

* load usage details only when clicking each month's Details button
* load only one month at a time
* load zero months to start

**Comment by tarakieffer** [comment]
Using the fantastic 'switch' feature, this is looking good.  Loading mask displays when Details button is clicked and while the usage details are loading.   
Navigation before (and after) going to account page is pretty snappy.
