### ISSUE TITLE
Set up conversion tracking in GA

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1020]
https://www.google.com/analytics/web/?hl=en#management/Settings/a40277363w69418586p71555004/%3Fm.page%3DGoals%26m-content-goalList.rowShow%3D10%26m-content-goalList.rowStart%3D0%26m-content-goalList.sortColumnId%3Dname%26m-content-goalList.sortDescending%3Dfalse%26m-content.mode%3DEDIT/

**Comment by Saltzshaker** [comment]
Set something up based on the popuparchive.com/collections url, but I don't think it's working. Will need to add event tracking snippet for sign up event.

**Comment by annewootton** [comment]
I noticed recently in GA that there are some conversions being tracked for
popuparchive.org, for what it's worth. Didn't look into it any further. Not
sure if it's related to what you did, but I certainly have never set up any
conversion tracking for PUA.

**Comment by Saltzshaker** [comment]
https://github.com/popuparchive/pop-up-archive/commit/a95f934b26c1db698b58c80f4e32d58cc6d40001 To test, use Google Analytics Debugger extension https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en

The goal is to have a "Registration" event fire during sign up.

**Comment by tarakieffer** [comment]
Does this need to be tested in prod?  I am not seeing anything firing when the extension is enabled and registering in stage.
