### ISSUE TITLE
Let org admins see team members' usage

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1021]
Per CBC:

"Right now I'm having a hard time trying to monitor who is using it and how much we have left. It would be really useful if I could log in and view this info easily.  ... I'm concerned that some people might not be using the service effectively (ie. uploading an hour of tape when they just need to transcribe a short except for web or story purposes). I'm going to need to send out an 'etiquette' email to our users sometime in the next few weeks and it would be great if I had as much info as possible before I sent out that note."

I'm sending her the info for February, but we could incorporate this on the /account page for admins going forward.

**Comment by pkarman** [comment]
that info should be available on their Account page now, if they click details.
we can also show it on the Org page (same data, different view).

**Comment by annewootton** [comment]
That's amazing. Thank you!
