### ISSUE TITLE
Batch upload question

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1024]
Users don't want to make files on Google Drive public, even temporarily. Not urgent, but:

"Is there an FTP option? I'm actually just uploading like 5 files at a time."

We've done FTP imports in the past (early days, for the Kitchen Sisters) using a rake task. I guess it wouldn't be that hard for us to do it again... could set up the rake task in Heroku scheduler to run once/day. The only thing I'm unsure of is whether the FTP login info would be 100% secure. In the past it was a parameter on the rake task and I seem to have a memory of it getting saved in the app somewhere. 

I'm telling this user "not for now, but we're looking into it" while I get y'alls thoughts (mostly @pkarman).

**Comment by pkarman** [comment]
The lib/remote_importer connects to an FTP server. So unless you're talking about a customer hosting their stuff on FTP that we connect to, I think our primary alternative is ssh+rsync to uploads.popuparchive.com.

We do not provide FTP upload to uploads.popuparchive.com because it is insecure.

We can set up the customer with ssh access; they just need to email us a public ssh key.

At that point though, we still need to automate the import. Right now that code is unwritten. In the past we just created CSVs and did it ourselves.

**Comment by annewootton** [comment]
I am talking about a customer hosting their stuff on FTP that we connect
to. Thoughts on that?

Otherwise, I will propose the ssh access option. We're fine with creating
the CSV ourselves since the UX is buggy and risks duplicate imports.
ᐧ

**Comment by pkarman** [comment]
understood.

yes, we could configure the FTP importer rake task on the scheduler. You are right about security: credentials would be stored in the heroku scheduler as part of the event.

It doesn't pose a security threat to PUA; it poses one to the customer. If they are ok with it, I'm ok with it.

**Comment by annewootton** [comment]
Got it. But we're not actually saving the credentials in a way that would
be, say, accessible on the item level in Pop Up Archive?

I'm okay with the Heroku scheduler security concern (insofar as it's really
the customer's concern) too, so I'll ask the customer what he prefers.
Thanks.
ᐧ

**Comment by pkarman** [comment]
the ftp credentials are not stored in our db, no. They are only used by the rake task and must be present when it runs, but that is all.

**Comment by annewootton** [comment]
I offered the FTP (where he gives us his credentials) and SSH options and he said that they seem too complicated for the five or so files he's adding at a time. 

For the (maybe never) future, the ideal solution would be Google Drive/Dropbox integration where we authenticate to the user's account and can access their private files. Closing this particular ticket.
