### ISSUE TITLE
Give Pop Up users option to download .txt files without timestamps

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1027]

**Comment by annewootton** [comment]
And they also want timestamps more frequently! Can't make 'em all happy.
But maybe we could come close if we gave three options: no timestamps, line-by-line timestamps, or speaker change (what we currently have) timestamps.

**Comment by baileyspace** [comment]
For testing: Export "format with timestamps" should include timestamps in the txt file and "format without timestamps" should not.

**Comment by tarakieffer** [comment]
Three is a choice between text with timestamps and without timestamps.
![screen shot 2015-06-04 at 7 29 38 am](https://cloud.githubusercontent.com/assets/9256525/7984054/92f3ed28-0a8b-11e5-81d4-3129fa6bb768.png)

Example of text without timestamps  -- it also is without speaker ids 
![screen shot 2015-06-03 at 4 07 22 pm](https://cloud.githubusercontent.com/assets/9256525/7984025/67cd9f5e-0a8b-11e5-8b0c-32f61c2a3a44.png)

Example of text with timestamps -- 
![screen shot 2015-06-03 at 4 07 45 pm](https://cloud.githubusercontent.com/assets/9256525/7984073/c1c3ee6e-0a8b-11e5-8f53-6d7746e1da0c.png)

**Comment by baileyspace** [comment]
Just re-added speaker ids to premium w/out transcripts.
