### ISSUE TITLE
Some public collections show 0 items at collection endpoint

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1028]
Most notably for Popcast: https://www.popuparchive.com/collections/4425 even though it's a public collection: https://www.popuparchive.com/superadmin/collections/4425 The item pages are accessible.

I also noticed this for another public collection, billable to me: https://www.popuparchive.com/superadmin/collections/3749

Though not for this one: https://www.popuparchive.com/superadmin/collections/3693

**Comment by pkarman** [comment]
the items weren't in the index. this contradicts my initial guess from earlier today, and makes me question whether the weekly re-indexing is actually doing what we want.

I have manually re-indexed the 3 items in the 4425 collection.

I'm going to dig a little into why the weekly re-index isn't catching these.

**Comment by pkarman** [comment]
ah. looks like bonsai went into 503 status when our re-index was 72% complete. I will kick off a manual reindex now.

**Comment by pkarman** [comment]
reindex complete.

fix now in place in code to not commit a partially complete reindex.

**Comment by Saltzshaker** [comment]
Looks like that did the trick. Thanks!
