### ISSUE TITLE
CORS bug with fontawesome for embedded tplayer

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1030]
I get this error in FF:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.popuparchive.com/assets/fontawesome-webfont.woff. This can be fixed by moving the resource to the same domain or enabling CORS.

It means the play button icons do not show up.

The file is being included in the fontawesome CSS inside tplayer.css. Not sure what the solution here is, since it doesn't seem to be an issue when the tplayer.css is explicitly <link> tagged on the embedding page.

**Comment by baileyspace** [comment]
We could try using the font-awesome cdn instead
http://fortawesome.github.io/Font-Awesome/get-started/

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-03-12 12:34 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by pkarman** [comment]
good call @baileyspace 

fixed merged and deployed
