### ISSUE TITLE
verify all fixer tasks are fired async

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1032]
audit all the fixer interaction to make sure it is async (via sidekiq) and not any directly from model or controller.

**Comment by tarakieffer** [comment]
Functionality that is working successfully at this point:
Premium transcripts for new items on new and existing collections
Reprocessing an existing Basic transcript as Premium

Functionality that is not working as expected:
Uploading an file to an existing item - @pkarman indicates this will always fail - I didn't log a ticket for this.
Uploading file for a basic transcript - #1122

**Comment by pkarman** [comment]
thanks for the summary. I am switching stage to use the bobbie branch and changing fixer config accordingly.

**Comment by pkarman** [comment]
#1122 should now be ready to test.
