### ISSUE TITLE
Improve sorting by date

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1036]
We've tried to bandaid this in the past, but it's still acting funny. The sorting order often does not change when users choose ascending vs. descending sort. 

For example:
https://www.popuparchive.com/search?page=1&sortBy=date_created&sortOrder=asc&query=collection_id:%22583-Illinois%20Public%20Media%22

vs.
https://www.popuparchive.com/search?page=1&sortBy=date_created&sortOrder=desc&query=collection_id:%22583-Illinois%20Public%20Media%22

**Comment by annewootton** [comment]
Sorting isn't working for Date Created or Date Added at all. At the very least this should default to sort by date added to DB, so users can find their most recent stuff. Collections used to display with most recent items at the top and they don't anymore...

**Comment by annewootton** [comment]
Moving up to June since CUNY is waiting on this to be able to pull a bunch of transcripts into their own CMS.

**Comment by pkarman** [comment]
sorting by "Date Created" is always going to give suspect-looking results, because the **date_created** field is often null.

sorting by "Date Added" should always give meaningful results because that date value is always populated.

The UX bug is that the presentation does essentially this:
```
date_created || date_added
```

which means users never see that the date_created field is null until they go into edit a record.

As I think I've said before, we can choose accuracy or we can choose usability, but in this case, we can't have both unless we change the presentation logic (show both date fields, including the null value).

**Comment by annewootton** [comment]
Can it just work the way it used to: when a user clicked on their
collection, they saw the most recent items at the top?

**Comment by annewootton** [comment]
If I understand you correctly, for it to work the way it used to would mean
default sorting by date added.

Like you said, sorting by "Date Added" should always give meaningful
results. Right now when you click to sort by "Date Added" it doesn't work —
regardless of which date fields are showing in the UI.

**Comment by pkarman** [comment]
when I click on a collection from the /collections page, I get all my items sorted **Newest Added to Oldest Added**.

The links you reference in the issue description are from a direct search, somehow. Hard to reverse-engineer from that URL. But definitely *not* from clicking on a collection link on the /collections page.

What I'm hearing you say is that any time a **query** or **filter** parameter includes a *collection_id* then the default sort should be by **date_added desc**.

**Comment by pkarman** [comment]
I don't have this experience:
"Right now when you click to sort by "Date Added" it doesn't work —
regardless of which date fields are showing in the UI."

When I select either of the **Date Added** options from the pulldown menu, the results re-sort accordingly. You are not seeing that behavior?

**Comment by annewootton** [comment]
The example URLs from WILL were from a user who navigated to the collection from our /search or /explore page. Any time a user clicks on a public collection title they are taken to the collection via a search query, i.e. https://www.popuparchive.com/search?page=1&query=collection_title:%22Illinois%20Public%20Media%22. So yes, I think it makes sense to default sort by date_added desc any time a query or filter parameter includes a collection_id (and/or a collection_title?).

Re: "Right now when you click to sort by "Date Added" it doesn't work — regardless of which date fields are showing in the UI," take a look at https://www.popuparchive.com/collections/2253. From what I can tell, none of these items have date_created assigned. But you see different things when you look at date_added desc and date_created asc.

I'm no longer positive that the default sort isn't working, since I learned after filing this ticket that the user didn't actually add the items he thought he had added to the collection. But there still seems to be inconsistency between date added // date created in a collection where no items have date_created values.

**Comment by annewootton** [comment]
To compare: 
https://www.popuparchive.com/collections/2253?sortBy=date_created&sortOrder=desc
https://www.popuparchive.com/collections/2253?sortBy=date_added&sortOrder=desc

**Comment by pkarman** [comment]
yes, you will always see inconsistency when sorting by date_created vs date_added. The date_added is automatically populated by Rails. The date_created is manually and optionally entered by the user.

**Comment by annewootton** [comment]
But the items in the example I provided do not have date_created values assigned by the user.
For example: https://www.popuparchive.com/collections/2253/items/23916

**Comment by pkarman** [comment]
you are exactly right. that's why the sorting is inconsistent. it's sorting on null values, but showing the date_added (not the date_created).

**Comment by annewootton** [comment]
Aha!
Hmm. I'd love to improve this experience. Open to ideas on that. Maybe it should default to date_added in absence of date_created values?

**Comment by pkarman** [comment]
If we default to date_added as you suggest, I think users who inconsistently add date_created values will be confused. I think if we have both fields, we should show both fields. We've given users the power to add data and sort by it, but if we aren't presenting it, it will confuse people (as it has a few times now).

**Comment by annewootton** [comment]
I hear what you're saying. And in that case, if a user clicks to sort by
"Date Created" and it sorts on null values, at least they'll see that there
is no date created value in the results partial UI?

**Comment by pkarman** [comment]
correct.

**Comment by pkarman** [comment]
We could show the Date Created if not null, otherwise hide it (for those users who do not use it).
And if defined, show it in addition to Date Added.

**Comment by annewootton** [comment]
The problem with not showing Date Created in the UI for users who do not
use it is that if they sort by Date Created, they get randomly sorted
search results, which confuses them. (Back to the CUNY example.)

**Comment by annewootton** [comment]
We could do something conditional like not even offer the "sort by date
created" option for collections/searches without date_created values for
any items, but I don't know how complicated that would be to implement.

**Comment by pkarman** [comment]
prohibitively complicated.

let's just always show both columns.

**Comment by annewootton** [comment]
Sounds good to me.

**Comment by tarakieffer** [comment]
Date created is displaying when it is defined.
![screen shot 2015-04-21 at 12 56 31 pm](https://cloud.githubusercontent.com/assets/9256525/7259051/302eca46-e826-11e4-9251-93130af4e1ef.png)
