### ISSUE TITLE
Send "You've reached X% of your plan" email

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1042]

**Comment by pkarman** [comment]
added email alert that gets sent via cron'd usage summary report. Must have SEND_ALERTS=1 env var set to true to send, so we can run it independently of the usual cron or any point in the usage calculation workflow.

Can be triggered manually with:

```
user.send_usage_alert
```

**Comment by pkarman** [comment]
@tarakieffer let me know when you want to test this and we can mock up the data to trigger an alert email.

**Comment by pkarman** [comment]
@baileyspace @Saltzshaker @annewootton do we want this email to go only to non-Community (paying) customers?

**Comment by annewootton** [comment]
Yep.
ᐧ

**Comment by pkarman** [comment]
thanks. done.
