### ISSUE TITLE
Figure out if users are editing

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1043]
Mixpanel/Rake task to see if timed_texts have changed.

**Comment by baileyspace** [comment]
added rake task:
rake monitor:new_transcript_edits (# of transcripts edited in past 24 hours)

added mixpanel event:
Edit Transcript

**Comment by tarakieffer** [comment]
Clicking 'Edit Text' increments 'Edit Transcript' in Mixpanel.
