### ISSUE TITLE
Reject illegal content types on the client side (if possible)

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1044]
Such as image uploads or SC item pages. Currently get stuck in "Processing"

**Comment by shindostrz** [comment]
2-tier solution: if URL ends in an acceptable file extension, just accept it, otherwise do a head request to see if it is an audio file.

**Comment by tarakieffer** [comment]
@shindostrz Does this apply only to files added by URL?  Should it apply also to uploaded files?

**Comment by tarakieffer** [comment]
I will rephrase my last comment.  This appears to be correctly rejecting files added via url.
![screen shot 2015-04-02 at 3 41 23 pm](https://cloud.githubusercontent.com/assets/9256525/6973674/00319bda-d952-11e4-9cf1-609c56aac7c5.png)

There is no error for the upload file that is not audio.
![screen shot 2015-04-02 at 4 07 07 pm](https://cloud.githubusercontent.com/assets/9256525/6973727/6811adf8-d952-11e4-8892-72d79672f38a.png)

**Comment by shindostrz** [comment]
@tarakieffer The code that I added is only for remote URLs, so it should reject URLs that either don't end in a valid audio extension or don't redirect to a resource of type "audio/..."

**Comment by pkarman** [comment]
@tarakieffer that's a valid point, and beyond the scope of this particular change. I think we have another ticket on the upload issue; if not, I'll create one.
