### ISSUE TITLE
Create "upgrade/downgrade" email notification

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1045]

**Comment by pkarman** [comment]
this seems like something we should use Mixpanel for. We could log events inside the User.subscribe! method and inside the relevant stripe webhook controller code. That way the report can be tied to other user activity.

@Saltzshaker @annewootton thoughts?

**Comment by annewootton** [comment]
Mixpanel event tracking seems like it would work just fine for this. @Saltzshaker is there a way we could email a report based on who upgrades/downgrades each week?

@pkarman, any particular other user activity you were thinking would be helpful in this context?

**Comment by pkarman** [comment]
nothing in particular. mostly I was imagining being able to correlate subscription changes with other "significant" events.

**Comment by annewootton** [comment]
Cool. Seems like we can go ahead and add the Mixpanel tracking to User.subscribe! and inside the relevant Stripe webhook controller code. Then assign to @Saltzshaker to figure out reporting piece.

**Comment by pkarman** [comment]
in the elizabeth branch

**Comment by pkarman** [comment]
changing subscription should trigger a mixpanel event, both from the Stripe.com side and from the popuparchive.com side.

**Comment by annewootton** [comment]
@tarakieffer when you're done testing this, you can assign it to @Saltzshaker and she'll add the appropriate email alert from Mixpanel.

**Comment by tarakieffer** [comment]
What is the name of the event this action should trigger?  

These are the events I see currently:
![screen shot 2015-04-02 at 3 19 22 pm](https://cloud.githubusercontent.com/assets/9256525/6972789/b88d7624-d94b-11e4-999c-afa4121d6b62.png)

**Comment by pkarman** [comment]
the name I used was *subscription change* though it might also appear under a slightly different name when coming via stripe.com

**Comment by pkarman** [comment]
found a typo in the mixpanel worker class. fixed and pushed to stage.

**Comment by tarakieffer** [comment]
'subscription change' and 'customer.subscription.updated' are incrementing when changed through the UI.

I don't have ability to change subscription in Stripe.  I have sent request to @baileyspace so that can be tested.

**Comment by tarakieffer** [comment]
'customer.subscription.updated' incremented for the change of subscription within Stripe.

Passing along to @Saltzshaker

**Comment by Saltzshaker** [comment]
now this ticket https://github.com/popuparchive/pop-up-archive/issues/1079
