### ISSUE TITLE
Tweet modal only autopopulates text of first thing you tweet

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1048]
For example, though everything about the first tweet experience works as expected, when you go back and try to tweet something else, the tweet from the first text stays in the modal. You can try it from here: http://popuparchive.tumblr.com/post/114063243544/folksong-potboilers

**Comment by Saltzshaker** [comment]
Works on Audiosear.ch

**Comment by Saltzshaker** [comment]
JK, have now seen this on AS too.

**Comment by tarakieffer** [comment]
Seems to be working okay now.
