### ISSUE TITLE
Get PUA short url

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1049]

**Comment by pkarman** [comment]
pop-up.io is available
puaio.com is available

**Comment by annewootton** [comment]
But no pua.io?!

If not, I vote pop-up.io.
ᐧ

**Comment by baileyspace** [comment]
10-4. I'm going url shopping.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-04-02 15:08 GMT-07:00 annewootton <notifications@github.com>:

**Comment by baileyspace** [comment]
We are now the proud owners of pua.bz

**Comment by pkarman** [comment]
cool it is so short.

does this give us any pause though? have we registered the plural?
http://www.urbandictionary.com/define.php?term=puab

**Comment by baileyspace** [comment]
Well, if people complain, we can always create a novelty website.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-04-02 19:56 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by pkarman** [comment]
excellent response.

to use this new domain in production, just need to set the SHORT_URL env variable. E.g.:
```
heroku config:set SHORT_URL=http://pua.bz -a pop-up-archive
```

@baileyspace do you want to try that and confirm it works?

**Comment by annewootton** [comment]
Hahaha. Now when I'm annoyed I can call people puabz and laugh maniacally because Peter taught us urban slang.

**Comment by baileyspace** [comment]
Cool, set up the variable. Looks like it's redirecting as expected
pua.bz/collections/810/items/7224

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-04-02 21:08 GMT-07:00 annewootton <notifications@github.com>:
