### ISSUE TITLE
Persistent player overflow is scroll

### ISSUE THREAD

**Issue by shindostrz** [popuparchive/pop-up-archive#1055]
![screen shot 2015-03-27 at 4 06 56 pm](https://cloud.githubusercontent.com/assets/5482422/6878453/9fbd2a22-d49b-11e4-9253-1f806d52c3e3.png)

**Comment by baileyspace** [comment]
Cannot recreate

**Comment by tarakieffer** [comment]
I have not been able to reproduce this.
