### ISSUE TITLE
Add prominent links to Audiosearch

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1058]

**Comment by Saltzshaker** [comment]
Added subscribe form to tumblr: http://popuparchive.tumblr.com/ 
Text is "Get Pop Up Archive's newsletter for archival picks and industry insights!" (as a starting point, not in love with the phrasing.)

For popuparchive.com, any thoughts on placement @baileyspace? Is it too audacious to just put it on the homepage under the sign up buttons? I actually think that it's worth being a central CTA, as it serves as an opt-in drip campaign for people who might not be ready to sign up.

I wonder if we should even get some testimonials from people who like it, to make it even MORE of a thing...

**Comment by annewootton** [comment]
+1 to making it a central (or at least non-footer) call to action on
popuparchive.com. Defer to @baileyspace on where exactly it should go.

Testimonials, not top priority, but I like that idea too.
ᐧ

**Comment by annewootton** [comment]
Let's go with horizontal div à la Hellobar with Audiosear.ch announcement + email signup.

**Comment by tarakieffer** [comment]
I am seeing subscribe to Newsletter after 'How it works"

![screen shot 2015-05-07 at 12 56 18 pm](https://cloud.githubusercontent.com/assets/9256525/7522130/cb5b4d7a-f4b8-11e4-95d1-a5536067fa83.png)

I am not seeing links to audiosear.ch.

**Comment by pkarman** [comment]
it looks like the /about page got the links:

https://github.com/popuparchive/pop-up-archive/pull/1092/files

**Comment by pkarman** [comment]
@anne @baileyspace can you confirm in stage that the links are where you expect them to be?

**Comment by baileyspace** [comment]
Correct.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-05-07 11:15 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by annewootton** [comment]
+1
ᐧ

**Comment by baileyspace** [comment]
Opa, but something's up with the sign up for newsletter bar.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-05-07 11:17 GMT-07:00 Bailey Smith <bailey.r.smith@gmail.com>:
