### ISSUE TITLE
disallow non-audio uploads

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1059]
similar to #1044 reject not-allowed file extensions.

**Comment by tarakieffer** [comment]
Error displays when non-audio file is selected to be uploaded.
![screen shot 2015-06-03 at 4 37 09 pm](https://cloud.githubusercontent.com/assets/9256525/7983892/7494e3ba-0a8a-11e5-90bf-45be660fd5cf.png)
