### ISSUE TITLE
Unselect "public" as default storage option

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1062]
When making collections in PUA, the collection form has "public" filled in as the default privacy setting (this was to encourage users to make their audio public). 

Seems like people get tripped up on this and freak out when their stuff was public (most recently someone thought they just had to re-upload the audio). 

Could we just show the blank radio buttons and have the user manually choose it from the start, rather than having "public" chosen by default?

**Comment by annewootton** [comment]
Taking the "proposed" tag off this — I think it's important because I'm noticing when I'm in superadmin that many reporters are creating public collections with their raw tape — most likely because they do not realize that the default collection privacy setting is "public."
