### ISSUE TITLE
Date Created not displaying correctly in results partials

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1065]
From customer:

Dates entered into the Creation Date filed appear properly when viewing the individual record, but when viewed in a search result, the creation date is displayed offset by a day earlier and with the time “19:00:00 GMT-0500 (Central Daylight Time)”
 
Examples of this can be viewed on this collection: https://www.popuparchive.com/collections/4166
Specific example:
David Fifield Interview, July 21, 1976: https://www.popuparchive.com/collections/4166/items/36991
Created: 1976-07-21
Search result display: Created: Tue Jul 20 1976 19:00:00 GMT-0500 (Central Daylight Time)

**Comment by pkarman** [comment]
the search results display in the timezone of the browser.

the item results display in UTC (GMT).

if we make it standard everywhere, which TZ should be used? My suggestion is UTC.

**Comment by annewootton** [comment]
Yeah, UTC all around sounds good to me.
ᐧ

**Comment by pkarman** [comment]
in master. will deploy on next push.
