### ISSUE TITLE
Some pixels cut off in search hit play buttons

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1067]
![image](https://cloud.githubusercontent.com/assets/833332/7029515/0dc2811e-dd13-11e4-9955-70888d08e62a.png)

**Comment by tarakieffer** [comment]
Transcript hits play button in stage.  
![screen shot 2015-05-04 at 2 57 58 pm](https://cloud.githubusercontent.com/assets/9256525/7461185/001d4baa-f26e-11e4-8500-be83c53bb967.png)
