### ISSUE TITLE
Create PUA WordPress and migrate over Tumblr posts

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1068]

**Comment by pkarman** [comment]
why leave Tumblr?

**Comment by annewootton** [comment]
SEO sucks.

**Comment by Saltzshaker** [comment]
Also embed player 1. doesn't even show up correctly in the feed for tumblr users (any rich media/iframe-like thing shows up as a thumbnail) 2. can't get oEmbed player on Tumblr

Might still post occasional picture/quote post, but our longer-form tutorials and blogs are not suited for tumblr's platform

**Comment by annewootton** [comment]
Let's find some definitive evidence that SEO for WordPress trumps Tumblr/Medium.

**Comment by Saltzshaker** [comment]
"When comparing Tumblr vs WordPress for SEO or Tumblr vs Blogger SEO, you can clearly see that Blogger and WordPress far ahead than Tumblr. Blogger and WordPress provide inbuilt tools to optimize blog for search engines. Especially to improve on-page SEO."
http://www.problogtricks.com/2014/09/tumblr-seo-tips-best-on-page-seo-strategies.html

This, along with the idea of having a nice separate page for Popcast for the blog, make me lean heavily toward WordPress. Tumblr and Medium (the two alternatives) have too many restrictions on content-types, along with SEO disadvantages. 

With Bailey's support, I'm plowing ahead with a hosted WordPress site.

**Comment by Saltzshaker** [comment]
Can't get access to the popuparchive.wordpress.com site (it's not clear who owns it). Should I create this with another name, or are there any other ideas?

**Comment by annewootton** [comment]
I'll look into this -- hang tight before creating a new domain.
