### ISSUE TITLE
Transcript editing unusable for some people

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1069]
Customer feedback:

"The problem I'm having with editing transcripts is that when I click "edit," it takes a long time for the cursor to show up and once it does it's very difficult to control, keeps jumping back to the end of the sentence and deleting what I've done if I am able to do anything. There seems to be a huge delay between my key commands and what I'm actually seeing on the screen. In general, I'm finding the site to be slow, but this is way worse than other loading issues I've had. And I'm pretty sure it's not my internet connection. I've experienced it in 2 different locations now. "

Wondering if #1060 will help with this at all.

**Comment by annewootton** [comment]
Aha. This is because when you have multiple files in a single item and try to edit one transcript, it opens the editor for ALL transcripts. Assigning to @shindostrz since he expressed understanding of how to make editor open ONLY for transcript currently being edited.

**Comment by baileyspace** [comment]
@shindostrz Successfully opening only one edit box at a time, but when clicking edit text playback doesn't match selected transcript (e.g. https://pop-up-archive-staging.herokuapp.com/collections/938/items/22268)
