### ISSUE TITLE
upgrade to Bootstrap 3

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1071]
this is a Technical Debt placeholder. Rails does not require Bootstrap 3, but if we ever want to be truly mobile-first, we'll want to upgrade. It should probably coincide with a UI makeover, since there are many things that would need to change.

The **bootstrap3** branch is start, initiated during the Rails4 upgrade and prompted by the bootstrap-sass gem, but ultimately abandoned in the interest of time.

**Comment by baileyspace** [comment]
AngularStrap for Bootstrap 3 requires AngularJS 1.2+ and we're on AngularJS v1.2.21, so we're good to go on that front.

**Comment by baileyspace** [comment]
For testing: general regression testing. In general keep an eye out for problems with bootstrap elements like popovers, modals, and dropdowns.
