### ISSUE TITLE
Search results buggy

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1072]
For example (might need to have permission to act as CUNY org 23):

General search:
https://www.popuparchive.com/search?page=1&query=EF000053.mp3
Should return no results, but returns many (incorrect) results.

Collection search:
https://www.popuparchive.com/collections/2253?page=1&query=CCT1302.mp3
Returns correct result along with a bunch more (incorrect) results.

**Comment by pkarman** [comment]
fwiw: CUNY is org 23

a search for *foobar.mp3* will find every instance of the string **mp3** because the search tokenizer splits on the dot (period) into 2 terms: **foobar** and **mp3**.

**Comment by pkarman** [comment]
That particular title does not appear in the database:
```
pop-up-archive::RED=> select id from items where title like 'EF000053%';
(No rows)
```

**Comment by annewootton** [comment]
Sorry, was typing too fast (re: org 23).

Yeah, there shouldn't be any results for EF00053.mp3:
```General search:
https://www.popuparchive.com/search?page=1&query=EF000053.mp3
Should return no results, but returns many (incorrect) results.```

**Comment by annewootton** [comment]
Sounds like we need to rethink search if searching for anything that ends in ".mp3" returns all instances of items with .mp3 anywhere the title.

**Comment by pkarman** [comment]
If you enclose the term in double-quotes you get accuracy:
https://www.popuparchive.com/search?page=1&query=%22EF000053.mp3%22

**Comment by annewootton** [comment]
Double quotes good to know. In the longer term, @pkarman do you think there are ways we could get more nuanced about tokenizing?

**Comment by pkarman** [comment]
There are several search improvements that could be ported to PUA from AS. Among them:

* default to AND default operator, fallback to OR (currently only OR)
* bias phrases
* remove stopwords at query-building time

In this case, the first one (AND instead of OR) would have fixed the problem.

**Comment by annewootton** [comment]
This all sounds smart to me. Unless there are objections let's do this. I'll move this ticket to Roseanne to give some time.

**Comment by pkarman** [comment]
this is in roseanne, deployed to stage, and index rebuilt.

**Comment by baileyspace** [comment]
Everybody test: filtering, facets and sorting

**Comment by baileyspace** [comment]
Did a few searches and didn't notice anything amiss.

**Comment by annewootton** [comment]
I'm trying to test the CUNY queries — when signed in as them, though it
says from /collections page that their collection has 37 items, I see "0 of
0 items" when I click on the collection (
https://stage.popuparchive.com/collections/2253). Clicking on individual
items works though. Is this relevant?

Otherwise, search seems fine to me. A search for "foobar.mp3" turns up no
results.
ᐧ

**Comment by annewootton** [comment]
To clarify: clicking on individual items from the /collections page works,
even though the /collections/2253 link shows no items.
ᐧ

**Comment by pkarman** [comment]
thanks @annewootton that was a good catch. should be fixed now in stage.

**Comment by tarakieffer** [comment]
I am not seeing any issues with search.  Removing stopwords seems like a big win.
