### ISSUE TITLE
Check out how to get metrics for popcast (feedburner, etc.)

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1073]
Can use Popcast as guinea pig, mostly to learn more firsthand about metrics for RSS feeds. http://stats.rawvoice.com/

**Comment by Saltzshaker** [comment]
changed feed in settings from feedburner to sc. will subscribe and test.

**Comment by Saltzshaker** [comment]
Added metrics data from SoundCloud, PUA, AS, Feedburner (TBD), and Blubrry(TBD) to Popcast Metrics docs. https://docs.google.com/spreadsheets/d/1vKG4nK7JCKWpfbsxaGqrhTJT5toLbCzNcGdICSUpzcE/edit?usp=sharing
