### ISSUE TITLE
In stage, not able to save contributors to an item

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1075]
I have tried adding when first creating an item, editing an item, and through the assign speaker flow to add contributors.  The type of contributor is saved, but the name is not.

![screen shot 2015-04-15 at 2 08 19 pm](https://cloud.githubusercontent.com/assets/9256525/7167209/e9ea873e-e378-11e4-879a-af9f5dbf669b.png)

**Comment by pkarman** [comment]
this was a bug in the response code for POST /api/collections/:id/people

should be fixed now in stage.

**Comment by tarakieffer** [comment]
looks good now.

![screen shot 2015-04-15 at 9 44 34 pm](https://cloud.githubusercontent.com/assets/9256525/7173155/a5a57a9e-e3b8-11e4-8c8e-ad9831488ab2.png)
