### ISSUE TITLE
Deleted items still show up as phantom items

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1076]
This happened with Popcast. I would post it as an example, but I already removed them from the index manually. Items show up on collection page without play icon. Nothing there when you click. They'll go away eventually, presumably after reindexing?

**Comment by pkarman** [comment]
yes the weekly re-indexing is the best effort fix for this issue. Everything else we tried introduced more complexity without actually solving the problem.

**Comment by Saltzshaker** [comment]
ah, got it. didn't remember that that was the situation.
