### ISSUE TITLE
add Mixpanel event for subscription change

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1077]
needs to be on the People section:
e.g.
```
mixpanel.people.set({"Subscription Change Date": new Date().toISOString()})
```

**Comment by pkarman** [comment]
@Saltzshaker what identifier are we using (should we use) for users at mixpanel? Email? Stripe customer id? User.id ?

**Comment by Saltzshaker** [comment]
Can we do email and user id?

**Comment by Saltzshaker** [comment]
So after looking into this more, it annoyingly appears that setting this up will actually only give us a way to target upgraded/downgraded users to send notification emails. While this is valuable too, it doesn't serve the intended purpose of giving us internal emails about upgrades and downgrades. 

According to Mixpanel support, there is no straightforward way of sending internal notifications based on Mixpanel data. They recommend two things:
1. Setting up a "webhook" to receive POST request from Mixpanel (and I guess get a notification based on when this page is updated?) https://mixpanel.com/help/reference/webhooks
2. I can do manual reporting by looking at the UI

**Comment by pkarman** [comment]
if Mixpanel can't do what we want, let's just skip it. We can add activity logging to our db and just log subscription events there instead, and do our own automated reporting. I will open a new ticket for that.
