### ISSUE TITLE
Play icon not displaying in search results/collection lists.

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1078]
Example: https://stage.popuparchive.com/collections/938
![screen shot 2015-04-20 at 1 22 27 pm](https://cloud.githubusercontent.com/assets/9256525/7237323/54ab0a86-e760-11e4-853e-ff287e078b7c.png)

Another example: https://stage.popuparchive.com/search?page=1&query=castle

**Comment by pkarman** [comment]
seems to a css/angular problem.

**Comment by pkarman** [comment]
stage index needed rebuild so that audio_files and image_files are in the index.

**Comment by tarakieffer** [comment]
Looks good now.
![screen shot 2015-04-21 at 12 48 15 pm](https://cloud.githubusercontent.com/assets/9256525/7258849/b4934d04-e824-11e4-869d-f2c0ef196639.png)
