### ISSUE TITLE
log subscription events to active_admin_comments

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1079]
See #1077. Log subscription events to our own db and generate reports from that.

**Comment by pkarman** [comment]
related to #1045

**Comment by pkarman** [comment]
@Saltzshaker @annewootton 
what kind of data would be most useful in a report on stripe subscription events? New plan vs old plan?

**Comment by Saltzshaker** [comment]
User info, old, and new plan, upgrade/downgrade

**Comment by pkarman** [comment]
In order to get some real data against which I can write a meaningful report, I'm going to push this feature to production and start accumulating data now. The report can come later in #1084.

**Comment by pkarman** [comment]
```
pop-up-archive::RED=> select * from active_admin_comments;
 id | namespace | body | resource_id | resource_type | author_id | author_type | created_at | updated_at 
----+-----------+------+-------------+---------------+-----------+-------------+------------+------------
(0 rows)
```

will run again tomorrow and trust that some records will have been created.

**Comment by pkarman** [comment]
```
pop-up-archive::RED=> select count(*) from active_admin_comments where namespace = 'stripe';
 count 
-------
     8
(1 row)
```

considering this complete.
