### ISSUE TITLE
Search not working on PUA

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1082]
All items returned regardless of search: 
![screen shot 2015-04-23 at 10 32 09 am](https://cloud.githubusercontent.com/assets/8497203/7303250/19c4bc96-e9a4-11e4-8b7c-123650eda5eb.png)

@baileyspace says it's working in staging

**Comment by Saltzshaker** [comment]
Seems to be mysteriously working again. @baileyspace says in the API seemed like all search queries were redirecting to a search endpoint without a query

**Comment by pkarman** [comment]
might have a JS caching issue, due to the deploy last night? glad it's working now.

**Comment by Saltzshaker** [comment]
Same thing is happening again.

**Comment by Saltzshaker** [comment]
Now it's working for me again too. I guess I'll re-close and keep an eye on it. And I'll send you a link if it happens again.
