### ISSUE TITLE
Durations being calculated inaccurately?

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1090]
From CUNY:

"I noticed that a bunch of our shows are registering basically as double the amount of time, like the INSO07029 show that I uploaded today is coming up with a duration of 56:28 and it’s a half hour show. I am looking under the “usage” area for this month under “my account” and am noticing that a lot of our half hour shows are being doubled in their duration to almost hour long shows and I think this has eaten up our 40 hours for the month. Am I reading this right or did I get it all wrong?"

Specifically: 
https://www.popuparchive.com/collections/4494/items/37920

Dave Rice says:
soxi -D gives 1694.328 aka 28:14.328 but on your site it's double 56:28
you can even see in the player, play and scrub to end and your at 28:14/56:28

could do-a ffprobe file.mp3 -show_entries format=duration -of json

i remember some utility not handling mp3 duration well, it had some presumption that wasn't true in my case. i thought is was soxi but can't reproduce. curious if updating soxi fixing the issue.

**Comment by pkarman** [comment]
@kookster the result from fixer was this:

```json
{"status":"complete",
"message":"analysis complete",
"info":{"size":27109440,
"content_type":"audio/mpeg",
"channel_mode":"Stereo",
"bit_rate":64,"length":3388,
"sample_rate":48000,
"version":1,
"layer":3
},"logged_at":"2015-04-30T13:17:53Z"}
```
https://www.popuparchive.com/superadmin/tasks/362847

Anything look odd to you?

**Comment by pkarman** [comment]
file at s3://pop-up-archive/inso07029-mp3.ERTcla.popuparchive.org/INSO07029.mp3

**Comment by kookster** [comment]
it is slightly more complicated than I remembered.

there had been a bug at one point where the lengths were off, and so what it now does is take the larger of the values from Mp3Info gem (https://github.com/moumar/ruby-mp3info) or soxi -D:

```

    def info_for_mpeg(mpeg_path, info = nil)
      logger.debug "info_for_mpeg: start"
      length = audio_file_duration(mpeg_path)
      info ||= Mp3Info.new(mpeg_path)
      result = {
        :size         => File.size(mpeg_path),
        :content_type => 'audio/mpeg',
        :channel_mode => info.channel_mode,
        :bit_rate     => info.bitrate,
        :length       => [info.length.to_i, length.to_i].max,
        :sample_rate  => info.samplerate,
        :version      => info.mpeg_version, # mpeg specific
        :layer        => info.layer # mpeg specific
      }

      # indicate this can be GC'd
      info = nil

      result
    end
```

It seems like for these files, the Mp3Info must be wrong to the tune of double the value.

I think it might be related to the fact that it is also coming back with a bitrate that is half as much (64 instead of 128).

**Comment by kookster** [comment]
so I don't lose it, here is a part of the fixer log where it is calculating the length right via soxi:
```
2015-04-30 20:56 22689 TID-ovcegcmfo INFO: notify_task_processing: 2015-04-30 20:56:41 +0000, task: 460014
2015-04-30 20:56 22689 TID-ovcegcmfo INFO: s3_download_file: try: 1, checking for inso07029-mp3.ERTcla.popuparchive.org/INSO07029.mp3 in pop-up-archive
2015-04-30 20:56 22689 TID-ovcegcmfo INFO: run_command: /usr/local/bin/soxi -V0 -D '/var/www/domains/prx.org/beta.fixer/deployments/releases/1669938cc29009a95de0aa4f0733c17e407662a3/tmp/audio_monster/INSO07029.mp320150430-22689-uhotpv.mp3'
2015-04-30 20:56 22689 TID-ovcegcmfo INFO: update_task: 2015-04-30 20:56:55 +0000, task: 460014, result_details: {:status=>"complete", :info=>{:size=>27109440, :content_type=>"audio/mpeg", :channel_mode=>"Stereo", :bit_rate=>64, :length=>3388, :sample_rate=>48000, :version=>1, :layer=>3}, :message=>"analysis complete"}
```

**Comment by kookster** [comment]
and a bit more info, the latest (as of March) version of the `mp3info` gem seems to work correctly, probably b/c of this fix for handling frame parsing with VBR (variable bit rate) mp3s:
https://github.com/moumar/ruby-mp3info/pull/53

before:
```
irb(main):013:0> info ||= Mp3Info.new(mpeg_path)
=> #<Mp3Info:0x007ff6a5d1f378 @filename_or_io="/Users/andrew/Downloads/inso07029-mp3.ERTcla.popuparchive.org/INSO07029.mp3", @tag_parsing_enabled=true, @mp3_parsing_enabled=true, @id3v2_options={}, @header={:layer=>3, :bitrate=>64, :samplerate=>48000, :mpeg_version=>1, :padding=>false, :size=>192, :error_protection=>false, :private=>true, :mode_extension=>0, :copyright=>false, :original=>false, :emphasis=>0, :channel_num=>0, :channel_mode=>"Stereo"}, @io_is_a_file=true, @io=#<File:/Users/andrew/Downloads/inso07029-mp3.ERTcla.popuparchive.org/INSO07029.mp3>, @io_size=27109440, @filename="/Users/andrew/Downloads/inso07029-mp3.ERTcla.popuparchive.org/INSO07029.mp3", @tag_orig={}, @tag1_orig={}, @tag={}, @tag1={}, @tag2={"TXXX"=>["major_brand\u0000qt  ", "minor_version\u0000512", "compatible_brands\u0000qt  "], "TSSE"=>"Lavf56.25.101", "RVA2"=>"normalize\x00\x01\v2\x00"}, @tag1_parsed=true, @first_frame_pos=256, @mpeg_version=1, @layer=3, @channel_mode="Stereo", @channel_num=0, @bitrate=64, @samplerate=48000, @vbr=true, @length=3388.648>
```

after:
```
irb(main):002:0> info ||= Mp3Info.new(mpeg_path)
=> #<Mp3Info:0x007ff8de049550 @filename_or_io="/Users/andrew/Downloads/inso07029-mp3.ERTcla.popuparchive.org/INSO07029.mp3", @tag_parsing_enabled=true, @mp3_parsing_enabled=true, @id3v2_options={}, @header={:layer=>3, :bitrate=>64, :samplerate=>48000, :mpeg_version=>1, :padding=>false, :size=>192, :error_protection=>false, :private=>true, :mode_extension=>0, :copyright=>false, :original=>false, :emphasis=>0, :channel_num=>0, :channel_mode=>"Stereo"}, @io_is_a_file=true, @io=#<File:/Users/andrew/Downloads/inso07029-mp3.ERTcla.popuparchive.org/INSO07029.mp3>, @io_size=27109440, @filename="/Users/andrew/Downloads/inso07029-mp3.ERTcla.popuparchive.org/INSO07029.mp3", @tag_orig={}, @tag1_orig={}, @tag={}, @tag1={}, @tag2={"TXXX"=>["major_brand\u0000qt  ", "minor_version\u0000512", "compatible_brands\u0000qt  "], "TSSE"=>"Lavf56.25.101", "RVA2"=>"normalize\x00\x01\v2\x00"}, @tag1_parsed=true, @first_frame_pos=256, @mpeg_version=1, @layer=3, @channel_mode="Stereo", @channel_num=0, @bitrate=127.99909344589713, @samplerate=48000, @vbr=true, @length=1694.328>
```

**Comment by baileyspace** [comment]
FWIW, I downloaded this file from PUA and opened it in VLC, which was
reporting a duration of 56:28

[image: Imagem inline 1]

and then I clicked on Chrome so I could write this email, and when I went
back to the player I saw this!!

[image: Imagem inline 2]

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-04-30 14:23 GMT-07:00 Andrew Kuklewicz <notifications@github.com>:

**Comment by kookster** [comment]
@baileyspace your images don't seem to have come through, but I suspect you are showing conflicting results.

The mp3 in question seems to be a variable bit rate file, with the first part of it at 64 k, and later parts at high bitrates.

If a program tries to determine length without parsing the entire file (e.g. just using header data and initial 100 frames or so) it is highly likely to get the wrong duration - from what I can tell, that is what the Mp3Info gem seems to be doing wrong (prior to its recent fixes), and I suspect other impls could be making similar errors.

**Comment by annewootton** [comment]
Once this ticket is addressed we need to recalculate durations for CUNY.

**Comment by pkarman** [comment]
fixed upstream and deployed on our fixer:

```
[puauser@ip-172-31-0-232 fixer.prx.org]$ grep mp3info Gemfile.lock 
      ruby-mp3info (~> 0.8.6)
      ruby-mp3info (>= 0.6.13)
    ruby-mp3info (0.8.6)
[puauser@ip-172-31-0-232 fixer.prx.org]$ bundle show ruby-mp3info
/home/puauser/.rvm/gems/ruby-2.2.1/gems/ruby-mp3info-0.8.6
```

**Comment by pkarman** [comment]
@annewootton do we still need to re-calculate CUNY stuff from May?

**Comment by annewootton** [comment]
How much effort? They aren't complaining but the record for their account is inaccurate.

**Comment by pkarman** [comment]
Probably a few hours. Would need to:

* identify a range of Items to re-calculate
* download mp3 for each item
* run mp3info on each item
* compare recorded duration against mp3info duration and update if necessary

If we do need to do this, we should open pua-internal ticket to track.

**Comment by annewootton** [comment]
Let's let it go for now.
ᐧ
