### ISSUE TITLE
Fix tplayer styles using oEmbed for Wordpress 

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1099]
![image](https://cloud.githubusercontent.com/assets/833332/7556573/684c51a0-f72b-11e4-8f75-b074589eb3e7.png)

**Comment by baileyspace** [comment]
I added full paths instead of the relative paths to the script element, and that's got the JS and CSS loading. The styles still need to be tweaked in order to scale appropriately for any given theme

![image](https://cloud.githubusercontent.com/assets/833332/7602955/468721e2-f8e0-11e4-9fc6-849ec725acff.png)

**Comment by baileyspace** [comment]
Added /embed_test.html for future testing

**Comment by baileyspace** [comment]
Well... It's working (mostly) and presentable.
![image](https://cloud.githubusercontent.com/assets/833332/7673120/ec01aa3c-fcc0-11e4-9e9f-0c61a2a265ac.png)

But still having trouble with twitter sharing even after having added bootstrap.

**Comment by annewootton** [comment]
It's looking good! At the risk of asking for something way more complicated than is apparent to the eye, is there any chance we could tighten the spacing at all so the transcript lines aren't so spread out? Can post some examples of other players that do this well if that would be helpful.

**Comment by baileyspace** [comment]
Can do. Our line height is probably being overidden by the wp stylesheet.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-05-17 20:01 GMT-07:00 annewootton <notifications@github.com>:

**Comment by annewootton** [comment]
@baileyspace ++
