### ISSUE TITLE
Fork over Audiosear.ch clients as Pop Up SDKs

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1101]

**Comment by pkarman** [comment]
https://github.com/popuparchive/pua-sdk-python

**Comment by pkarman** [comment]
https://github.com/popuparchive/pua-sdk-php

**Comment by pkarman** [comment]
Wiki updated: https://github.com/popuparchive/pop-up-archive/wiki/API

developer site also updated.
