### ISSUE TITLE
This file took a very long time to get to SM

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1105]
We're now confident enough to say we've been consistently hearing from customers wondering what's taking their transcripts so long.

The file for this item: https://www.popuparchive.com/superadmin/items/38345 is now being transcribed, but it only started transcribing <20 min ago so it doesn't seem to be an issue with SM.

**Comment by pkarman** [comment]
The AnalyzeAudio task appears to have hung up for 4 hours, till the nudger pushed it along, and that triggered the Transcribe task to start.

https://www.popuparchive.com/superadmin/tasks/394190

**Comment by baileyspace** [comment]
I think that was the case with the file from yesterday as well (an exceedingly long analyze period).

**Comment by baileyspace** [comment]
Poking around another slow moving file (44767). I printed it out the task type, date_created and date_udated for each task, it looks like the transcribe task didn't start until the transcode task completed, even though this file was originally an mp3. I also looked at the audio_file.rb, and @pkarman is correct, if the file is an mp3, it should begin transcribing immediately after analyze.

#<Tasks::SpeechmaticsTranscribeTask:0x007fcb416f7070>
2015-05-16 01:04:34 UTC
2015-05-16 01:04:46 UTC
#<Tasks::TranscodeTask:0x007fcb41d7bec8>
2015-05-15 23:46:10 UTC
2015-05-16 01:04:34 UTC
#<Tasks::AnalyzeAudioTask:0x007fcb41812dd8>
2015-05-15 23:46:10 UTC
2015-05-15 23:46:18 UTC
#<Tasks::UploadTask:0x007fcb3ee39200>
2015-05-15 23:45:18 UTC
2015-05-15 23:46:10 UTC

**Comment by pkarman** [comment]
looks like the transcode task was waiting for fixer to finish. the timestamp in results is the same as the update_time:
https://www.popuparchive.com/superadmin/tasks/395239

It sounds like what I'm hearing in this ticket thread is that if the incoming file is already a .mp3 format, the transcribe tasks should be created immediately after upload finishes, at the same time the transcode and analyze_audio tasks are created.

**Comment by annewootton** [comment]
I'm good with that. Since that change will only affect mp3 files, it might
not 100% answer the question of why transcoding seems to be taking longer
than usual and/or transcripts are slower to come back, but all we can do is
troubleshoot these specific cases as we come across them.

**Comment by baileyspace** [comment]
Related from the ghost of tickets past: https://github.com/popuparchive/pop-up-archive/issues/953 and https://github.com/popuparchive/pop-up-archive/pull/956

**Comment by baileyspace** [comment]
We should probably give the audio file model a little TLC next week (https://codeclimate.com/github/popuparchive/pop-up-archive/AudioFile). It's had a lot of changes over time; it could use a spring cleaning.

**Comment by pkarman** [comment]
Not sure how much can really be cleaned. I've had my hands on it pretty heavily the last 6 months, mostly recently to optimize performance (instead of optimizing readability).

I think this patch will do what we want. Right now the premium_transcribe_audio method is only called on UPDATE not on INSERT. The transcribe_audio method is called on both.

```
diff --git a/app/models/audio_file.rb b/app/models/audio_file.rb
index 4b9d52c..ebc5f04 100644
--- a/app/models/audio_file.rb
+++ b/app/models/audio_file.rb
@@ -225,6 +225,8 @@ class AudioFile < ActiveRecord::Base
 
     transcribe_audio
 
+    premium_transcribe_audio
+
   rescue Exception => e
     logger.error e.message
     logger.error e.backtrace.join("\n")
```

**Comment by pkarman** [comment]
In the Dottie branch.

**Comment by pkarman** [comment]
Now I'm not so sure. This line:

```
326   def start_premium_transcribe_job(user, identifier, options={})
327     return if (duration.to_i <= 0)
```

seems to suggest that the premium transcript task will never get fired until there is a duration set, which is dependent on at least one other task (AnalyzeAudio or Transcode) finishing first. So I don't expect the code change to make a difference.

IIRC the reason we check for duration is that we had a case where zero-length audio was getting put into the queue and never succeeding (for obvious reasons). Maybe that's less of an issue now.

@baileyspace thoughts?

**Comment by kookster** [comment]
we also needed the duration to know what to charge people for the transcript cost - and in some cases show the cost before they decide to order the transcript.

**Comment by baileyspace** [comment]
Both of those things are true. We might just have to live with it.  That said, the duration is only necessary for transcripts ordered a la carte, so we could only wait for the duration in the event that the premium transcript request originates from an a la carte premium transcript request.

**Comment by annewootton** [comment]
There seems to have been something fundamentally up with transcode tasks since the code didn't change, but we started getting user complaints en masse last week. Perhaps it was related to all the tasks created as a result of the archive.org bug, in which case this duration stuff hopefully doesn't matter too much.

Also, @baileyspace — I don't think what you're suggesting would work: how could we only wait for durations "in the event that the premium transcript request originates from an a la carte premium transcript request" for the use case @kookster is describing, when there is *no* premium transcript ordered yet? (This use case occurs for files uploaded to the community plan, and then we give them option to "Reprocess as premium" and tell them how much it will cost. Otherwise, i.e. if someone is over their limit and orders a premium transcript in excess of their limit, we just tell them they're gonna get billed at the rate of $22/hr because it takes too long to wait for the duration to calculate in the moment.)
