### ISSUE TITLE
Add Pop Up Archive API to GA

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1108]

**Comment by pkarman** [comment]
since the Angular UI uses the API exclusively, I am wondering how/if we want to distinguish normal UI-based API usage from non-browser-agent API usage. Thoughts? @baileyspace

**Comment by baileyspace** [comment]
We should definitely distinguish. I guess we could use an internal and
external subdomain.

Pop Up Archive
popuparchive.com




2015-05-18 12:19 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by pkarman** [comment]
subdomain could work. I was thinking more about adding a small parameter on the UI side that indicated the use case. So all the /api URLs that ended with `&ui=1` could be ignored from an analytics perspective.

**Comment by baileyspace** [comment]
Works for me.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-05-18 12:54 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by pkarman** [comment]
confirmed data flowing into GA
