### ISSUE TITLE
Add transcripts to WordPress plugin

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1116]
Aldertrack and GCLA (both new customers) need this, particularly because some transcripts are coming from private collections and thus won't work with our standard embed options. Since WP plugin OAuths to Pop Up Archive, we should be able to get private transcripts to show when implemented through the plugin.

**Comment by pkarman** [comment]
By "transcripts" do you mean, using the tplayer oEmbed instead of the older embed_player iframe? Or some other kind of transcript presentation?

**Comment by baileyspace** [comment]
I think offering the choice of either the old player or the full player
would be ideal.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-05-26 12:46 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by annewootton** [comment]
Yes, tplayer (@baileyspace, correct me if I'm wrong).

This was prompted by a customer wanting to embed transcripts on a password-protected WP site, and tplayer OEmbed fell short -- seemed like we might as well integrate tplayer directly w/ WP plugin. Other option could be to add the necessary credentials for displaying tplayer for private items via OEmbed... open to your thoughts if you have an opinion.

**Comment by pkarman** [comment]
ok, version 1.1 (current version) of the WP plugin is now tagged on github.

master branch now is version 1.2 with optional tplayer embed via oEmbed:
https://github.com/popuparchive/popuparchive-wp

You get the tplayer instead of older embed_player by using the *tplayer* shortcode attribute (documented in the Usage tab of the WP plugin settings).

If that's acceptable, we can tag 1.2 and upload to Wordpress plugins site.

**Comment by baileyspace** [comment]
That sounds great.

Pop Up Archive
popuparchive.com




2015-05-26 13:48 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by annewootton** [comment]
++

**Comment by pkarman** [comment]
version 1.2 on wordpress.org: https://wordpress.org/plugins/pop-up-archive-for-wp/developers/
