### ISSUE TITLE
Files added to a existing collection (or item) are failing

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1119]
https://stage.popuparchive.com/superadmin/audio_files/29746
![screen shot 2015-05-29 at 1 59 09 pm](https://cloud.githubusercontent.com/assets/9256525/7890327/03cf32a8-060b-11e5-8f13-d491abf75c5e.png)

**Comment by pkarman** [comment]
changed storage config but same issue as #1120 so I think you should delete and start over.

**Comment by tarakieffer** [comment]
This didn't fail immediately, but it is still processing after 30 mins.  Just in case anyone wants to follow along on the waiting:
https://stage.popuparchive.com/superadmin/audio_files/29751

**Comment by pkarman** [comment]
anything that doesn't finish in about 15 min is probably stuck somewhere.

**Comment by pkarman** [comment]
ok the storage config was getting set incorrectly on new audio. please delete and re-do.

**Comment by tarakieffer** [comment]
I think this is good now.

https://stage.popuparchive.com/superadmin/audio_files/29751
![screen shot 2015-05-29 at 6 08 04 pm](https://cloud.githubusercontent.com/assets/9256525/7894340/d5cb7cb8-062d-11e5-842b-185552d04d8c.png)
