### ISSUE TITLE
File added by url is not getting any tasks.

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1120]
Two examples
Collection created today: https://stage.popuparchive.com/superadmin/audio_files/29747
![screen shot 2015-05-29 at 2 05 50 pm](https://cloud.githubusercontent.com/assets/9256525/7890468/d9444108-060b-11e5-9030-2b04d5aecdfb.png)

Existing collection:https://stage.popuparchive.com/superadmin/audio_files/29742

**Comment by pkarman** [comment]
ok once I set the storage_configuration correctly for the parent collection, clicking the Recover button in superadmin sent these on their way immediately.

however it seems like the existing collection file 29742 has other problems now, involving the storage switch. I think we should delete it and start over to verify.

**Comment by tarakieffer** [comment]
This file added by url got a transcript: https://stage.popuparchive.com/superadmin/audio_files/29748

The status is 'Premium transcript complete.'  The analyze task does still have a status of 'working.'  I don't know if I am just being impatient or remember if that is acceptable.

**Comment by pkarman** [comment]
finished already. often takes a little bit because it uses 3rd party services (opencalais, yahoo, etc).

**Comment by tarakieffer** [comment]
Great.
