### ISSUE TITLE
Basic Transcripts are not completing

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1122]
Uploaded file:
https://stage.popuparchive.com/superadmin/audio_files/29755

Added by link:
https://stage.popuparchive.com/superadmin/audio_files/29756

Both were added to a collection that was created on Friday.  https://stage.popuparchive.com/superadmin/collections/3752

**Comment by pkarman** [comment]
the problem is that fixer doesn't seem to let me create a sequence of tasks the way it used to. I have opened this ticket to track the issue upstream: https://github.com/PRX/fixer.prx.org/issues/33

**Comment by pkarman** [comment]
PR created and approved: https://github.com/PRX/fixer.prx.org/pull/34

**Comment by kookster** [comment]
and now merged.

**Comment by pkarman** [comment]
confirmed that PRX/fixer.prx.org#34 fixed this particular problem.

there are still some issues, tracking upstream in https://github.com/PRX/fixer_client/issues/2 and https://github.com/PRX/audio_monster/issues/8

**Comment by pkarman** [comment]
upstream issues seem resolved, and I was able to recover one of the troubled files:
https://stage.popuparchive.com/superadmin/audio_files/29755

I would suggest testing this again from the top with a new item.

**Comment by tarakieffer** [comment]
I tried this again this morning.  I did have four files complete, but I never received an email notification.

https://stage.popuparchive.com/superadmin/audio_files/29773
https://stage.popuparchive.com/superadmin/audio_files/29774
https://stage.popuparchive.com/superadmin/audio_files/29775
https://stage.popuparchive.com/superadmin/audio_files/29776

I did get impatient after 30 mins or so on a couple of them and clicked 'Recover.'

**Comment by tarakieffer** [comment]
My mistake. These were all preview transcripts and therefore should not get the email notification.  So these all work as expected.
