### ISSUE TITLE
Tplayer loading slowly?

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1131]
Not sure if we can do anything about this, but it takes >30 seconds for the tplayers to load on this page, at least in my experience: http://studsterkel.org/categories/chicago.

Anyone else?

**Comment by pkarman** [comment]
they snapped up for me before I could scroll down to them.

**Comment by annewootton** [comment]
That's a good sign...
ᐧ

**Comment by pkarman** [comment]
attached a Firebug screensnap showing load times for the 4 tplayer and oembed URLs. All pretty snappy imo.

![studs-terkel-embed-load-times](https://cloud.githubusercontent.com/assets/1205061/8014586/aef48eee-0b97-11e5-9876-a14d9e18ee3e.png)

**Comment by pkarman** [comment]
I don't think we can make them any faster, at least not in any way obvious to me.

**Comment by annewootton** [comment]
Got it, thanks. Just concerned when emailing examples to people and not wanting them to be janky.
