### ISSUE TITLE
Date picker doesn't populate month

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1132]
This is on the upload form.

![screen shot 2015-06-05 at 3 23 40 pm](https://cloud.githubusercontent.com/assets/9256525/8014635/fa1e715a-0b97-11e5-8fd8-cde683a44707.png)

**Comment by pkarman** [comment]
fixed missing month, and also missing icons.

**Comment by tarakieffer** [comment]
Month is populating.  This is a different format that is currently in production this is yyyy-mm-dd instead of mm-dd-yyyy.  However, it is now consistent with how the date displays in the Metadata section of the item page.

![screen shot 2015-06-05 at 5 00 41 pm](https://cloud.githubusercontent.com/assets/9256525/8016089/b235db5a-0ba4-11e5-84ac-b5f3995c60f2.png)

**Comment by pkarman** [comment]
yes, I changed the format to match what displays, for consistency.

I'm not sure how this ever worked before. The standard syntax for month is **MM** (uppercase) not mm (lowercase).
