### ISSUE TITLE
Completed file upload notification does not display.

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1133]
No "Congratulations! <FileName> upload completed. View and edit the items!"
And the file progress says 'Complete' but the progress bar does not change to reflect this.

![screen shot 2015-06-05 at 3 34 22 pm](https://cloud.githubusercontent.com/assets/9256525/8014753/d2618e94-0b98-11e5-971b-6b7a9f782501.png)

**Comment by pkarman** [comment]
@baileyspace I am going to assign this to you because I think the alerts dropdown needs some more styling work. I have made some commits to the bobbie branch (mentioned on this ticket) that should help get you started.

**Comment by tarakieffer** [comment]
The message is displaying, but the link to 'View and edit' the item is not working.

![screen shot 2015-06-09 at 6 56 10 am](https://cloud.githubusercontent.com/assets/9256525/8057164/a5f60572-0e74-11e5-8a74-31e70abfc560.png)
