### ISSUE TITLE
Making is_billable=false does not affect processing time

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1139]
This user's total was 6h: 25m: 5s before and after changing is_billable to false on two files. 

User: https://www.popuparchive.com/superadmin/users/1973
For example: https://www.popuparchive.com/superadmin/audio_files/46068
and https://www.popuparchive.com/superadmin/audio_files/46075

**Comment by pkarman** [comment]
fixed and deployed. monthly usage now (0d: 5h: 40m: 42s)
