### ISSUE TITLE
Slim down search bar 

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1140]
Bootstrap issue:
![screen shot 2015-06-15 at 11 03 45 am](https://cloud.githubusercontent.com/assets/8497203/8166708/561d812c-134e-11e5-8ed8-b53d3f2305d7.png)

**Comment by tarakieffer** [comment]
![screen shot 2015-07-20 at 2 20 26 pm](https://cloud.githubusercontent.com/assets/9256525/8785021/8428515c-2eea-11e5-81c0-f29213b51e53.png)
