### ISSUE TITLE
disable speaker id editing where not supported in transcript

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1143]
Verify transcript speaker ids cannot be edited where they are not already assigned by the transcriber.

**Comment by pkarman** [comment]
confirmed: speaker ids cannot be assigned if the underlying timed_text record has a null speaker_id.

**Comment by annewootton** [comment]
@pkarman does this extend to downloading transcripts too? The former (current?) logic for exporting text transcripts is if premium, then break on speaker changes. Without speaker ids, would need to change that to break every 0:30 like we do for basic transcripts.

**Comment by pkarman** [comment]
@annewootton as near as I can tell, from reading the code, downloading a transcript pays no attention to whether the transcript is premium vs basic. It only takes all the timed_text records and concatenates them.

All the premium transcript tasks, regardless of the upstream provider, create timed_text chunks of 5 seconds. I.e. one timed_text record is about 5 seconds.

I suggest we come up with some specific examples of existing transcript downloads and confirm that the new format is as desired.

**Comment by pkarman** [comment]
I have changed the template to use the `transcript.has_speaker_ids` method to detect which template partial to use.

**Comment by pkarman** [comment]
since this is in master, it is in production now. @tarakieffer can you give it a spin there? The test is whether there is any regression in editing speaker ids.

**Comment by tarakieffer** [comment]
Clicking 'Save Contributors' doesn't seem to do anything.  I see as the added contributors update on the Item page as I define them.  Clicking 'Save Contributors' does not look like it changes anything and the modal doesn't close.

![screen shot 2015-08-21 at 1 09 41 pm](https://cloud.githubusercontent.com/assets/9256525/9415575/f26947e6-4805-11e5-928c-15c7c746c54f.png)

Otherwise assigning speakers seems to behave the same.  However, is there a change to reduce the likelihood to have speakers identified on premium transcripts?  

Examples: https://pop-up-archive-staging.herokuapp.com/collections/3762/items/24523
https://pop-up-archive-staging.herokuapp.com/collections/3765/items/24524

**Comment by pkarman** [comment]
I think the 'Save Contributors' bug is a Bootstrap 3 migration bug, and it existed already. It's not about the transcript type or speaker id. I will look at it.

**Comment by pkarman** [comment]
It looks to me like 'Save Contributors' is actually saving the underlying Item. I'm not sure that is desired or not. I would be inclined to comment that button out until we can decide what the UX here should be, since I'm confused by it.

**Comment by pkarman** [comment]
@tarakieffer I don't understand your question:
"is there a change to reduce the likelihood to have speakers identified on premium transcripts?"

There are no more speaker ids for new premium transcripts at all. That's what we wanted to test here, whether that broke anything.

**Comment by baileyspace** [comment]
Yes, it should save to the underlying item. When a new speaker as added, that person is added as a contributor on the item. That said, the UX is admittedly confusing. We've held off updating it because this feature doesn't get a lot of action.

**Comment by tarakieffer** [comment]
@pkarman - Ah, I missed that this was change to no longer have speaker ids in transcripts.  I just thought there was identified situations where sometimes they were not getting defined.

**Comment by pkarman** [comment]
@annewootton @baileyspace so is there anything to be done here? It sounds like it is working as it always has, which was what the ticket was to verify.

**Comment by baileyspace** [comment]
Yes, verify that clicking "Save Contributors" is actually saving the contributors.

**Comment by annewootton** [comment]
And @tarakieffer: confirm that speaker ID editing is disabled for transcripts without speaker IDs.

**Comment by tarakieffer** [comment]
1) Confirmed 'Save Contributors' saves contributors with the latest change.

2) For a transcript with no speaker ids, I am able to still click Assign Speakers and define additional contributors, but there is no Speaker Id dropdown to associate the contributors with.
![screen shot 2015-08-21 at 2 42 37 pm](https://cloud.githubusercontent.com/assets/9256525/9417604/321e4956-4813-11e5-9dc0-0829cbee061f.png)

3) For a transcript without speaker ids, while editing there is no place to click to defined speakers.
![screen shot 2015-08-21 at 2 42 54 pm](https://cloud.githubusercontent.com/assets/9256525/9417603/2e950c98-4813-11e5-8491-d33a8b7de946.png)

4) For a transcript WITH speaker ids, I am able to Assign Speakers and define contributors associated with the different ids.
![screen shot 2015-08-21 at 2 51 05 pm](https://cloud.githubusercontent.com/assets/9256525/9417720/28f61d58-4814-11e5-80d1-c3d6f1770f20.png)

5) For a transcript WITH speaker ids, I am to click on the speaker id while editing to choose a different speaker id for any line.
![screen shot 2015-08-21 at 2 44 22 pm](https://cloud.githubusercontent.com/assets/9256525/9417593/2aa1222a-4813-11e5-838d-b3c407044f9a.png)

**Comment by baileyspace** [comment]
I went ahead and hid the assign speaker button when not available and confirmed it's working in staging.
