### ISSUE TITLE
Item.identifier field not searchable in PUA

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1145]
For example, take item https://www.popuparchive.com/collections/938/items/6903

Item.identifier = 1856688-3-1

Searching for "1856688-3-1" on popuparchive.com returns many results (i.e. transcripts containing the number "1") but not item 6903.

@baileyspace says that searching for identifier:"1856688-3-1" does return the item (although I am not able to recreate; maybe my syntax is wrong).

If item identifiers are included in the index, why aren't they searchable as part of PUA search like other indexed fields?

This question came from a customer who is trying to search on identifier within their collections.

**Comment by baileyspace** [comment]
Query => identifier:"525A"
https://www.popuparchive.com/search?page=1&query=identifier:%22525A%22

**Comment by pkarman** [comment]
ES will tokenize a string on non-word characters. A dash is a non-word character (@baileyspace is correct).

If you put it in double-quotes, the search looks for all the tokens in sequence, so it has the effect of "ignoring" the dashes.

E.g. `somefield:foo-bar` is parsed as "find `foo` in field `somefield` and `bar` anywhere".

But `somefield:"foo-bar"` is parsed as "find `foo` and `bar` in sequence in field `somefield`".

**Comment by annewootton** [comment]
There are a few questions here.

1) Why does this double-quoted search return tokenized results? https://www.popuparchive.com/search?page=1&query=identifier:%221856688-3-1%22

2) On Audiosear.ch it seems like we favor exact matches before tokenized matches. Is that not true on Pop Up Archive (or am I misunderstanding something more general)?

3) Why do we have to put identifier: in front of the search term? Users aren't inclined to do that (and they don't have to do that to search, for example, titles) — they just type the field value of what they're looking for.

**Comment by pkarman** [comment]
1) there was a bug in the query parser. Fixed and deployed now.

2) Both sites use the same query parser. It has been fixed on both sites now.

3) You don't need the field, if the value is unique.

https://www.popuparchive.com/search?page=1&query=identifier:%221856688-3-1%22
https://www.popuparchive.com/search?page=1&query=%221856688-3-1%22

^^ both URLs should return exactly one result.

**Comment by annewootton** [comment]
Cool, much better! And that explains why people have been asking about
exact phrase matching on Audiosear.ch too...

Last question: shouldn't the query
https://www.popuparchive.com/search?page=1&query=1856688-3-1 (same as your
examples but without double quotes) return the exact match before results
with, say, the number "1" in them?
