### ISSUE TITLE
Contact modal style fix

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1146]

**Comment by tarakieffer** [comment]
![screen shot 2015-07-21 at 6 53 05 am](https://cloud.githubusercontent.com/assets/9256525/8800071/2d1ef2c2-2f75-11e5-888f-3fdb998b6fc4.png)

**Comment by annewootton** [comment]
What's that button to the right of Name that says "Pop Up Archive"?

**Comment by tarakieffer** [comment]
Oops.  That is not a button, that is some hover text hanging around.   A nice reminder to preview my screenshots.

![screen shot 2015-07-21 at 10 44 19 am](https://cloud.githubusercontent.com/assets/9256525/8805264/e9fc7fac-2f95-11e5-886b-42201ed79845.png)

**Comment by annewootton** [comment]
:-D
