### ISSUE TITLE
disallow adding new Files to existing Items

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1148]

**Comment by pkarman** [comment]
once an Item is created, should not be able to upload another audio file.

**Comment by tarakieffer** [comment]
Edit Item form no longer has the fields to add an audio file by uploading or URL.  Also, dragging a file to the form does not add it.

![screen shot 2015-07-10 at 6 39 01 am](https://cloud.githubusercontent.com/assets/9256525/8617937/885d0d54-26ce-11e5-94fc-63a6873e0e0d.png)

Confirmed still able to modify other form fields and upload an image.
