### ISSUE TITLE
404s for focus580 collection

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1150]
Clicking on these items in this collection returns 404 errors: https://www.popuparchive.com/collections/2448/
For example:
https://www.popuparchive.com/collections/2448/items/27931
https://www.popuparchive.com/collections/2448/items/28722

**Comment by pkarman** [comment]
needed a `rake db:migrate` and app restart. should be ok now. please confirm.

**Comment by Saltzshaker** [comment]
yep, working now. thanks!
