### ISSUE TITLE
Fix Sign Up button! (Bootstrap)

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1151]
https://www.popuparchive.com/users/sign_up?plan_id=community
![screen shot 2015-07-08 at 2 36 13 pm](https://cloud.githubusercontent.com/assets/8497203/8582937/c0b885c6-257e-11e5-871e-2721985fab2e.png)

**Comment by tarakieffer** [comment]
![screen shot 2015-07-21 at 7 25 19 am](https://cloud.githubusercontent.com/assets/9256525/8800581/adac9814-2f79-11e5-959f-76d2dba2d208.png)
