### ISSUE TITLE
Only allow single file uploads

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1153]

**Comment by pkarman** [comment]
feature branch: single-file-upload

**Comment by pkarman** [comment]
merged to miley branch

**Comment by tarakieffer** [comment]
Create Audio form does not have fields/buttons to add additional files.

![screen shot 2015-07-20 at 1 55 21 pm](https://cloud.githubusercontent.com/assets/9256525/8784379/60549b3a-2ee7-11e5-9eab-04e821320995.png)

If user drags multiple files to upload, error message displays.
![screen shot 2015-07-20 at 1 56 52 pm](https://cloud.githubusercontent.com/assets/9256525/8784428/badbe1e4-2ee7-11e5-9823-a59227564971.png)

Clicking Save at this point, closes modal and does not save item.

Removing files until only one remains, I can save the item and the file is uploaded.
