### ISSUE TITLE
Make Radio Race promo code/custom sign-up page

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1154]
Not sure how we want to do this. Seems like we could adapt the PRX beta-tester code that's in there and make a custom Radio Race sign up page which puts them on the one-hour plan.

Actually...now that I think about it, by the time this happens, the community plan will essentially be a free hour, so how will this offer be different? Are we offering them a free month *after* the one-hour trial?

**Comment by Saltzshaker** [comment]
@baileyspace fyi, kcrw is starting to promote this heavily (sign ups end beginning of august) so we want to make sure this gets done this week

**Comment by Saltzshaker** [comment]
@annewootton you said in slack that you think we should make it a 5hr plan, given our new community situation?

**Comment by Saltzshaker** [comment]
We are sticking with the one-hour plan, and releasing new community plan after August 9th Radio Race

**Comment by baileyspace** [comment]
@Saltzshaker do we have copy for this?

**Comment by Saltzshaker** [comment]
Can be pretty minimal. How's this:

"Welcome, participants of KCRW's 24-hour Radio Race 2015! Sign up here for a free hour of premium transcription to be used during the month of August, courtesy of Pop Up Archive."

**Comment by Saltzshaker** [comment]
and then just the regular sign up page, if that's how we were going to do it

**Comment by baileyspace** [comment]
Does this need to work for both new and existing users?

**Comment by Saltzshaker** [comment]
Oh yeah, I suppose so. In that case, add a note that says:
"Already have a free Pop Up Archive account? Enter your login information here to redeem the free hour of premium transcription.

On a paid Pop Up plan? Contact us at <a href="edison@popuparchive.com?Subject=Radio%20Race" target="_top">edison@popuparchive.com</a> and we'll credit you for a free hour."

**Comment by baileyspace** [comment]
for testing:
/radiorace  
Should be able to sign up new user to plan and switch existing user to plan

**Comment by tarakieffer** [comment]
Not signed in.

![screen shot 2015-07-23 at 8 22 29 am](https://cloud.githubusercontent.com/assets/9256525/8851672/a49f29e6-3116-11e5-8594-9e88c7e7bc91.png)


Signed in user - not signed up for Radio Race trial
![screen shot 2015-07-23 at 8 24 02 am](https://cloud.githubusercontent.com/assets/9256525/8851695/bc7ff784-3116-11e5-9d5c-b3b23681b738.png)

Signed in user - currently in Radio Race trial
![screen shot 2015-07-23 at 8 22 08 am](https://cloud.githubusercontent.com/assets/9256525/8851678/aa0cd72a-3116-11e5-8d08-187c69a8b2ea.png)
