### ISSUE TITLE
Cannot add file to existing Item with zero files

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1157]
Now that there is not an ability to add an audio file to an existing item, is there a reason to still allow the deleting of the audio file from the item?  Or should a user be able to add an audio file if there is not one already associated with the item?

**Comment by baileyspace** [comment]
Good point. We should remove both of those features going forward. However, let's keep the ability to delete files for items that already have multiples.

**Comment by pkarman** [comment]
@tarakieffer can you confirm whether this is still an issue? IIRC the edit form now allows exactly one file on an existing Item.

**Comment by tarakieffer** [comment]
A user is still able to remove the one audio file that is associated with an item.  Perhaps this is a desired feature.  If so, then it would seem once a file is removed, a user should be able to add a file.

**Comment by pkarman** [comment]
agreed. is that not the case now? can a user not add a file to an Item with zero files?

**Comment by tarakieffer** [comment]
Correct. 
![screen shot 2015-07-29 at 12 13 59 pm](https://cloud.githubusercontent.com/assets/9256525/8964496/898446d0-35eb-11e5-8d85-dc3d2f32cf43.png)

**Comment by tarakieffer** [comment]
I am able to select a file to upload and to use a url for an item that does not have an audio file.  @pkarman I am not able to drag and drop. 

![screen shot 2015-08-21 at 12 15 04 pm](https://cloud.githubusercontent.com/assets/9256525/9414536/daa813b4-47fe-11e5-872f-d5663a98f21b.png)

**Comment by tarakieffer** [comment]
Editing an item without audio file.  
1)There are two displays for adding audio files.   
2) Selecting file to upload, does not update 'Current' files, but when I save it uploads the file
3) Drag and Drop does not add the file to the item.

![screen shot 2015-08-21 at 2 01 30 pm](https://cloud.githubusercontent.com/assets/9256525/9416771/4d40e046-480d-11e5-81ae-7395508ead78.png)

**Comment by pkarman** [comment]
I have reverted the last change.

Drag and Drop only works for new items, not existing items. That seems to be the Way It Is.

**Comment by annewootton** [comment]
Got it. If Drag and Drop doesn't work for existing items, is there a way to
remove it from the UI so users don't *think* they can do it, then get
confused when it doesn't work?

**Comment by pkarman** [comment]
it has been removed.

**Comment by annewootton** [comment]
Most excellent.

**Comment by tarakieffer** [comment]
with the removal of drag/drop, I think this is good to go.

![screen shot 2015-08-21 at 2 38 01 pm](https://cloud.githubusercontent.com/assets/9256525/9417474/4a690a6a-4812-11e5-9160-7c381b433d7d.png)
