### ISSUE TITLE
Account for grandfathered plans when creating transcribe tasks

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1164]

**Comment by pkarman** [comment]
I'll need some more specifics about what defines a "grandfathered plan".

Right now any SubscriptionPlan where has_premium_transcripts? returns true gets premium, otherwise gets basic. The new Premium Community plan gets premium.

**Comment by baileyspace** [comment]
That's good. I wanted to make sure people on paid basic plans (Mechabasic, 25_Monthly, 5_professional_mo) continue to get basic transcripts.

**Comment by pkarman** [comment]
I have not altered the AudioFile.transcribe_audio() method, only eliminated the 2 minute preview transcripts per @baileyspace . I think this ticket is a test-only ticket.

**Comment by tarakieffer** [comment]
@baileyspace I do not have any test users on one of these plans.  Will you update tarakieffer612+popup6@gmail.com to have one these?  Thanks.

**Comment by baileyspace** [comment]
Ok, @tarakieffer ready to go

**Comment by tarakieffer** [comment]
@baileyspace Either the plan switch didn't take or there is an issue because the file I just uploaded created a premium transcript.
![screen shot 2015-08-21 at 9 06 31 am](https://cloud.githubusercontent.com/assets/9256525/9410103/f9f6c4d8-47e3-11e5-9e96-fc80590203bd.png)

**Comment by pkarman** [comment]
That user is assigned to plan 1_small_business_mo in the stage database. Anything with **business** or **premium** or **enterprise** in the plan id will automatically get premium transcripts.

There are 3 customer records for that user in Stripe. Is it possible @baileyspace switched the wrong one? Should be **cus_5WMpHCeVJJZDQW** which does not look like it was changed yesterday. Instead **cus_5YCz6nCRTyuk09** was changed.

**Comment by baileyspace** [comment]
That's likely, I changed the first  "tarakieffer612+popup6@gmail.com" account to 25_Yearly, assuming the rest were phantom accounts. I've now changed the others as well, @tarakieffer you can try again.

**Comment by tarakieffer** [comment]
That worked. I got a basic transcript.  However, the message in the middle indicates I have ordered a premium transcript.  

![screen shot 2015-08-21 at 12 26 12 pm](https://cloud.githubusercontent.com/assets/9256525/9415882/e486cc8c-4807-11e5-912a-d86624cec95e.png)

**Comment by pkarman** [comment]
I think we should just zap the word 'Premium' from the messaging. To the user, it doesn't matter what flavor they are getting since there is no longer an option to re-process as premium.

**Comment by baileyspace** [comment]
​Seconded. @pkarman do you want to do that as part of this ticket, or shall
I create a new one for removing "premium" mentions?​

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-08-21 11:29 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by pkarman** [comment]
I'll take care of it here.

**Comment by tarakieffer** [comment]
![screen shot 2015-08-21 at 2 56 41 pm](https://cloud.githubusercontent.com/assets/9256525/9417804/f706f4a6-4814-11e5-9c03-0a0f83ce2e4d.png)
