### ISSUE TITLE
Migrate existing users from old community plan to free trial

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1166]

**Comment by tarakieffer** [comment]
@pkarman Is there more than one 'Community' plan in stage? Users I had created and copies of existing production users have changed to 1 Hour Demo, but there are a few others that still have 'Community'.
![screen shot 2015-08-20 at 8 24 24 am](https://cloud.githubusercontent.com/assets/9256525/9384267/f7300a2c-4714-11e5-8320-15c69743d1b0.png)

**Comment by pkarman** [comment]
The 'Premium Community' plan was renamed to '1 Hour Demo'.

I don't think the subscriptions:migrate_community task was ever run in stage. I am running it now.

I'm not sure how the live-vs-test Stripe environment might affect the subscription change, but the few accounts I tested seemed to move ok.

**Comment by tarakieffer** [comment]
These are now updated.
![screen shot 2015-08-20 at 9 08 22 am](https://cloud.githubusercontent.com/assets/9256525/9385266/0e270ec8-471b-11e5-9a60-202b090a0305.png)
