### ISSUE TITLE
500 error for Samuel and Frederick

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1172]
Samuel - https://stage.popuparchive.com/superadmin/users/1464
Frederick - https://stage.popuparchive.com/superadmin/users/1452

![screen shot 2015-07-21 at 7 53 48 am](https://cloud.githubusercontent.com/assets/9256525/8801104/a991efe6-2f7d-11e5-8bb4-9d7e65e672e7.png)

**Comment by baileyspace** [comment]
@tarakieffer At what point in the process did you see the 500 error?

**Comment by pkarman** [comment]
sorry, @tarakieffer and I fixed this yesterday. it was 035ef014e75fa1e9da5850080775ac207e2de56d

**Comment by baileyspace** [comment]
Excellent

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-07-22 12:21 GMT-07:00 Peter Karman <notifications@github.com>:
