### ISSUE TITLE
Able to still upload after trial has ended.

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1174]
Message displays indicating trial has ended and gives opportunity to upgrade.  However, I am not preventing from proceeding and uploading a file.

![screen shot 2015-07-23 at 8 15 11 am](https://cloud.githubusercontent.com/assets/9256525/8851123/05cdcf64-3113-11e5-85e3-d9444a0ca437.png)

**Comment by tarakieffer** [comment]
When clicking 'Upload' file to get form message form looks ok.

![screen shot 2015-07-28 at 8 26 04 am](https://cloud.githubusercontent.com/assets/9256525/8932424/b379f80c-3502-11e5-9724-24375a49d522.png)

Dragging a file to upload, it looks ok.  However, if I click 'Save', I am able to upload the file dragged.

![screen shot 2015-07-28 at 8 26 42 am](https://cloud.githubusercontent.com/assets/9256525/8932444/d3a4d656-3502-11e5-8ce8-3aea78182109.png)

**Comment by baileyspace** [comment]
Put in a fix for drag and drop and tested it out in staging. I'm going to mark this ready to deploy.
