### ISSUE TITLE
Community Plan upgrade

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1176]
-New free trial plan users will receive 1 hour of upload/processing, no expiration date. 
-Users will not be able to upload content in excess of one hour without upgrading.
-Remove pay as you go option.
-Existing community plan users should receive 1 free processing/upload hour in addition to any material uploaded before the migration to the new community plan. 
-If a community user upgrades, the free hour should not count toward their plan limit hours for the month.

**Comment by tarakieffer** [comment]
-New free trial plan users will receive 1 hour of upload/processing, no expiration date. - Confirmed the limit of one hour.  Not able to confirm if this expires or refreshes.
-Users will not be able to upload content in excess of one hour without upgrading. - Confirmed
-Remove pay as you go option. - Confirmed
-Existing community plan users should receive 1 free processing/upload hour in addition to any material uploaded before the migration to the new community plan. - Confirmed
-If a community user upgrades, the free hour should not count toward their plan limit hours for the month.  - limit is not enforced, but looks like it on the account page - #1205
