### ISSUE TITLE
Enable alphabetical sorting of items

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1178]
It's reached the top of the feature request tracker (so to speak). Many people have asked for it so we want to make it happen.

**Comment by pkarman** [comment]
I assume alphabetical by **title** ?

**Comment by annewootton** [comment]
Yes.

**Comment by pkarman** [comment]
should be 2 new options in search results sort dropdown: title A-Z and title Z-A. They should act as expected (note that bad data may cause confusion, if the title starts with a space or other invisible character. that's outside the scope of this ticket.)

**Comment by tarakieffer** [comment]
Alphabetical title sorting is available.  It does sort the capital letters and lowercase separately.  When looking at the data, this looks like it probably doesn't come into play very often.   

![screen shot 2015-08-04 at 8 19 12 am](https://cloud.githubusercontent.com/assets/9256525/9061484/9bebe4b4-3a81-11e5-8fae-2ad8d86a2b1f.png)

**Comment by pkarman** [comment]
that's a bug. I will fix.

**Comment by tarakieffer** [comment]
Sorting not considering case.
![screen shot 2015-08-19 at 8 13 44 am](https://cloud.githubusercontent.com/assets/9256525/9357039/433b168a-464a-11e5-9245-f41f731b9efb.png)
