### ISSUE TITLE
Redirect popuparchive.wordpress.com to blog.popuparchive.com

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1181]

**Comment by pkarman** [comment]
did you mean redirect the other direction? from popuparchive.com/blog => popuparchive.wordpress.com ?

**Comment by Saltzshaker** [comment]
well, i guess there could be multiple ways of doing this:
1. redirect popuparchive.com/blog to popuparchive.wordpress.com
2. buy a wordpress domain so that popuparchive.wordpress.com becomes popuparchive.com/blog (which would meaning buying a wordpress.com domain? https://en.support.wordpress.com/domains/)

@annewootton @baileyspace thoughts/preferences?

**Comment by annewootton** [comment]
I like option #2 depending on how much it costs, since it seems more
professional. Open to counter-arguments.

**Comment by annewootton** [comment]
Need to change CNAME data for popuparchive.com/blog so it loads popuparchive.wordpress.com instead.
