### ISSUE TITLE
Update "Upgrade plan" messaging for community plan users

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1183]

**Comment by baileyspace** [comment]
for testing: remove references to pay as you go transcripts

**Comment by tarakieffer** [comment]
No reference to pay as you go
![screen shot 2015-08-20 at 7 53 32 am](https://cloud.githubusercontent.com/assets/9256525/9383701/9f914104-4710-11e5-91a5-db56d2ad1de6.png)
