### ISSUE TITLE
copy IA assets to S3

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1184]
need to copy over IA assets (transcoded only? -- confirm with @baileyspace) to PUA bucket and alter code to play back from S3. See also #556

**Comment by baileyspace** [comment]
Yes. MP3 only.

**Comment by pkarman** [comment]
this is really a post-deployment task, since we do not care about copying files to/from stage environment.

**Comment by pkarman** [comment]
assigning to @baileyspace for deployment

**Comment by Saltzshaker** [comment]
It appears (at least some) of these tasks have failed for files that have complete Copy tasks, but cancelled analyze, transcribe, and detect_derivitaves tasks. For example:
* https://www.popuparchive.com/superadmin/audio_files/34581
* https://www.popuparchive.com/superadmin/audio_files/34583
* https://www.popuparchive.com/superadmin/audio_files/34592

I am not well-versed in the IA task business, so seems very possible that this is actually an issue with the cancelled detect_derivitaves tasks from 2014. If so, close this ticket and I can create one about the cancelled detect_derivitaves tasks.

**Comment by annewootton** [comment]
Related to #1216?

**Comment by Saltzshaker** [comment]
Addressed in https://github.com/popuparchive/pop-up-archive/issues/1229
