### ISSUE TITLE
Files not completing

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1188]
Stuck in transcribing status, tried recover didn't change:
https://stage.popuparchive.com/superadmin/audio_files/29786

Stuck in processing, tried recover didn't change:
https://stage.popuparchive.com/superadmin/audio_files/29787

**Comment by pkarman** [comment]
the 2nd one (29787) is due to Cloudfront URLs being generated in the DetectDerivatives task, which is a chicken-and-egg problem. The Cloudfront URLs should only be used *after* the .mp3 is copied back to S3, and only for the mp3 file.

**Comment by pkarman** [comment]
the first one (29786) was due to DO_NOT_EMAIL env var not being set in stage.

**Comment by pkarman** [comment]
both problems should be fixed now. probably should re-test the affected use cases to be sure I didn't just introduce a new regression.

**Comment by tarakieffer** [comment]
Able to upload both a private collection file and a public/internet archive file and have them complete.
