### ISSUE TITLE
Warning message displaying indicating a collection is private when it is public

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1189]
I am getting this warning message indicating the collection is private when uploading a file to a public collection stored on the Internet Archive.

![screen shot 2015-08-05 at 7 53 31 am](https://cloud.githubusercontent.com/assets/9256525/9086022/442f35f2-3b47-11e5-9474-73c24ba8ecfa.png)

![screen shot 2015-08-05 at 7 43 24 am](https://cloud.githubusercontent.com/assets/9256525/9086018/3e33878e-3b47-11e5-9892-967388a20ef3.png)

**Comment by pkarman** [comment]
I don't see anything in the code and data, today, that would explain this. @tarakieffer can you reproduce? If so, the steps you took would greatly help.

**Comment by tarakieffer** [comment]
Odd. I am not able to reproduce this, so closing.
