### ISSUE TITLE
Reprocess as premium broken?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1190]
User: "I have tried this several times today. A couple of times it just hung after I loaded my credit card details, and the other times it went back to the credit card detail page and then wouldn’t allow me to ‘reprocess as premium’ because it was supposedly ‘processing as premium’… but this was this morning and the status now allows for the ‘reprocess as premium’ button to be clicked again, and the transcripts haven’t been done yet."

**Comment by baileyspace** [comment]
fix in master
