### ISSUE TITLE
Reprocess as premium gets stuck loading

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1191]
Loading animation gets stuck, even as premium transcript order goes through
![screen shot 2015-08-07 at 1 08 52 pm](https://cloud.githubusercontent.com/assets/8497203/9145044/291004b6-3d06-11e5-825e-7ccae4de1442.png)

![screen shot 2015-08-07 at 1 09 41 pm](https://cloud.githubusercontent.com/assets/8497203/9144998/d6c07772-3d05-11e5-8b46-1bb94869a3dd.png)

**Comment by pkarman** [comment]
@baileyspace did you fix this issue already?

**Comment by baileyspace** [comment]
Yes. I think there might have been two tickets open for this.

**Comment by baileyspace** [comment]
I closed #1190 instead. both are taken care of.
