### ISSUE TITLE
Premium items stuck in "Processing"

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1192]
Items Track0004.wav, Track0003.wav, and Track0002.wav stuck in "Processing" after 24 hours. No Speechmatics tasks ever created, despite premium plan. This is now the second time this has happened for this user. Though last time, clicking "Recover" fixes the problem, why isn't the task being created in the first place?

https://www.popuparchive.com/superadmin/items?q%5Bcollection_id_equals%5D=5223

**Comment by pkarman** [comment]
these appear to be an issue with the nuwav gem balking at reading the .wav files within the transcode tasks. @kookster is looking at the issue.

**Comment by pkarman** [comment]
@kookster says:

```
andrew		so, looks like this is an audio file that is a wav file with mpeg audio inside the data chunk			12:22
andrew		however, while they use the BWF standard to indicate it is contains mpeg data			12:22
andrew		they are not following the standard for providing the additional info required for mpeg audio			12:22
andrew		as detailed here			12:22
andrew		https://tech.ebu.ch/docs/tech/tech3285s1.pdf 			12:22
andrew		specifically, they lack the additional fields extending the fmt chunk with MPEG specific info
```

**Comment by pkarman** [comment]
assigning this to @Saltzshaker for follow up with customer.

**Comment by Saltzshaker** [comment]
"Apologies, then this was completely my fault. I converted the files from video to audio using VLC and must have selected MPEG instead of MP3 for the codec. Will convert again and upload the MP3 versions."
