### ISSUE TITLE
Add org overages to on-demand billing report

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1196]
For example: org 3 went over their limits (via admin-approved overages) in July, but this wasn't reflected in the on-demand billing report.

Note: this will be moot after Community Plan milestone gets deployed, so maybe all we need is to run a query for all orgs that went over their limits so far this year. (Wondering if we missed any besides org 3...)

**Comment by pkarman** [comment]
Organizations are already included on the on-demand billing report.

Note that the ondemand billing report uses the **current** plan to determine whether the entity in question (User or Organization) is "over" for the month.

Organization 3 is currently assigned to a 50-hour premium plan so they will never show up on **any** ondemand billing report. If they changed their plan, then they would need to be looked at individually and billed according to their Monthly Usage for the month(s) in question.

**Comment by annewootton** [comment]
Why would an org on a 50hr plan never show up in any on demand report? The current setup allows org admins to order on demand transcripts in excess of their plan, whatever that plan may be.

**Comment by pkarman** [comment]
Because only non-premium plans are included in the on-demand report:

```
if !mu.entity.plan.has_premium_transcripts?
```

**Comment by annewootton** [comment]
Ah, got it. Would it be possible to run a report of all orgs that have gone over their plan limits in 2015?

**Comment by pkarman** [comment]
email with report sent.

**Comment by pkarman** [comment]
Note you can always view usage history for any Org with the superadmin UI.
