### ISSUE TITLE
Monthly limit calculation incorrect with provider switch

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1199]
User: 1477 - signed up as 1 hour demo

Signed on today with 0/usage and no over limit message even though over 1 hour of audio uploaded 8/3-8/5.  
Upload 11 min audio today - now there is an over limit message and the meter is only registering usage of 11mins
![screen shot 2015-08-18 at 1 06 37 pm](https://cloud.githubusercontent.com/assets/9256525/9339180/39e33b04-45ae-11e5-874d-d167cc3fc52f.png)

https://stage.popuparchive.com/superadmin/monthly_usages/126649

**Comment by pkarman** [comment]
fix in stage now.

**Comment by tarakieffer** [comment]
Account page totals including all premium transcripts in usage.

![screen shot 2015-08-18 at 3 01 36 pm](https://cloud.githubusercontent.com/assets/9256525/9341204/13a59d2c-45ba-11e5-8a7e-bc76ccbedc2e.png)
