### ISSUE TITLE
Account page  and transcript type

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1200]
This looks confusing now to have Premium Transcript total line with Basic transcript lines in the details, but perhaps this does not impact many users to be an issue.

![screen shot 2015-08-18 at 1 50 45 pm](https://cloud.githubusercontent.com/assets/9256525/9339535/38cf8446-45b0-11e5-83cc-ca200d71ca01.png)

**Comment by pkarman** [comment]
this is a UI bug. the API response is correct.

**Comment by pkarman** [comment]
UI fixed.

Note the numbers might be off for the next hour or two, until the new logic for monthly usage of premium transcripts has a chance to run.

**Comment by tarakieffer** [comment]
There we go.

![screen shot 2015-08-19 at 7 53 57 am](https://cloud.githubusercontent.com/assets/9256525/9356590/7ee540c8-4647-11e5-8055-4f4f126162f9.png)
