### ISSUE TITLE
basic audio transcripts not on s3

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1202]
https://www.popuparchive.com/superadmin/audio_files/49202

cc: @Saltzshaker

**Comment by Saltzshaker** [comment]
I see I'm the owner. I believe I originally uploaded To The Point for KCRW with csv import. Is there something weird about my plan that might be causing this?

**Comment by pkarman** [comment]
I don't think the problem is with your plan; there's something amiss wrt fixer and/or storage. Just opened the ticket to keep track of it, since I noticed while looking at something else.

**Comment by pkarman** [comment]
also https://www.popuparchive.com/superadmin/audio_files/49207

**Comment by pkarman** [comment]
the tasks eventually cancelled themselves, and clicking Recover on the audio files produced success.
