### ISSUE TITLE
1 Hour Demo usage looks like it counts on the account page after upgrad

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1205]
1) on the 1 hour demo plan - upload 1 hour of audio
2) upgraded to the 1 hour plan
3) Limit is no longer enforced (able to upload more audio), but the meter on the account page looks like this is not the case.

![screen shot 2015-08-19 at 8 15 48 am](https://cloud.githubusercontent.com/assets/9256525/9386124/b5ca12f2-471f-11e5-933f-1fa0c355e4c2.png)

**Comment by pkarman** [comment]
I guess it depends on whether we want the initial hour to be "invisible" vs not counted.

In the Charges branch #1203 all mentions of "cost" disappear so there would be no ambiguity there.

I can make the initial hour "invisible" (not show under Total Hours or Usage bar) if that is what is wanted (cc @annewootton @baileyspace). It should still show up when clicking the Details button for the month under History.

**Comment by annewootton** [comment]
Makes sense to me that the "not counted" hour also be invisible in total usage once a user upgrades. That's where people are inclined to look and fret. I think we should make it invisible, especially if the user can still see it under the month's history.

**Comment by pkarman** [comment]
community transcript usage is now subtracted in the display of total hours on the /account page when the current plan is not the community plan.

**Comment by pkarman** [comment]
Note that all the language about cost and overages on the /account page will disappear once the Charges branch is merged, so you can ignore the number discrepancies for those categories.

**Comment by tarakieffer** [comment]
@pkarman It looks while on the community plan, demo usage is getting subtracted.

![screen shot 2015-08-21 at 8 44 39 am](https://cloud.githubusercontent.com/assets/9256525/9409564/0dcdf39e-47e1-11e5-9df0-e19b2e7b1b86.png)

After the upgrade, the usage meter looks ok.
![screen shot 2015-08-21 at 8 48 37 am](https://cloud.githubusercontent.com/assets/9256525/9409642/8d7a4f52-47e1-11e5-8cf5-d880e4657831.png)

**Comment by pkarman** [comment]
related to the visible plan name change. fixing...

**Comment by tarakieffer** [comment]
Community plan is now counting the time while on Community.
![screen shot 2015-08-21 at 11 12 41 am](https://cloud.githubusercontent.com/assets/9256525/9413128/9bfac69c-47f5-11e5-8ac2-f21ac6c6a742.png)
