### ISSUE TITLE
change accounts page to show invoice history

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1208]
the linda-rc branch has some changes to the /account page that were referenced on pua-internal tickets.

Notably:

* History refactored to remove Cost and instead show Invoice records pulled from Stripe
* No more Total Cost in summary section (at the top)
* No more overages

https://github.com/popuparchive/pua-internal/issues/47
https://github.com/popuparchive/pua-internal/issues/48

**Comment by tarakieffer** [comment]
@pkarman @Saltzshaker when should a charge display?   

Here are the invoices in Stripe for tarakieffer612+popup2@gmail.com 
![screen shot 2015-08-21 at 9 01 49 am](https://cloud.githubusercontent.com/assets/9256525/9409985/521466da-47e3-11e5-9fcb-2080694bbb7a.png)

Here is what I am seeing for usage details.  "Charges pending" for August and no cost for previous months.
![screen shot 2015-08-21 at 9 03 13 am](https://cloud.githubusercontent.com/assets/9256525/9410026/8cee748a-47e3-11e5-8d02-675b55226d82.png)

**Comment by pkarman** [comment]
Need to run User.populate_charges for any users we want to test. See notes on #1203

**Comment by tarakieffer** [comment]
All invoices are displaying in the month they are created.

Example of a user who switched plans a few times:
![screen shot 2015-08-21 at 10 55 57 am](https://cloud.githubusercontent.com/assets/9256525/9413055/1d60746c-47f5-11e5-978c-5fd289d3887b.png)

Example of user just sticking to one plan.
![screen shot 2015-08-21 at 9 26 10 am](https://cloud.githubusercontent.com/assets/9256525/9413040/043985aa-47f5-11e5-87f1-5f0c77a1e772.png)

**Comment by annewootton** [comment]
We're good with the $0.00 invoices displaying for now since they represent the exact moment the plan change happened, and the actual charge goes through manually any number of days after that. Can't hurt to reflect both pieces of info for now in account UI.

Marking ready-to-deployl
