### ISSUE TITLE
Calculate upload totals using duration from analyze_audio task instead of transcribe task

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1209]
This will more quickly stop users from uploading over their limit, since analyze_audio takes less time to complete than transcribe.

Change “Total Hours” under popuparchive.com/account “This Month Usage” UI to “Estimated Total Hours” and ensure that it is also calculated based on totals from analyze_audio task.

**Comment by AndersEverett** [comment]
It looks like duration is being set by each task along the way where possible, and then it's being overwritten by later tasks (probably with more accuracy). I've added a method to audiofile that will block processing on any file who's user is over their tallied limit (not based on transcripts). This ticket still needs to have the estimated usage rendering handled on the account page. b3f5b17

**Comment by Saltzshaker** [comment]
Note: also think about adding usage to upload modal so that users will have a better idea of how much space they have left while uploading. This might prevent some users from uploading over their limits.

**Comment by baileyspace** [comment]
Do an initial check of the file metadata to see if we can get duration there:
Using: https://github.com/moumar/ruby-mp3info
You can do something like: `info=Mp3Info.open(file_url)` and then check `info.length`

**Comment by AndersEverett** [comment]
b3f5b178d5aa2 and b3f5b178d5aa24 add block after upload if cumulative `duration` for current month is over limit. As discussed, interface flow for this may be further developed with an additional warning, modal, or deletion of file. 9eb24e3 adds a message to the upload modal with monthly usage.

**Comment by AndersEverett** [comment]
revised duration checker on audiofile processing: 7f6036c

**Comment by Saltzshaker** [comment]
@AndersEverett what is the best way for me to test this?

**Comment by Saltzshaker** [comment]
Uploaded a 32 min file, 36 min file, and 3 min file one after another in both staging and production. 
* In production, as we've seen in the past, all three processed. Over-limit messaging appears after ~10 min. 
* In staging, the 32 min and 36 min files were processed, and the 3 min file stopped at uploading. Yeah!!

@AndersEverett before we deploy, there some messaging kinks to look into:
1) After uploading all three files, the 36 min file initially got the "Illegal file" status, even though it was actually the 3 min file that was stopped at uploading. The 36 min file eventually transcribed.
![screen shot 2016-02-01 at 3 11 33 pm](https://cloud.githubusercontent.com/assets/8497203/12734938/a0780f98-c8f8-11e5-9e4e-dd4b04e5b4f1.png)

2) After a few minutes, they all show up with the Illegal File status on the collections page. 
![screen shot 2016-02-01 at 3 12 53 pm](https://cloud.githubusercontent.com/assets/8497203/12734946/acfbeff0-c8f8-11e5-9201-410624251a8d.png)

3) Before the 32 min & 36 min file processed, their item pages showed mismatched messaging, while the 3 min file showed accurate messaging.
![screen shot 2016-02-01 at 3 12 31 pm](https://cloud.githubusercontent.com/assets/8497203/12734950/bd01ed82-c8f8-11e5-83ab-873304e09842.png)
![screen shot 2016-02-01 at 3 15 34 pm](https://cloud.githubusercontent.com/assets/8497203/12734959/cadf917a-c8f8-11e5-8fc1-3cc0cc9c3581.png)

4) (Minor) There's a lag of a few minutes between when the Illegal File status shows up and the red over-limit banner shows up for the user. I don't think this is a big deal, but I'm wondering if it makes sense to update when we show the over-limit banner according to this new method.

**Comment by AndersEverett** [comment]
3ce20f1 Changes status setting to specifically set only files that push the user over limit.
@Saltzshaker This is in staging.

**Comment by AndersEverett** [comment]
412764e Added a check to skip illegal status for any files with tasks. @Saltzshaker ==> in staging!

**Comment by Saltzshaker** [comment]
@AndersEverett tested this. The over-limit file stopped after upload and has accurate "over-limit" messaging on the item and collections pages. The other files processed normally. Ready to go.
