### ISSUE TITLE
Include plan changes in Usage History

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1214]
For "$0.00" invoices, print "Plan change from XX to XX" (it's in the Stripe data) instead of "Invoice." Do not show "$0.00" amount.

Add tool-tip to "History": "1hr Demo plans changed mid-month will be charged a pro-rated amount based on usage during the month. Paid plans changed mid-month will be charged the difference between plans."

**Comment by pkarman** [comment]
it's far easier to just ignore all zero amount invoice records that try and discern which ones to show and which ones not to. that parsing is all but impossible.
