### ISSUE TITLE
Files stuck in Processing w/o transcript tasks

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1215]
All files uploaded after 2015-08-22 01:30:46 UTC are stuck in "Processing" without transcription tasks: https://www.popuparchive.com/superadmin/audio_files

For example: https://www.popuparchive.com/superadmin/audio_files/49401

**Comment by pkarman** [comment]
Emily Saltz wrote on 8/22/15, 2:33 PM:
> All files uploaded after 2015-08-22 01:30:46 UTC are stuck in "Processing"
> without transcription tasks: https://www.popuparchive.com/superadmin/audio_files
>
> For example: https://www.popuparchive.com/superadmin/audio_files/49401
>


fixer has 3000+ jobs queued since last night (all the copy from IA tasks I would 
guess) so until that clears nothing will go through.

I would suggest spinning up a few more fixer worker instances.


-- 
Peter Karman . @peterkarman
Search your sound . http://popuparchive.com/ . @PopUpArchive

**Comment by baileyspace** [comment]
Will do

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-08-22 12:52 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by baileyspace** [comment]
@pkarman Trying to launch
​"​
more like
​"​
fixer-work-000 and getting "This AMI has been deregistered, or you do not
have permission to use it.
Try again with another AMI for which you have permissions, or request
permission to use this AMI from its owner." Do you need to grant me
​any ​
permission
​s​
?

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-08-22 12:57 GMT-07:00 Bailey Smith <bailey.r.smith@gmail.com>:

**Comment by pkarman** [comment]
Bailey Smith wrote on 8/22/15, 3:13 PM:
> @pkarman Trying to launch
> ​"​
> more like
> ​"​
> fixer-work-000 and getting "This AMI has been deregistered, or you do not
> have permission to use it.
> Try again with another AMI for which you have permissions, or request
> permission to use this AMI from its owner." Do you need to grant me
> ​any ​
> permission
> ​s​


I created an AMI on July 20. You can create a new t2.small instance from that 
image (fixer-work) and then you can do "Launch more like this" from that new 
instance.


-- 
Peter Karman . @peterkarman
Search your sound . http://popuparchive.com/ . @PopUpArchive
