### ISSUE TITLE
Change non-signed-in drag-and-drop message to "Sign in to upload"

### ISSUE THREAD

**Issue by shindostrz** [popuparchive/pop-up-archive#1222]

**Comment by tarakieffer** [comment]
"Please log in to upload" displays when not signed in user attempts to drag and drop.

There is a bit of behavior that may not be expected.  Drag and Drop on the pricing page displays "Please log in to upload" unless the previous attempt was on the item page.  Then it displays "You may not add more than one file per item"

Steps for a non-signed in user to inconsistent drag and drop message:
1) attempt to drag and drop on an item page - receive message "You may not add more than one file per item"
2) navigate to pricing page.
3) attempt to drag and drop on pricing page - receive message "You may not add more than one file per item"
4) navigate to about page
5) attempt to drag and drop on about page - receive message "Please log in to upload"
6) navigate to pricing page
7) attempt to drag and drop on pricing page - receive message "Please log in to upload"

**Comment by shindostrz** [comment]
@tarakieffer That inconsistency should be fixed in staging now

**Comment by tarakieffer** [comment]
"Please log in to upload" is displaying always for a not signed in user.
