### ISSUE TITLE
Files get stuck on detect_derivatives, transcribing, processing, and working

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1223]
For some items, detect_derivatives and s3 tasks get stuck in "working" until running "finish_tasks." The response url seems to be there, but isn't getting the callback. 

No current examples, since "finish tasks" was run on all of them. Had happened with this item: https://www.popuparchive.com/superadmin/items/42966

**Comment by annewootton** [comment]
We think the same thing is happening with transcribe tasks. 

See: https://www.popuparchive.com/superadmin/audio_files/45215

**Comment by baileyspace** [comment]
Initial observations:

Incomplete tasks
    960
Working tasks
    244
Stuck tasks
    242
Unstuck tasks
    2
With job callback*
    73

*All for transcribe tasks.


Additional task errors:
1) Analysis does not include length for AnalyzeAudioTask (e.g., 434380)
2) Undefined method each_with_index for nil class for TranscribeTask (e.g., 434304)
