### ISSUE TITLE
Tplayer sometimes not working on Tumblr

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1224]
Audio works on Pop Up Archive, but broken in tplayer:
![screen shot 2015-08-31 at 2 07 03 pm](https://cloud.githubusercontent.com/assets/8497203/9590937/bdd854e2-4fec-11e5-8342-130753892e82.png)
http://popuparchive.tumblr.com/post/127814463404/popcast-a-love-poem-to-a-2000-year-old-stranger

The previous Popcast has a working tplayer on the Tumblr: http://popuparchive.tumblr.com/post/126534254624/15-rooms-15-visions-of-womanhood

Both were embedded with iframe.

**Comment by annewootton** [comment]
See also: https://freemusicarchive.org/member/cheyenne_h/blog/Radio_Free_Culture_50_Trapped_in_the_Black_Box_of_Sound_with_Emily_Saltz_from_the_Pop-Up_Archive

**Comment by annewootton** [comment]
Aaaalso, to add mischief to misery, the "Fiesta A Chicago Happening" audio isn't player here: http://studsterkel.org/categories/chicago. Not sure if that's our fault or archive.org, but ostensibly we should have copied it over from archive.org already.

**Comment by baileyspace** [comment]
Deployed fix. Error introduced 8/14. @Saltzshaker for existing players with this problem remove  `%20%7D%7D`. e.g., https://www.popuparchive.com/tplayer/49485%20%7D%7D becomes https://www.popuparchive.com/tplayer/49485

**Comment by baileyspace** [comment]
@annewootton the other two examples have different problems. Fiesta is a 404 and Radio free culture is a 403

**Comment by annewootton** [comment]
Commented about the Fiesta 404 on a separate ticket (https://github.com/popuparchive/pop-up-archive/issues/1216). 

@baileyspace still need to troubleshoot Radio Free Culture — audio is playing from the Pop Up Archive site: https://www.popuparchive.com/collections/4787/items/38360

**Comment by annewootton** [comment]
Seeing the "Flash update required" message here:
http://www.cbc.ca/radio/spark/292-what-you-say-will-be-searched-why-recognition-systems-don-t-recognize-accents-and-more-1.3211777/here-s-why-your-phone-can-t-understand-your-accent-1.3222569

![screen shot 2015-09-13 at 7 41 09 pm](https://cloud.githubusercontent.com/assets/1718286/9841039/7d2a77c8-5a4f-11e5-8ca9-aa1e379e3a3c.png)
