### ISSUE TITLE
Why are there cancelled detect_derivitaves tasks?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1229]
There are lots of files (many at WILL) that have complete Copy tasks, but cancelled analyze, transcribe, and detect_derivitaves tasks. For example:

https://www.popuparchive.com/superadmin/audio_files/34581
https://www.popuparchive.com/superadmin/audio_files/34583
https://www.popuparchive.com/superadmin/audio_files/34592

**Comment by baileyspace** [comment]
See if resolved with #1216

**Comment by AndersEverett** [comment]
2/3 of the above examples have completed DetectDerivativesTasks. I think it was mentioned that the nudger keeps trying these? Also, I ran a a script on all of the failed DD's, and 95% of these actually have both 'mp3' and 'ogg' urls but are missing a 'detected_at' field.

**Comment by AndersEverett** [comment]
Check failed DD tasks & see if their files are playing from s3 and have a transcript. Get number of files and possibly add date.

**Comment by baileyspace** [comment]
Check that audio_file has a detect derivatives task AND that it does not have a detect derivatives task that is complete.

**Comment by AndersEverett** [comment]
https://docs.google.com/spreadsheets/d/1Y7xl86JXhRBeVmXcn-ASUmtvZdynDvp3y5zBZNAG3So/edit#gid=1437708643&vpid=A1

**Comment by annewootton** [comment]
Cool. Can we remove all the items that are playing + have transcripts? Seems like we don't care if their DD tasks are canceled, unless @baileyspace or @Saltzshaker disagrees.

**Comment by AndersEverett** [comment]
Ok, done. I did leave the rows that aren't playing from IA or S3 but that play and have ts.

**Comment by annewootton** [comment]
Great. The rows that aren't playing from IA or S3 but play and have
transcript should also/already be covered by your doc of files that didn't
copy, correct?
ᐧ

**Comment by AndersEverett** [comment]
Yes, I think that's 'playing from elsewhere' spreadsheet.

**Comment by annewootton** [comment]
@AndersEverett to do: 

For files not playing, add them to list from #1311. Open new ticket (Mencken) for emailing users to whom those files belong and alerting them that the items will be deleted.

For files playing but not transcribed, open new ticket (Mencken) for re-transcribing those items and link to list of those files from ticket. I will look them over before we go ahead and re-transcribe.

**Comment by annewootton** [comment]
And then this ticket can be closed!

**Comment by AndersEverett** [comment]
Files that don't play combined in : https://docs.google.com/spreadsheets/d/1mofzWZEkg9eayyjEvTerWkL5_-oxGsTkF-rJAXTuXrI/edit?ts=565c8d6f#gid=1232807286&vpid=A1
New issue in Mencken for files that don't play/email contact for deletion : #1327

Files that play but don't have transcripts (from this ticket's results): 
https://docs.google.com/spreadsheets/d/16s-7DStrG3gnwydrh-uDs7_Rfe3JhzryKz-FUIjkDfY/edit#gid=1876073338&vpid=A1
New issue in Mencken for dealing with missing ts files : #1328
