### ISSUE TITLE
Mobile - not able to see full transcript

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1230]
This is true in production as well as stage - so not a regression.  The whole transcript line does not display and I am not able to swipe right to see the whole line.

![screen shot 2015-09-04 at 9 50 24 am](https://cloud.githubusercontent.com/assets/9256525/9686625/78732c28-52ea-11e5-97cf-5a8a14939b49.png)

**Comment by tarakieffer** [comment]
I am still not able to see full transcript lines in portrait view.

![screen shot 2015-09-29 at 7 35 21 am](https://cloud.githubusercontent.com/assets/9256525/10164060/d1a7063e-667c-11e5-98f3-4af977a54a3b.png)

**Comment by shindostrz** [comment]
@tarakieffer I just pushed a fix to staging

**Comment by tarakieffer** [comment]
Line wraps are allowing me to see the whole transcript line.

![portraittranscript20150930](https://cloud.githubusercontent.com/assets/9256525/10199581/fc792302-6766-11e5-8950-5cf72db8ee3e.jpg)
