### ISSUE TITLE
Don't show drag-and-drop mask where drag-and-drop is disabled (Item page, edit modal)

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1233]
You can't drag and drop files onto item pages or onto the edit item modal. This is true even when there are 0 files in an item. Despite this, the drag and drop screen still shows up when you try to drag a file onto these pages. When you try to drop a file, the mask closes and nothing happens. 

Disable the drag and drop screen from showing up where it's not actually possible to drag and drop audio.

**Comment by tarakieffer** [comment]
"You may not add more than one file per item" displays when drag and drop is attempted on the item page.   
-For both signed in user and not signed.
-For with files and without

**Comment by annewootton** [comment]
We discussed internally: we need to change the alert to "You may not drag
and drop files on an item page." That message is accurate for all
variations of users listed by @tarakieffer.

**Comment by tarakieffer** [comment]
Message is "You may not drop files on Item pages"  It is displaying for signed in user for items with and without files.

Signed out user is getting the message "Please log in to upload"
