### ISSUE TITLE
Create tasks for items with no tasks (recent IA items)

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1234]
These files from 7/28–7/31 have 0 tasks. They are all stored at Internet Archive. There is nothing on item pages. 
* 	https://www.popuparchive.com/superadmin/audio_files/48262	KCRW: Which Way L.A.	7/28/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48298	KQED The California Report	7/28/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48313	KALW Crosscurrents	7/28/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48314	KALW Crosscurrents	7/28/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48315	KALW Crosscurrents	7/28/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48316	KALW Crosscurrents	7/28/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48341	KCRW: Which Way L.A.	7/29/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48349	KALW Crosscurrents	7/29/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48350	KALW Crosscurrents	7/29/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48351	KALW Crosscurrents	7/29/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48390	WILL News	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48391	WILL News	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48392	WILL News	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48395	KCRW: Which Way L.A.	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48419	KQED The California Report	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48420	KQED The California Report	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48423	KALW Crosscurrents	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48424	KALW Crosscurrents	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48425	KALW Crosscurrents	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48426	KALW Crosscurrents	7/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48446	WILL News	7/31/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48447	WILL News	7/31/2015
* 	https://www.popuparchive.com/superadmin/audio_files/48453	KCRW: Which Way L.A.	7/31/2015
* 	https://www.popuparchive.com/superadmin/audio_files/42007	Radio Diaries (owned by me)	7/31/2015
* 	https://www.popuparchive.com/superadmin/audio_files/42571	Radio Diaries (owned by me)	7/31/2015
* 	https://www.popuparchive.com/superadmin/audio_files/42968	Radio Diaries (owned by me)	7/31/2015

**Comment by baileyspace** [comment]
Must have been an outage. I'm seeing "detect_derivatives audio_file xxx not yet saved to archive.org". Rerunning.

**Comment by baileyspace** [comment]
@Saltzshaker reran these. Spot check to test.

**Comment by Saltzshaker** [comment]
Only the first link above is complete. The rest have "Cancelled" statuses, and only have AnalyzeAudio, DetectDerivatives, and Copy Tasks tasks (all complete), except for the last three Radio Diaries links which still have 0 tasks.

**Comment by baileyspace** [comment]
Reran the following, ready to spot check:

https://www.popuparchive.com/collections/800/items/41639
https://www.popuparchive.com/collections/5212/items/41646
https://www.popuparchive.com/collections/5212/items/41647
https://www.popuparchive.com/collections/5212/items/41648
https://www.popuparchive.com/collections/5212/items/41648
https://www.popuparchive.com/collections/2064/items/41649
https://www.popuparchive.com/collections/2064/items/41650
https://www.popuparchive.com/collections/2064/items/41651
https://www.popuparchive.com/collections/2064/items/41652
https://www.popuparchive.com/collections/2347/items/41677
https://www.popuparchive.com/collections/2064/items/41685
https://www.popuparchive.com/collections/2064/items/41686
https://www.popuparchive.com/collections/2064/items/41687
https://www.popuparchive.com/collections/5220/items/41723
https://www.popuparchive.com/collections/1468/items/41726
https://www.popuparchive.com/collections/1468/items/41727
https://www.popuparchive.com/collections/1468/items/41728
https://www.popuparchive.com/collections/2347/items/41731
https://www.popuparchive.com/collections/5169/items/41738
https://www.popuparchive.com/collections/5169/items/41740
https://www.popuparchive.com/collections/800/items/41755
https://www.popuparchive.com/collections/800/items/41756
https://www.popuparchive.com/collections/2064/items/41759
https://www.popuparchive.com/collections/2064/items/41760
https://www.popuparchive.com/collections/2064/items/41761
https://www.popuparchive.com/collections/2064/items/41762

**Comment by Saltzshaker** [comment]
All complete except for the following items which don't exist in superadmin and throw a privacy error in UI:
https://www.popuparchive.com/collections/5220/items/41723 
https://www.popuparchive.com/collections/5169/items/41740
https://www.popuparchive.com/collections/5169/items/41738

Also, KALW Crosscurrents and WILL News have Premium transcripts

**Comment by annewootton** [comment]
Can you tell if the Crosscurrents and WILL News items are counting toward
those orgs' limits this month?

**Comment by Saltzshaker** [comment]
WILL News: yes. https://www.popuparchive.com/superadmin/organizations/7
Crosscurrents and KALW as a whole are still throwing an application error in superadmin for some reason

**Comment by Saltzshaker** [comment]
Is this the same issue? See "n/a" files: https://www.popuparchive.com/superadmin/collections/800

**Comment by AndersEverett** [comment]
I spot-checked N/A files for last mentioned link, and they all seem to be titled items with 0 audio files connected.

**Comment by annewootton** [comment]
Hm, so perhaps separate issue. @Saltzshaker, do you want to create a ticket for copying over items in collection 800 from their current digital locations?

**Comment by annewootton** [comment]
Also there is this: https://github.com/popuparchive/pop-up-archive/issues/913.

Collection 800 used to be "copy media false," though I can't say that would be a reason why no tasks were fired for the files @Saltzshaker mentioned.

**Comment by Saltzshaker** [comment]
Closing this ticket. Other issues will be addressed with https://github.com/popuparchive/pop-up-archive/issues/1323
