### ISSUE TITLE
Create transcripts for items that play but have no transcript or analyze tasks

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1237]
Complete copy, detect_derivatives, and s3 tasks, but no transcript or Analyze/Analyze_Audio tasks. Includes both IA and non-IA items, uploaded and copied:
* 	https://www.popuparchive.com/superadmin/audio_files/35496	WILL	12/22/2014
* 	https://www.popuparchive.com/superadmin/audio_files/37199	User	1/16/2015
* 	https://www.popuparchive.com/superadmin/audio_files/38372	California Report	1/29/2015
* 	https://www.popuparchive.com/superadmin/audio_files/38417	WILL	1/30/2015
* 	https://www.popuparchive.com/superadmin/audio_files/38517	California Report	1/31/2015
* 	https://www.popuparchive.com/superadmin/audio_files/38518	California Report	1/31/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39291	California Report	2/2/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39368	WILL	2/3/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39369	WILL	2/3/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39370	WILL	2/3/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39371	WILL	2/3/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39466	WILL	2/4/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39467	WILL	2/4/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39468	WILL	2/4/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39469	WILL	2/4/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39500	The California Report	2/4/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39537	TRUNEWS	2/4/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39602	The California Report	2/5/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39633	WILL News	2/6/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39634	WILL News	2/6/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39664	The California Report	2/6/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39665	The California Report	2/6/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39730	The California Report	2/7/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39682	WILL News	2/7/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39851	TRUNEWS	2/9/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39865	WILL News	2/10/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39896	The California Report	2/10/2015
* 	https://www.popuparchive.com/superadmin/audio_files/40038	TRUNEWS	2/11/2015
* 	https://www.popuparchive.com/superadmin/audio_files/40118	WILL	2/12/2015
* 	https://www.popuparchive.com/superadmin/audio_files/41110	User	2/24/2015
* 	https://www.popuparchive.com/superadmin/audio_files/41111	User	2/24/2015
* 	https://www.popuparchive.com/superadmin/audio_files/43989	Forum	4/23/2015
* 	https://www.popuparchive.com/superadmin/audio_files/43979	User	4/23/2015

**Comment by AndersEverett** [comment]
CSV updated with manual checks for transcripts on highlighted items from rake task generated report.
https://docs.google.com/spreadsheets/d/1s683czh0eKhSOHSDPSlEjbC2_xTzX-LY2MmOMCPhvfE/edit?ts=5637c58c#gid=257959290

**Comment by Saltzshaker** [comment]
1. refire rows highlighted green that play w/o transcript: basic, is_billable=false, don't email
2. make sure that items with transcripts also play

**Comment by AndersEverett** [comment]
Rake task monitor:create_missing_transcripts was run on items agreed upon from spreadsheet: 
https://docs.google.com/spreadsheets/d/1s683czh0eKhSOHSDPSlEjbC2_xTzX-LY2MmOMCPhvfE/edit#gid=2022323924&vpid=A104

Second tab, 3rd column has all audio files transcribed by task today.

**Comment by annewootton** [comment]
Great, and the other files are covered by #1311, correct? If so, looks like this ticket is good to close.

**Comment by Saltzshaker** [comment]
@annewootton Yep! Was going to wait for the other rake task to hit that satisfying "Close Milestone button" to knock 'em out all at once, but the "Close and comment" button is right there, so...
