### ISSUE TITLE
Investigate files that are still playing from IA

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1238]
Everything in PUA should play from s3. Find files that are playing from IA. Make a head request to see if IA files are actually playing from s3. 

*      https://www.popuparchive.com/superadmin/audio_files/39582
* 	https://www.popuparchive.com/superadmin/audio_files/34570	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34581	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34583	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34592	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34595	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34610	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34620	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34628	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34648	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34649	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34668	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34678	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34731	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34733	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34742	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34743	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34776	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34777	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34791	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34792	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34802	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34803	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34804	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34807	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34831	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34852	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34858	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34866	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34870	WILL	12/4/2014
* 	https://www.popuparchive.com/superadmin/audio_files/34887	WILL	12/4/2014

**Comment by baileyspace** [comment]
Make a head request to see if IA files are where they are supposed to be

**Comment by Saltzshaker** [comment]
We discovered that some files did actually copy to S3, but don't play because they are playing at the IA.

**Comment by Saltzshaker** [comment]
@AndersEverett created a list of files still playing from IA: https://docs.google.com/a/popuparchive.org/spreadsheets/d/1wcms3Uv3-OuXb0A72PpBt9CP64sauNChjsfCOLEqGU8/edit?usp=sharing The ones not copied over to s3 will be copied with https://github.com/popuparchive/pop-up-archive/issues/1296. 

@AndersEverett: Is there anything in place to change the play location?

**Comment by Saltzshaker** [comment]
1. For files that copied to S3 and are still playing from IA, repoint storage from IA to S3. 

Because we don't want to run this in staging, marking as ready to deploy to production.
