### ISSUE TITLE
Why do these files have complete s3 tasks, but failed detect_derivatives?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1241]
Upload or Copy and CopyToS3 are complete, but Detect_Derivatives is cancelled. Files play. 
Examples:
* 	https://www.popuparchive.com/superadmin/audio_files/39830	KALW's Crosscurrents	2/9/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39866	WILL News	2/10/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39867	WILL News	2/10/2015
* 	https://www.popuparchive.com/superadmin/audio_files/39868	WILL News	2/10/2015
* 	https://www.popuparchive.com/superadmin/audio_files/42572	The California Report	3/20/2015
* 	https://www.popuparchive.com/superadmin/audio_files/42766	WILL News	3/27/2015
* 	https://www.popuparchive.com/superadmin/audio_files/42974	KALW's Crosscurrents	4/2/2015
* 	https://www.popuparchive.com/superadmin/audio_files/44183	KCRW: Which Way L.A.	4/29/2015
* 	https://www.popuparchive.com/superadmin/audio_files/44396	KCRW: Which Way L.A.	5/5/2015
* 	https://www.popuparchive.com/superadmin/audio_files/44651	The California Report	5/13/2015
* 	https://www.popuparchive.com/superadmin/audio_files/44653	KALW's Crosscurrents	5/13/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46594	KALW Crosscurrents	6/17/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46666	KQED The California Report	6/18/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46751	WILL News	6/22/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46867	KQED The California Report	6/25/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46868	KALW Crosscurrents	6/26/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46878	WILL News	6/26/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46879	WILL News	6/26/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46884	KCRW: Which Way L.A.	6/26/2015
* 	https://www.popuparchive.com/superadmin/audio_files/46900	KALW Crosscurrents	6/26/2015
* 	https://www.popuparchive.com/superadmin/audio_files/47066	WILL News	7/1/2015
* 	https://www.popuparchive.com/superadmin/audio_files/47258	WILL News	7/8/2015
* 	https://www.popuparchive.com/superadmin/audio_files/47399	USER	7/8/2015

**Comment by AndersEverett** [comment]
Above links are included in : https://docs.google.com/spreadsheets/d/1Y7xl86JXhRBeVmXcn-ASUmtvZdynDvp3y5zBZNAG3So/edit#gid=1437708643&vpid=A1

**Comment by annewootton** [comment]
Awesome. Given that all of these links are included in your doc, and we are addressing whether or not those items have transcripts, I think it's safe to close this ticket.

It seems from our other ticket (#1229) that is is not necessary to refire DD tasks as long as the files get transcribed, unless we find that competed DD tasks are a prerequisite for transcription to occur. Either way, this ticket will be addressed by #1229.
