### ISSUE TITLE
Add loading animation to email form for adding org members

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1245]
* It is slow to add users via the email form, and there's no indication that it's loading. 
* Also Change error message:
from "Error: There was a problem sending the invite" to "Something went wrong. Emails must correspond to users with existing Pop Up accounts."

**Comment by tarakieffer** [comment]
![screen shot 2015-10-16 at 9 32 46 am](https://cloud.githubusercontent.com/assets/9256525/10544410/e9f8f8ae-73e8-11e5-9498-5b682839a631.png)
