### ISSUE TITLE
Add ability for org admins to remove members from team

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1246]
Requested by multiple users

**Comment by tarakieffer** [comment]
Able to add and remove users from the organization as the admin and the owner.  Members not able to remove other members.

![screen shot 2015-10-16 at 9 17 02 am](https://cloud.githubusercontent.com/assets/9256525/10544336/67fbf04a-73e8-11e5-9b21-399ac2cf2bc7.png)
