### ISSUE TITLE
Pop Up Archive sometimes not working on mobile

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1250]
Reported by user. I get a "404 not found" message at popuparchive.com/ from my iPhone4. Page still has header and footer, with error message being rendered in Soleil font, so it's possible that this is not the real error. Also experienced by Anne sporadically.

**Comment by annewootton** [comment]
I haven't gotten the 404 error though, I got something else (can't remember
what it was — will comment here if I can recreate).

**Comment by shindostrz** [comment]
Pushed this directly to prod because it seems to be working
