### ISSUE TITLE
About page styles broken

### ISSUE THREAD

**Issue by shindostrz** [popuparchive/pop-up-archive#1259]
I thought this was fixed with the new CSS partial, so look into that problem

**Comment by tarakieffer** [comment]
Couple of screenshots from 360x640 resolution.  Looks better.

![screen shot 2015-10-09 at 06 26 59](https://cloud.githubusercontent.com/assets/9256525/10392708/3743d862-6e4f-11e5-8102-13294dc287b6.png)

![screen shot 2015-10-09 at 06 30 03](https://cloud.githubusercontent.com/assets/9256525/10392714/436fdd02-6e4f-11e5-9d90-d097ceec8a74.png)
