### ISSUE TITLE
Why isn't CIR notified when going over their limit?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1263]
CIR has uploaded 30+ hours on a 20 hour plan. Neither admins nor org members are getting the over-limit messaging. They are still able to upload. https://www.popuparchive.com/superadmin/organizations/46

**Comment by baileyspace** [comment]
Added an env_var to allow sending usage reports

**Comment by baileyspace** [comment]
for testing: regression testing and users who are members of an organization whose account is over the monthly limit should see the red "You are over your monthly limit. Upgrade now!" messaging. @tarakieffer when you get to this bit let us know and we'll add you to the appropriate organization for testing

**Comment by tarakieffer** [comment]
![screen shot 2015-10-16 at 9 14 59 am](https://cloud.githubusercontent.com/assets/9256525/10543973/837d9df2-73e6-11e5-8d38-bf464c97bd1a.png)

**Comment by Saltzshaker** [comment]
WILL isn't getting over-limit messaging in UI. They've uploaded 31h on a 25h plan. https://www.popuparchive.com/superadmin/organizations/7

**Comment by annewootton** [comment]
Possibly related to https://github.com/popuparchive/pop-up-archive/issues/1274

**Comment by tarakieffer** [comment]
All uploads seem to be counting towards the limit.  I did not do any testing with feeds.
