### ISSUE TITLE
Search result alignment

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1265]
![image](https://cloud.githubusercontent.com/assets/833332/10173291/431e3272-6698-11e5-8bf2-0b85eb2e038e.png)

**Comment by tarakieffer** [comment]
![screen shot 2015-10-12 at 4 12 11 am](https://cloud.githubusercontent.com/assets/9256525/10424755/780a4cf6-7097-11e5-8f6e-95e2a6d5084e.png)
