### ISSUE TITLE
Entering multiple search terms creates search for "and" 

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1275]
![screen shot 2015-10-02 at 5 57 41 pm](https://cloud.githubusercontent.com/assets/8497203/10260668/461be2dc-692f-11e5-86f2-ba03c7c10c60.png)

**Comment by Saltzshaker** [comment]
Aha, looks like this only happens when you search with a comma, i.e. "red ribbon, aids" 
Looks like the comma triggers an "and" search, which it should not.

**Comment by Saltzshaker** [comment]
Also just noticed it happens even without a comma: https://www.popuparchive.com/search?page=1&query=channukah,hannukah

**Comment by AndersEverett** [comment]
Search is correct, highlighting is not. I haven't been able to pinpoint where 'and' is getting set as a search filter match.

**Comment by AndersEverett** [comment]
Fixed with 58acd0d.

**Comment by Saltzshaker** [comment]
Test with words with commas, search terms entered to top followed by a search to the main search bar, and then two search terms to the main search bar. None have "and" highlighted! Ready to deploy.

Search for "dog" and "day" with fix:
![screen shot 2016-03-01 at 5 14 32 pm](https://cloud.githubusercontent.com/assets/8497203/13447533/2b33b5a8-dfd1-11e5-90ce-6ef1a68c7ae6.png)
Search for "dog" and "day" before fix:
![screen shot 2016-03-01 at 5 14 20 pm](https://cloud.githubusercontent.com/assets/8497203/13447535/2f5f2338-dfd1-11e5-86ca-ab788be097d5.png)
