### ISSUE TITLE
Transcript callback error

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1279]
The job callback text is in there, but it has an error that there's no Voicebase id: https://www.popuparchive.com/superadmin/tasks/447093 

Unlike previous files where SM transcripts fail to get back to PUA, task.finish_task doesn't complete the callback. Ditto for https://www.popuparchive.com/superadmin/tasks/447083

Both files are for a user who initially had basic transcripts, so this might be an edge case.

**Comment by AndersEverett** [comment]
Both links above lead to error messages. Both tasks in database have owner audio files that have been deleted or don't exist. There are, however, completed tasks for files of the same name but different ids.

Betty_Marvin_All_Audio_for_Transcription.mp3  ==>
https://www.popuparchive.com/superadmin/tasks/447980

Queen_Thurston_140308_0097.mp3  ==>
https://www.popuparchive.com/superadmin/tasks/447970

Specific error mentioned in description occurs in code in task.recover! method, so it might not be indicative of a specific situation.

**Comment by annewootton** [comment]
I believe the completed tasks for files of same name, different ids is because the originals were deleted and the files were re-uploaded, at which point they transcribed and called back successfully.

If the error occurs in task.recover!, what (if anything) does that tell us?

**Comment by AndersEverett** [comment]
task.recover! attempts to nudge a stuck task. In the case of "No Voicebase job_id found," the recovery process tried to find the job_id in the task's extras attribute and couldn't find it so rendered the error. There's no evidence as to why the job_id is missing other than that maybe the audiofile was deleted early. I'm not sure how/if the job_id depends on the physical presence of the file. The task itself still exists in the database along with its callback.

**Comment by annewootton** [comment]
Hmm. We can leave this open to double-check with @Saltzshaker but it appears that these were initially audio files with basic transcripts, and when she tried to create premium transcripts, the job callback text was there, but for some reason no job_id was created. Is that possible — to have callback text but no job id?

**Comment by AndersEverett** [comment]
job_id should be grabbed in the voicebase callback, and it is there in the database for task 447093 : "vb_job_id_via_callback"=>"120aaac0-e95f-4909-a761-4cc50a47139e", 
so it's unclear why it doesn't get pulled into extras.

**Comment by AndersEverett** [comment]
This task does actually have a job_id, but it's another version of the job id called the 'vb_job_id_via_callback' which gets assigned later with the same variable from the payload that the job_id is based. From commented-out notes in the callback controller: "# worst case. create the job_id now but give it a different key so we can tell it was after-the-fact." It looks like this happens when the job id (or mediaID in VB language) is not available upon task creation, but is grabbed from the callback instead.

**Comment by AndersEverett** [comment]
@Saltzshaker Hey, do you happen to have any more info on this issue? When I undelete these items and move them into my collection, they have visible transcripts. Would it be best to change the error messaging for situations like these? Or is there a different goal here?

**Comment by Saltzshaker** [comment]
I think this was a rare enough case that we can close this — agreed @annewootton? And just to understand why this happened, @AndersEverett is it your impression that the reason the transcripts weren't showing up in PUA before because of the vb_job_id_via_callback situation?

**Comment by annewootton** [comment]
@saltzshaker do you know what caused the transcript to show up in PUA after
it initially didn't? You mentioned that the finish_task method didn't work
for these items, but  when @anderseverett un-deleted the item and moved it
into a separate collection, he was able to see the transcript in PUA.
ᐧ

**Comment by AndersEverett** [comment]
@Saltzshaker It's hard to say. Maybe there was a delay? Something kept the id from being set at the beginning of the task/ forced it to be set on callback, so maybe there was a delay/issue on VB side.

**Comment by Saltzshaker** [comment]
@annewootton No, I don't know why the items would show up when moved to another collection. Do you @AndersEverett?

**Comment by annewootton** [comment]
It appears that the callback eventually came through, regardless of
collection — maybe it just took longer than usual because it didn't have
the VB job id out of the gate like a "normal" file.
ᐧ

**Comment by Saltzshaker** [comment]
@annewootton It's possible. Closing as a wontfix, unless you have any outstanding questions or goals from this ticket
