### ISSUE TITLE
As owner not able to upgrade plan.

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1280]
As https://stage.popuparchive.com/superadmin/users/1479, I am not able to upgrade the plan for 'Reply all' org.   
![screen shot 2015-10-16 at 9 42 03 am](https://cloud.githubusercontent.com/assets/9256525/10544641/38ced27c-73ea-11e5-87ce-53c498e63d4d.png)

**Comment by baileyspace** [comment]
@tarakieffer to clarify, can admins upgrade the plan?

**Comment by tarakieffer** [comment]
@baileyspace I don't seem to be able to update as the admin or the owner.

**Comment by AndersEverett** [comment]
@tarakieffer I was getting this 500 Internal Server too on Friday but am now getting 431 Request Header Fields Too Large error. Can you confirm if you're seeing this now too? Along with the pop-up alert?

**Comment by AndersEverett** [comment]
@tarakieffer So, when I clear my cache and then attempt to upgrade both myself as individual user and also an org(as owner), I am able to upgrade without issue. Let me know what you're seeing once you create a new user. Thanks!

**Comment by tarakieffer** [comment]
@AndersEverett It appears with the new organization that @baileyspace set up for me. This is not an issue.  So it most likely was an issue with the previous user not existing in Stripe.  I am closing this ticket.
