### ISSUE TITLE
KCRW and CBC orgs not working

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1283]
When viewing as users of KCRW or CBC orgs, no data displays. I've tried as both the owner and as a member. The console gives a 403 error. 
![screen shot 2015-10-18 at 7 43 48 pm](https://cloud.githubusercontent.com/assets/8497203/10568701/b605a472-75d0-11e5-9766-5d4a1fbf7ae4.png)
KCRW is on a Mechaplan and CBC is 50 hours. I also tried viewing as CIR (30 hours) and everything looked normal

**Comment by annewootton** [comment]
Were too big to run the ActiveQuery we were running, so limited backlog of results to one year and switched query to be SQL.
