### ISSUE TITLE
File with two complete ts_paid tasks

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1285]
* Figure out why there are two complete ts_paid tasks
* Prevent user from being billed twice
https://www.popuparchive.com/superadmin/tasks?q%5Bowner_id_equals%5D=51663&q%5Bowner_type_equals%5D=AudioFile

**Comment by Saltzshaker** [comment]
@baileyspace Also note that one of these transcripts is marked as is_billable=false, but the usage hasn't updated accordingly. Figure out why/how to be able to adjust what's counted as billable.

**Comment by baileyspace** [comment]
Put in extra test to see if job is already running. For testing: regression only.

**Comment by tarakieffer** [comment]
No regressions observed, so I am marking this as ready-to-deploy
