### ISSUE TITLE
Make sure all items have titles

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1286]
Usually if user does not provide a title we default to filename as title.

This is apparently not happening for feed items. See https://www.popuparchive.com/api/collections/3247/items/45063 — no item title, but there is a filename.

**Comment by baileyspace** [comment]
I think this is happening in the RSS feed importer.

**Comment by AndersEverett** [comment]
Added an alternate to take filename for item title if no title available. 6751f3785ce27bc7ff5

**Comment by Saltzshaker** [comment]
Tried to recreate with original example above, but all feed items now had original titles. Can't recreate this, short of creating a custom rss feed without titles. @annewootton @baileyspace do you have any other ideas? I'm inclined to call it in as "can't replicate" and move forward with deploying Joan.

**Comment by Saltzshaker** [comment]
closing as untestable
