### ISSUE TITLE
Why were duplicate items being created?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1287]
We haven't replicated this, but when a user clicked to upload her files uploaded twice. Note that duplicates have since been deleted: https://www.popuparchive.com/superadmin/collections/5883
![duplicateupload](https://cloud.githubusercontent.com/assets/8497203/10680924/22766226-78d9-11e5-8551-db10f524c710.png)

**Comment by annewootton** [comment]
User was trying to upload audio file as audio and as image.
