### ISSUE TITLE
Prevent users from being able to upload zip files

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1288]
Because lol, this happened. May have slipped through because .mp3 was still in the title? See @shindostrz's similar fix for uploading non-audio files (can't find ticket)

**Comment by annewootton** [comment]
hahaha sorry you had to deal with that @saltzshaker

**Comment by Saltzshaker** [comment]
Tested .zip or .mp3.zip or .wav.zip files. All return an error message. 
![screen shot 2015-11-19 at 4 19 23 pm](https://cloud.githubusercontent.com/assets/8497203/11288524/aceb7624-8ed9-11e5-97d8-47af24e3246f.png)
![screen shot 2015-11-19 at 4 19 02 pm](https://cloud.githubusercontent.com/assets/8497203/11288525/acecfd32-8ed9-11e5-8da2-eeef7145cbde.png)
