### ISSUE TITLE
is_billable=false not working

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1289]
One of these transcripts is marked as is_billable=false, but the usage hasn't updated accordingly. Figure out how to be able to adjust what's counted as billable.

https://www.popuparchive.com/superadmin/tasks?q%5Bowner_id_equals%5D=51663&q%5Bowner_type_equals%5D=AudioFile

**Comment by Saltzshaker** [comment]
@baileyspace test whether this works by marking the deleted duplicate files in this collection —https://www.popuparchive.com/superadmin/collections/5883 — as is_billable=false and see if it changes the user's limits.

**Comment by baileyspace** [comment]
@Saltzshaker to test, try changing a file to is_billable=false in staging and monitor whether the monthly_usage time updates in admin

**Comment by Saltzshaker** [comment]
Tested on this transcript: https://stage.popuparchive.com/superadmin/transcripts/68603. Superadmin properly updated, subtracting the file's duration from the user's usage. (Note: I changed it back to is_billable=true)

**Comment by Saltzshaker** [comment]
this is a comment to test slack integration
