### ISSUE TITLE
Remove popuparchive.com/jobs & audiosear.ch/jobs listing

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1291]
Change text to "No openings available at this time. We're always accepting resumes at edison@popuparchive.com." 

Ditto for Audiosear.ch, but change email to "info@audiosear.ch"

**Comment by Saltzshaker** [comment]
Job description removed on AS & PUA, replaced by generic message.
![screen shot 2015-11-19 at 4 08 57 pm](https://cloud.githubusercontent.com/assets/8497203/11288317/ee08d16c-8ed7-11e5-891f-9109915f113c.png)
![screen shot 2015-11-19 at 4 08 46 pm](https://cloud.githubusercontent.com/assets/8497203/11288318/ee1bd60e-8ed7-11e5-84fa-f55d8c4e6768.png)
