### ISSUE TITLE
Create reprocess transcript method

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1293]
to retranscribe a file if there was something amiss with the original transcript. Add "reprocess transcript" button in superadmin

**Comment by AndersEverett** [comment]
This will be possible with the rake task underway in #1237 .

**Comment by AndersEverett** [comment]
Added a button to superadmin with an AudioFile method for reprocessing transcriptions.

**Comment by Saltzshaker** [comment]
![screen shot 2015-11-19 at 4 01 59 pm](https://cloud.githubusercontent.com/assets/8497203/11288225/e609a3de-8ed6-11e5-99b5-036dcabe0032.png)
Transcribe button shows up for items without complete transcripts. Change it so the button to shows up and refires a transcript even if there is a complete basic or premium transcript.

**Comment by AndersEverett** [comment]
167b6cb Transcribe button visible on all files in superadmin.

**Comment by Saltzshaker** [comment]
Button appears even for transcribed buttons. Clicking it creates a VB task. Marking ready to deploy!
