### ISSUE TITLE
Create a list of files that did not copy over to s3 and copy over

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1296]
Everything in PUA should have copied over to s3, unless it has copy_media=false.

**Comment by AndersEverett** [comment]
It doesn't seem that the 'token' identifier is going to be a consistent method for determining a successful copy to S3.

**Comment by Saltzshaker** [comment]
connected to https://github.com/popuparchive/pop-up-archive/issues/1238

**Comment by AndersEverett** [comment]
https://docs.google.com/spreadsheets/d/1FRn-kVs-4lB_KP4k1dCaxlKKXob-y6igDDs1vk17avQ/edit#gid=1736101354

List of files playing from neither IA or s3.

**Comment by AndersEverett** [comment]
https://docs.google.com/spreadsheets/d/1wcms3Uv3-OuXb0A72PpBt9CP64sauNChjsfCOLEqGU8/edit#gid=1887431542

List of files playing from IA that need to be copied or pointed to S3.

**Comment by Saltzshaker** [comment]
Thanks for these @AndersEverett! For the list of files playing from IA that need to be copied or pointed to S3, is the rake task in place to copy them over?

**Comment by Saltzshaker** [comment]
2. If not copied and playing from IA, refire s3 tasks. Spot-check afterwards to make sure storage is truly pointed to S3. 

Because we don't want to run this in staging, marking as ready to deploy to production.

**Comment by Saltzshaker** [comment]
@AndersEverett says: "as expected, those playing from somewhere other than s3 or ia [1.] were not impacted by rake task. i will run head checks on those and see what last url is.

[2.] of the 3971 that were previously playing from the IA, 2334 have been solved (s3 now). That leaves 1637 still from IA.  I’m going to have to investigate this set more. There’s nothing obvious about them as to why they wouldn’t have been copied. I’ll look at their tasks and see if they’ve failed."

I'm going to close this and make a new ticket for the remaining 1637 files that were copied but aren't playing from IA. 

As for the files playing from somewhere other than s3 or ia, @AndersEverett will comment with his findings and we can decide if there's anything to be done, or if we should just delete them.

**Comment by annewootton** [comment]
Sounds good. To clarify, the 1637 still to be investigated *are* still playing from IA and did not successfully copy, per @anders comment, correct?

**Comment by Saltzshaker** [comment]
That's my understanding: https://github.com/popuparchive/pop-up-archive/issues/1326
