### ISSUE TITLE
Add friendly upgrade message to demo plan item pages

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1300]

**Comment by Saltzshaker** [comment]
Add message below transcripts on over-limit item pages. "Like this transcript? Upgrade to a paid plan for more!" In conjunction with over-limit email created with ticket https://github.com/popuparchive/pop-up-archive/issues/1309

**Comment by AndersEverett** [comment]
Adding an upgrade prompt alert in 1611d87 .

**Comment by Saltzshaker** [comment]
![screen shot 2016-01-13 at 12 13 50 pm](https://cloud.githubusercontent.com/assets/8497203/12306549/37af89e0-b9ef-11e5-9466-4ebd975f5d88.png)
Upgrade prompt is only supposed to appear to demo plan users on their own premium items. 
Prompt currently appears on **all premium items** for any user, whether signed into a demo plan, 5-hr plan, and even for users who aren't signed in. Reassigning to @AndersEverett. 

Also, would be good to include a link to the pricing page (https://www.popuparchive.com/pricing) where it says "Upgrade your plan for more!"

**Comment by AndersEverett** [comment]
visibility fixed with a84e67ba461c620164

**Comment by AndersEverett** [comment]
linked to pricing 5d3fa8d

**Comment by Saltzshaker** [comment]
Links to pricing, and message no longer appears on items not owned by the user. 

However, message should only appear for demo users. Right now it's appearing for users on the five-hour plan as well, e.g. https://pop-up-archive-staging.herokuapp.com/collections/5823/items/44535

Re-assigning to @AndersEverett 
![screen shot 2016-01-20 at 12 22 01 pm](https://cloud.githubusercontent.com/assets/8497203/12461952/7c720d06-bf70-11e5-96bc-ad97607bee7b.png)

**Comment by AndersEverett** [comment]
Added extra check for premium account : dd4168c

**Comment by Saltzshaker** [comment]
@AndersEverett do you mean a check for the demo account? Will this prevent users on paying plans (e.g. the five-hour plan i tested above) from seeing the upgrade message?

**Comment by AndersEverett** [comment]
Updated the code with be1d86b. Should work now so only demo plan with completed premium transcripts will see the alert. In staging

**Comment by Saltzshaker** [comment]
:+1: ready to deploy!
