### ISSUE TITLE
Add PUA url to superadmin pages

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1302]
e.g., `Item.find(xxx).url`

**Comment by baileyspace** [comment]
Added PUA URL to collection, item, audio_file, transcript, and task pages

**Comment by Saltzshaker** [comment]
Confirmed on collection, item, audio_file, transcript, and task pages
![screen shot 2015-11-19 at 3 06 40 pm](https://cloud.githubusercontent.com/assets/8497203/11287271/2c328540-8ecf-11e5-9bad-ebae9905368e.png)
