### ISSUE TITLE
Monthly "time" and "duration" are sometimes 1 day off

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1303]
**Superadmin**
For example, In superadmin org overview, KUOW shows 32 hours (1d: 8h: 40m: 36s) under "Time" column for October, but when you click on the month for details, it lists 08:40:36 as monthly "Duration." (Double-checked, and summing durations of files does come to 08:40:36.)

https://www.popuparchive.com/superadmin/organizations/33 vs.
https://www.popuparchive.com/superadmin/monthly_usages/109633

Most months these numbers match, but February is also off by 1 day: 27 hours (1d: 3h: 39m: 53s) vs. 3h: 39m: 53s 

**UI account page**
Monthly history for KUOW displays 32 hours for October. Question: what did they see during October under "This Month" usage? (These numbers are calculated with different methods)

**Comment by Saltzshaker** [comment]
KUOW February usage matches for superadmin org overview and monthly usage. 

@baileyspace, does this also change how "This Month" usage is calculated in the UI? Can we expect it to match the numbers calculated for monthly history?

**Comment by baileyspace** [comment]
I think "this month" was correct, and if this is now correct, it should match the figure in "this month"

**Comment by Saltzshaker** [comment]
In the UI, the monthly history was correct, but we never caught what showed up in the current month — it's possible it shows up correctly, and possible that it doesn't. We'll keep an eye on it. Marking ready to deploy for now.
