### ISSUE TITLE
Create "no-transcript" setting for PUA collections

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1307]
Can look to Audiosear.ch as an example.

Once this is done, re-add the following feed to collection 2064 with "no transcript" set: http://kalw.org/feeds/628/rss.xml

**Comment by AndersEverett** [comment]
d19f601 I added an 'extra' attribute to collections, so they can be flagged upon creation for no transcript processing. Collection should be updated once deployed.

**Comment by Saltzshaker** [comment]
Waiting for Joan to be deployed to production. Once migration is run, default extra field needs to be set as empty hash for all existing collections. Set Collection 2064 as "no transcript."

**Comment by annewootton** [comment]
Don't forget to re-add the feed (http://kalw.org/feeds/628/rss.xml) to the Heroku scheduler for collection 2064! We turned ingest off while this ticket was being worked on.
