### ISSUE TITLE
Create a list of items that don't play, with and without transcripts

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1311]
Hard to reliably identify these items.

* To see whether items play, run head request, but this returns items that are down even for a moment. Discussed: try running head request a few different times and create list of items that never play. 

*To see whether items have transcripts, .transcript and .length attributes aren't always reliable. @AndersEverett can work with @baileyspace to find a more reliable method.

Once we've identified the items that don't play, see if any are salvageable by changing location, or whether we want to delete them.

**Comment by AndersEverett** [comment]
Here's the list of items that don't play (triple checked with head requests) along with transcript statuses.

https://docs.google.com/spreadsheets/d/1mofzWZEkg9eayyjEvTerWkL5_-oxGsTkF-rJAXTuXrI/edit#gid=1405373018&vpid=A1

**Comment by annewootton** [comment]
Plan for these is to treat them the same way we treated failed uploads: email users to warn them that we are deleting files that do not play back, then delete these items a week later.

@AndersEverett if you could add user emails to the spreadsheet, I'll take it from there.

**Comment by annewootton** [comment]
Updated https://docs.google.com/spreadsheets/d/1mofzWZEkg9eayyjEvTerWkL5_-oxGsTkF-rJAXTuXrI/edit?ts=565c8d6f#gid=1232807286&vpid=A1 — rows highlighted in green SHOULD NOT be deleted.

**Comment by AndersEverett** [comment]
Emails added to spreadsheet.

**Comment by annewootton** [comment]
@AndersEverett to do:

Open new ticket in Mencken with these files and non-playing files from #1229. Then we will email users to alert them that those items will be deleted.

**Comment by annewootton** [comment]
And then this ticket can be closed too!
