### ISSUE TITLE
Disambiguate between "premium transcripts" & "premium (usage only)" in Superadmin

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1312]
Determine how exactly they're different, if they're both necessary, and consider getting rid of one/making it clearer. Example: https://www.popuparchive.com/superadmin/users/1593

![screen shot 2015-11-20 at 10 27 18 am](https://cloud.githubusercontent.com/assets/8497203/11308206/b8ecae14-8f71-11e5-8019-90c9d258e6d7.png)

**Comment by AndersEverett** [comment]
Judging by comments in code, "(usage only)" versus "transcripts" charges seems to have been intended to differentiate between User usage and entity usage. It doesn't in practice seem to be doing this as transcripts_billable_for_month_of and transcripts_usage_for_month_of are identical methods. I've left both in the code but changed the admin dashboard to only render the transcripts charges. 1a658ba6a2

**Comment by Saltzshaker** [comment]
No longer showing premium (usage only). Marking ready to deploy. 
![screen shot 2015-12-11 at 12 27 53 pm](https://cloud.githubusercontent.com/assets/8497203/11754820/c05052e0-a002-11e5-9829-4e386cd64cbf.png)
