### ISSUE TITLE
Change messaging for "Status: Cancelled"

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1314]
![screen shot 2015-11-23 at 10 04 45 am](https://cloud.githubusercontent.com/assets/8497203/11345148/2a820632-91ca-11e5-87e4-b1f261e252b6.png)
Change descriptive text to something like "Something went wrong. Contact us at edison@popuparchive.com for support."

**Comment by AndersEverett** [comment]
b34737a adds new message for cancelled status.

**Comment by Saltzshaker** [comment]
Files with a cancelled status now appearing with appropriate messaging:
![screen shot 2015-12-11 at 12 16 05 pm](https://cloud.githubusercontent.com/assets/8497203/11754567/ff390328-a000-11e5-827b-de56cfdcdecd.png)
