### ISSUE TITLE
Why do we get "VB Job Failed" errors?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1315]
Examples:
https://www.popuparchive.com/superadmin/tasks/460304
https://www.popuparchive.com/superadmin/tasks/460300
https://www.popuparchive.com/superadmin/tasks/460296

@baileyspace is asking Brian

**Comment by baileyspace** [comment]
There are some fixes coming soon. Nothing more for us to do.
