### ISSUE TITLE
Research Stripe discount codes

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1317]
Figure out how to offer 20% discount to plans and generate promo codes in Stripe. Followed up by https://github.com/popuparchive/pop-up-archive/issues/1319

**Comment by Saltzshaker** [comment]
We want two referral codes:
1) #DemoDiscount: The code that any user on the demo plan can get for sending 3 email invites out. Applied when changing plans. Stripe applies 20% discount to user for next month's plan. Duration: one month. Max redemptions: one. Redeem_by: no expiration.

2) #PayingFriendX: This is the promo code that is sent in email invites. If someone signs up for a !demo plan using this code, Stripe applies 20% discount to user for next month's plan. The referrer will also get 20% off next month's plan. Duration: one month. Max redemptions: None? @annewootton Should we limit this? If a user can keep generating paying customers with invites, I feel like we should keep incentivizing them to do so with continued discounts. Redeem_by: no expiration.

It looks like 1) can be set up pretty easily with Stripe – https://stripe.com/docs/guides/subscriptions#applying-discounts, but the two-sided discount for 2) will require getting set up with a Stripe integration program like SaaSSquatch — guide here: http://docs.referralsaasquatch.com/guides/percent-discount/

**Comment by Saltzshaker** [comment]
Continued with https://github.com/popuparchive/pop-up-archive/issues/1317

**Comment by annewootton** [comment]
I'm down to keep giving people 20%, 1 month discounts for every additional promo code followed through on. Question: if there are no max redemptions, can a user redeem more than one 20% discount per month? I'd be inclined to say no, but I'm not sure how Stripe handles this.

**Comment by Saltzshaker** [comment]
Ah, I misunderstood what max redemptions meant. 
Re: applying multiple discounts per month: An invoice can only have one coupon applied–it’s not possible to stack two or more coupons onto an invoice.
Re: max_redemptions: this is the total number of times that this coupon can be applied to customers. For example, you can restrict a coupon to the first 50 customers that use it, or you can make a coupon expire by a certain date.

So no max_redemptions, because it should be available to anyone with the code, and no multiple discounts for the same month.

**Comment by annewootton** [comment]
Great. And can a user get multiple discounts to apply across separate
months?
ᐧ

**Comment by Saltzshaker** [comment]
As I understand it, yes — if you have a friend sign up in Jan you'll get max one coupon applied to your invoice, and if another friend signs up in Feb, ditto. And if you're a demo user who upgrades using a discount, you won't have access to the #demodiscount again anyway. 

Hypothetically, if they were to downgrade later, I think they would be able to redeem the #demodiscount again as long as the code was applied to a different invoice. We can probably set it otherwise.

**Comment by annewootton** [comment]
That all sounds fine. How does the user get the coupon code once their
friend signs up?
ᐧ

**Comment by Saltzshaker** [comment]
@annewootton I think it gets applied automatically to their Stripe invoice with the SaaSquatch integration, but I'm not sure yet — @AndersEverett will get more familiar with the details in https://github.com/popuparchive/pop-up-archive/issues/1317.

**Comment by AndersEverett** [comment]
I'm looking at SaaSquatch now; it looks like it does all the tracking of users and referrals.

**Comment by AndersEverett** [comment]
SaaSquatch appears to be a paid service only, so @Saltzshaker and I are discussing ways of building this out manually. We are looking at creating a join table called "References" to track referrer id's with emails of potential new users. A question that has come up is in the case of two users referring the same potential user: do both referrers get 20% upon successful account creation of the 3rd?
