### ISSUE TITLE
Make sure that old phone number is nowhere on site

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1322]
Customer complained about calling 510-463-4066 and not getting through. We should remove any references to that number on our site, since it's unreliable.

**Comment by AndersEverett** [comment]
f7ea347

**Comment by Saltzshaker** [comment]
Still in Terms: 
![screen shot 2015-12-11 at 12 23 25 pm](https://cloud.githubusercontent.com/assets/8497203/11754735/1f5f8054-a002-11e5-8aaf-d853c3f3cfb9.png)
Deleted it here: https://github.com/popuparchive/pop-up-archive/commit/adf703249e88e0c13c37c793d52341e28ac3e1c9 Once @baileyspace pushes the change to staging I'll check again and mark it ready to deploy
