### ISSUE TITLE
Copy over items in collection 800 from their current digital locations

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1323]
See items with status "n/a": https://www.popuparchive.com/superadmin/collections/800 These items have titles but 0 audio files connected. @AndersEverett says item.identifier links to a web page, not audio file.

Possibly connected to https://github.com/popuparchive/pop-up-archive/issues/913 which shows that collection 800 used to be "copy media false"

**Comment by AndersEverett** [comment]
Check location of URL in XML and structure of rss feed ==> possible changes.

**Comment by AndersEverett** [comment]
62cd69fc7daf0a blocks this from happening again. Empties can be deleted as they are individuals from other aggregated items.

**Comment by AndersEverett** [comment]
Deleted all the empty items from collection 800.
