### ISSUE TITLE
Why did this file get stuck in Processing?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1324]
https://www.popuparchive.com/superadmin/items/37116

CopyTask is complete, but file url is not found https://www.popuparchive.com/media/audio_file/a7bc/123264635

**Comment by AndersEverett** [comment]
Fixer message: File missing or 0 length
Transcode Task Error: Destination URL does not exist
The original_file_url leads to a vimeo page for a private video with no visible public content, and the url is not in audio_file format (no .wav, .mp3, etc); so it seems there was nothing available to process here.

**Comment by Saltzshaker** [comment]
Good enough for me! Closing. 

One question for @AndersEverett: do we have any checks in place to prevent people from entering non-audio urls? If not, there might be another ticket to make.

**Comment by Saltzshaker** [comment]
Looks like there is some check in place, but not for private files. 
![screen shot 2015-12-09 at 6 29 50 pm](https://cloud.githubusercontent.com/assets/8497203/11705351/031a0fa4-9ea4-11e5-8faa-d78419108970.png)
I made this ticket: https://github.com/popuparchive/pop-up-archive/issues/1339
