### ISSUE TITLE
Block new premium transcription attempts when results repeatedly = empty hash.

### ISSUE THREAD

**Issue by AndersEverett** [popuparchive/pop-up-archive#1325]
Example: https://www.popuparchive.com/superadmin/audio_files/53200

This file has  > 50 VoicebaseTranscribeTask attempts.

**Comment by annewootton** [comment]
Related to #1315

**Comment by Saltzshaker** [comment]
@baileyspace says: "i've looked into it and the empty hash actually means that the vb task failed, so i don't think it's even a problem. we'll probably just end up closing it, i just want to look at a few more examples."
