### ISSUE TITLE
Why are these files still playing from IA? Change to AWS.

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1326]
After finishing https://github.com/popuparchive/pop-up-archive/issues/1296, 1637 files didn't successfully copy and are still playing from IA. Figure out why and make sure they play from AWS. Note: @AndersEverett is also still looking into the files that are playing from locations other than s3 or archive.org and didn't copy (as discussed here: https://github.com/popuparchive/pop-up-archive/issues/1296) @AndersEverett: Comment with status of these files so we can decide what to do with them.

**Comment by AndersEverett** [comment]
I just reran the rake task, and now that number (playing from IA) has dropped from 1637 to 774. I'm guessing that there's either a lag, or fixer or Heroku (or some other mystery) is gagging at some point. I can rerun the rake task again this weekend, and my guess is that it will all but eradicate this IA situation.

**Comment by AndersEverett** [comment]
The total number still playing from IA is 122 files after running the task 3 times.

**Comment by annewootton** [comment]
Cool. See what you can find re: why they didn't copy, and/or feel free to include a list of them on this ticket (or email it around) so we can decide where to go from here.

**Comment by AndersEverett** [comment]
Ran it again and there are now none from the original set that are still playing from IA.

**Comment by annewootton** [comment]
Awesome!
