### ISSUE TITLE
Create Transcripts for Items that Play but are Missing Transcripts.

### ISSUE THREAD

**Issue by AndersEverett** [popuparchive/pop-up-archive#1328]
Spreadsheet generated from cancelled detect derivatives issue:
https://docs.google.com/spreadsheets/d/16s-7DStrG3gnwydrh-uDs7_Rfe3JhzryKz-FUIjkDfY/edit#gid=1876073338&vpid=A1

**Comment by annewootton** [comment]
I will assess to determine if we should force basic transcripts for all of these or deal with them otherwise.

**Comment by annewootton** [comment]
There are so few of these, happily! Let's create basic transcripts for these like @AndersEverett did with the last spreadsheet of untranscribed files.

**Comment by AndersEverett** [comment]
Ok, I'll run the through the same rake task that does a force basic.

**Comment by Saltzshaker** [comment]
Rake task just run. Will spot-check and close.

**Comment by Saltzshaker** [comment]
All items I spot-checked in the spreadsheet above now have basic transcripts. Closing!
