### ISSUE TITLE
Send automated email to demo users who didn't finish upgrading

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1329]
If demo users click on upgrade messaging but don't finish upgrading, email them to finish upgrade process

**Comment by Saltzshaker** [comment]
Prereq is https://github.com/popuparchive/pop-up-archive/issues/1333

**Comment by Saltzshaker** [comment]
@baileyspace, while spot-checking some of the users on the email lists for the various conditions listed above, i noticed that 'hours remaining' and 'monthly usage' resets each month.

while this is perfect for paid plans, it unfortunately messes up targeting for demo plan users, where the hour limit is fixed. for example, when i try to target demo users who signed up in the last 30 days & haven't uploaded any audio, the list includes users who uploaded audio in january and haven't uploaded audio in february. 

can we rewrite the 'monthly usage' and 'hours remaining' properties so that they don't reset each month for demo users?

**Comment by Saltzshaker** [comment]
Made https://github.com/popuparchive/pop-up-archive/issues/1363 to allow proper targeting based on demo plan usage. 

In the meantime, I can set up 4: "If demo users click on upgrade messaging but don't finish upgrading, email them to finish upgrade process." 
![screen shot 2016-02-11 at 6 12 25 pm](https://cloud.githubusercontent.com/assets/8497203/12997126/2a09953e-d0eb-11e5-9f4e-60e6a4f20dfc.png) Spot-checked the 3 users who meet these condition right now and they all seem accurate. Will send a test email shortly, and then I can schedule it to send every week to the users that meet the conditions

**Comment by Saltzshaker** [comment]
Split out the emails into different tickets. This one is based on click events and can get done with Sally, but the emails based on usage will require some tweaks to the Mixpanel code in https://github.com/popuparchive/pop-up-archive/issues/1366. 

Usage emails to be launched in https://github.com/popuparchive/pop-up-archive/issues/1366

**Comment by Saltzshaker** [comment]
Scheduled for Thursdays at 12pm

**Comment by annewootton** [comment]
Sweet. Is there a way you could check to make sure this is running properly
by creating a user who fits the proper Mixpanel condition?
ᐧ

**Comment by Saltzshaker** [comment]
mixpanel shows you the users it's going to send the email to, and i spot-checked the list. also, when i was testing the email copy, i targeted it only to myself, and it sent.

**Comment by annewootton** [comment]
Great, if it shows you who it's going to send to, that's good enough for me
(more meaningful I think than when you target it to yourself).
ᐧ
