### ISSUE TITLE
Add speaker IDs back into UI

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1330]
Related to https://github.com/popuparchive/audiosear.ch/issues/940

**Comment by AndersEverett** [comment]
Possible fix in ddaf439. I'm not quite sure how to test this in dev or staging yet, so this will likely need more tweaking.

**Comment by Saltzshaker** [comment]
Speaker numbering is funky and nonsequential, but functional. Will write to Bryon about the numbering, but in the meantime this isn't a dealbreaker for deploying Sal.

500 error when assigning speakers with the select2 box: 
![screen shot 2016-01-20 at 10 39 18 am](https://cloud.githubusercontent.com/assets/8497203/12459320/fda16362-bf62-11e5-8e64-d8d8be5207f3.png)

**Comment by Saltzshaker** [comment]
Speaker assignment works! Marking ready-to-deploy. 
![screen shot 2016-01-20 at 11 50 52 am](https://cloud.githubusercontent.com/assets/8497203/12461139/288be77e-bf6c-11e5-8d08-5c3a3358fdc0.png)
