### ISSUE TITLE
Add one-time processing messaging to pricing + Zendesk

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1331]
Could be as simple as moving up current enterprise audio div to the top, replacing 10% annual plan discount thing which no one uses.

Discussed: have form that asks how many hours, and recommend plan and upgrade/downgrade flow based on this.

**Comment by Saltzshaker** [comment]
Mockup of one-time processing button. Interested to hear feedback — esp. from @baileyspace — on how this new button jives with the enterprise button at the bottom. Should the designs be more different? E.g. different button color and/or icon? 
![onetime-mockup](https://cloud.githubusercontent.com/assets/8497203/11755590/3644ec90-a008-11e5-946a-50db424d8acc.png)

**Comment by Saltzshaker** [comment]
Clicking button one-time processing button launches form:
---
* Required
Name*: 
Email*: 
Enter approximate hours of audio* [integer picker]: 
*[tool-tip] Enter the total duration of the audio that you need processed at this time, rounding up to the hour. If you're not sure how much audio you have, you can contact us with questions at edison@popuparchive.com.
---
For integers between 0 and 25, display message:
0-1: Recommend 1 hour plan
2-5: Recommend 5 hour plan
6-10: Recommend 10 hour plan
11-20: Recommend 20 hour plan 
21-25: Recommend 25 hour plan 
---
Message:
"Because you've selected [y] hours of audio, you qualify for our [x hour plan]. For one-time use, you can just sign up for the [x hour plan] and downgrade to the free plan before the end of the month at no extra charge. At the end of your first month, we charge a prorated amount based on your usage and the plan rate. For example, if you sign up for the 10 hour plan ($15/hr rate) and use 8 hours, you will be charged for $120 at the end of the calendar month. 

Once you've downgraded, you'll keep access to Pop Up transcripts and editing tools for all previously processed audio even from the free plan. You can upgrade again for more room at any time. More questions? Contact us with questions at edison@popuparchive.com. Thanks!"

25+: "Because you've selected [y] hours of audio, you qualify for a custom Pop Up Archive plan. We'll contact you shortly about how to set up a custom plan for this amount of audio. Thanks!"

**Comment by Saltzshaker** [comment]
Simplifying from button to a plain hyperlink at the top that says "Are you a freelancer? Have a special project? Learn how to use Pop Up if you don’t need a recurring plan." This links to a Zendesk FAQ which explains the above.

**Comment by Saltzshaker** [comment]
https://github.com/popuparchive/pop-up-archive/commit/090c7560eb1e4bbbb51875f3a0ee34e5ffa49a15 Added link and edited pricing FAQ

**Comment by Saltzshaker** [comment]
![screen shot 2016-01-13 at 12 08 22 pm](https://cloud.githubusercontent.com/assets/8497203/12306421/7d09a7d8-b9ee-11e5-8ab5-ac54efe99627.png)
Link appears on pricing page and goes to FAQ for one-time use. One question: I apparently left in the 10% discount part on the opposite side. @baileyspace @annewootton is it too busy with them both? Should I change it to replace the 10% discount section as we discussed?

**Comment by annewootton** [comment]
I'm okay with it as-is but defer to @baileyspace on design.

**Comment by baileyspace** [comment]
I'd prefer replacing it.

**Comment by annewootton** [comment]
Or — would there be another, better place for it? I ask only because we
actually had a person sign up for an annual plan in the last month.

**Comment by annewootton** [comment]
I'm fine with replacing the 10% discount line if @baileyspace has no other thoughts on this.

In that case, I would like to vote that the one-time processing messaging be right-justified.

**Comment by Saltzshaker** [comment]
I changed the placement to be right-justified and replacing the 10% discount line: https://github.com/popuparchive/pop-up-archive/commit/b4fa111484abbd91f23008ed98f0c9a5961422f8 
Once it's merged into Sal, I'll mark this ready to deploy
