### ISSUE TITLE
Improve site speed

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1332]
Start by fixing minifying configuration and implementing gzip and research Angular optimization

**Comment by shindostrz** [comment]
Start by fixing minifying configuration and implementing gzip

**Comment by Saltzshaker** [comment]
From WooRank
**Speed Tips**
* Enable compression
* Eliminate render-blocking JavaScript and CSS in above-the-fold content
* Minify JavaScript
* Leverage browser caching
* Too bad, your server is not using a caching method. (?)

**Comment by baileyspace** [comment]
Focus on search and collections pages.
Are we retrieving unecessary data?
Initial research:
https://www.binpress.com/tutorial/speeding-up-angular-js-with-simple-optimizations/135
http://blog.scalyr.com/2013/10/angularjs-1200ms-to-35ms/

**Comment by baileyspace** [comment]
The batarang chrome extension recently added a performance tab for Angular with "hints" on optimization 
![image](https://cloud.githubusercontent.com/assets/833332/12209802/55a43448-b60a-11e5-83bf-361ceb9ee9a7.png)

**Comment by AndersEverett** [comment]
Improved site speed with js minifications: f1b6963

Still need to look into gzip. It's not recommended to minify angular so will break that off into another ticket.

**Comment by AndersEverett** [comment]
gzip compression : ff5bd76

**Comment by Saltzshaker** [comment]
@AndersEverett how should I test this?

**Comment by AndersEverett** [comment]
From the initial check:
<img width="1001" alt="screen shot 2016-01-28 at 3 30 10 pm" src="https://cloud.githubusercontent.com/assets/7750668/12662297/47a692a8-c5d4-11e5-80fd-7b99779536f3.png">
From the follow-up check after minifying & gzip:
<img width="995" alt="screen shot 2016-01-28 at 3 30 36 pm" src="https://cloud.githubusercontent.com/assets/7750668/12662304/4ed6320e-c5d4-11e5-9628-dee15daea94d.png">

Improved speed by 12%.

**Comment by annewootton** [comment]
@AndersEverett Any idea why the page load time is longer now (5.1s) than it
was before (4.1s)?

**Comment by AndersEverett** [comment]
@annewootton I don't know the answer to that.

**Comment by Saltzshaker** [comment]
F to E seems like an improvement anyway! @AndersEverett thinks it the page load probably had to do with a temporary issue, like Internet connection. Marking this ready-to-deploy. @AndersEverett, could you make another ticket for Angular optimizations?

**Comment by AndersEverett** [comment]
Created new issue in Ginsburg for Angular Optimization research: #1359
