### ISSUE TITLE
Create referral codes

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1334]
See comments on https://github.com/popuparchive/pop-up-archive/issues/1317 for details on creating codes. Once codes are created, create fields to enter the codes both during sign up, and plan upgrading. Codes: #DemoDiscount and #PopUpFriend

**Comment by Saltzshaker** [comment]
Copying over @AndersEverett's comment from #1317:
"SaaSquatch appears to be a paid service only, so @Saltzshaker and I are discussing ways of building this out manually. We are looking at creating a join table called "References" to track referrer id's with emails of potential new users. **A question that has come up is in the case of two users referring the same potential user: do both referrers get 20% upon successful account creation of the 3rd?**" I think yes, because who knows which referrer really inspired the creation of the 3rd. Also, this seems rare enough that I'd rather credit everyone than run the risk of it getting back to a referrer that they didn't get credited for a new sign up. thoughts @annewootton?

**Comment by AndersEverett** [comment]
This can also be addressed by passing user id variables in the link urls. Whomever gets the link clinked, gets the 20% credit.

**Comment by AndersEverett** [comment]
Adding a ready-to-test label to this as both codes have been created on Stripe. The #DemoDiscount is functioning in Salvatore. #PopUpFriend functioning will be completed with #1320 .

**Comment by Saltzshaker** [comment]
Since upgrading isn't working in staging, need to test in production

**Comment by Saltzshaker** [comment]
Discounts all applied as expected! Closing. 

#DemoDiscount scenario one:
* demo-referrer gets 20% off after sending emails: #DemoDiscount 20% discount applied to next Stripe invoice ($16 for $20 plan). The month after is $20 as expected. 

#PopUpFriend (20% for 20%) scenario two:
* new-custy-paid gets 20% off on sign up: #PopUpFriend 20% discount applied to next Stripe invoice ($16 for $20 plan). The month after is $20 as expected. (Same discount for new user regardless of whether referrer was on a paid or demo plan)
* paid-referrer gets 20% off when new-custy-paid signs up: After new-custy-paid signs up, #PopUpFriend 20% discount applied to next Stripe invoice ($16 for $20 plan). The month after is $20 as expected.
* paid-ref gets 20% DOES NOT when new-custy-demo signs up: true
