### ISSUE TITLE
Switch over to aggregations

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1335]

**Comment by AndersEverett** [comment]
3 places:
analytics data viz
search page side bar
explore page

**Comment by AndersEverett** [comment]
Conversion to aggregations in 7463054 & f0940db.

**Comment by Saltzshaker** [comment]
![screen shot 2016-03-01 at 5 18 45 pm](https://cloud.githubusercontent.com/assets/8497203/13448063/ed92c85c-dfd4-11e5-84c7-3f483b5d83ad.png)
Search sidebar, tags, and entities all working. No viz showing up on /analytics, and clicking "More" on Explore only shows alphabet letters, but no content.

@AndersEverett is looking into the analytics page. Working more on the explore page issue requires @AndersEverett to fix his indices, which is a ticket in and of itself. We discussed commenting out "More" for now and having him look into in a future ticket, cc @annewootton

**Comment by Saltzshaker** [comment]
Explore page issues to be continued in https://github.com/popuparchive/pop-up-archive/issues/1379

**Comment by AndersEverett** [comment]
0d2be8d maps the data viz to aggregations -- bubbles are back. This is also in staging now.

**Comment by Saltzshaker** [comment]
Analytics looking good! "More" is commented out. Ready-to-deploy. 
![screen shot 2016-03-03 at 1 33 33 pm](https://cloud.githubusercontent.com/assets/8497203/13510278/a9a904e6-e144-11e5-8485-21c69f1a67b1.png)
