### ISSUE TITLE
Split out demo and plan usage on account page for "This Month" usage

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1336]
Instead of showing usage as total usage seconds subtracted from community plan usage, show "1hr demo" usage for the current month up to 1 hr. Everything in excess of that as "usage." For example, in the screenshot below, it would show:
Usage: 3 hr 14 min
1 hr demo: 1 hr*
*The 1 hr demo field only appears during months where there is usage on the 1hr demo plan.

https://www.popuparchive.com/superadmin/users/2482
![screen_shot_2015-12-09_at_11 24 09_am](https://cloud.githubusercontent.com/assets/8497203/11696287/6c4886d6-9e68-11e5-91c3-3669a16ef4b1.png)

**Comment by AndersEverett** [comment]
Premium transcript duration returns total usage seconds from the database. The "usage" section subtracts community plan usage from total usage seconds, so this will be different if the user transitioned from a community account to another account mid-month. 

Community plan usage for this user returns 66 minutes, which is the difference between the two in question here. So, is there any instance in which community plan usage should be 66 minutes? Is this related to #1209?

**Comment by annewootton** [comment]
@AndersEverett your assumptions are correct -- since the user had under 1hr total usage after the 49 min in September, they were able to upload another 66 minute file on the 1hr Demo plan without triggering the plan limit. Related to #1209. 

It seems like one way to correct the reporting could be to calculate usage in excess of 60 min on the 1hr Demo plan and count that toward the given month's limit — does that make sense? That 1hr doesn't renew, so these use case only occurs in the first month that someone upgrades from free to paid plan.

**Comment by Saltzshaker** [comment]
@annewootton "It seems like one way to correct the reporting could be to calculate lifetime usage in excess of 60 min on the 1hr Demo plan and count that toward the first month's limit" That makes sense to me.

How about instead of showing usage as total usage seconds subtracted from community plan usage, we show "1hr demo" usage for the current month up to 1 hr, and then everything in excess of that as "usage"? For example, in the screenshot above, it could show:
Usage: 3hr 14 min
1 hr demo: 1 hr

The 1hr demo field only appears during months where there is usage on the 1hr demo plan.

**Comment by AndersEverett** [comment]
That sounds good to me.

**Comment by annewootton** [comment]
That works for me. It's different from what I suggested (where we would attempt to apply lifetime usage in excess of the 1 free hour, which is compounded by what 1209 will fix, toward the first month limit of the paid plan) — but I think it's simpler and we'll be losing fewer hours on the free plan once we implement 1209 anyway. 

In this scenario, the user would have gotten 109 minutes on the free demo (49 in September, 60 in December) but I'm fine with that, especially if it makes the usage reporting consistent.

**Comment by Saltzshaker** [comment]
Ah, right, since the demo usage was split over multiple months it wouldn't catch that excess time — although it would if it was all uploaded in the same month, which I feel like is typically what happens.

Cool, let's go with this for now then. Moving this forward to Megan and renaming it.

**Comment by AndersEverett** [comment]
a2ecb14 Demo plan usage is now rendered separately below regular usage in user account page.

**Comment by Saltzshaker** [comment]
![screen shot 2016-01-28 at 2 11 01 pm](https://cloud.githubusercontent.com/assets/8497203/12660524/01febbaa-c5c9-11e5-9dc8-6a89a13b1437.png)
1-hr demo is split out, but usage is inaccurate.
Actual usage was 1min 56sec uploaded to the 1-hr plan, then 3min uploaded to 1-hr demo.

Tested with essaltz+reftest@gmail.com: https://pop-up-archive-staging.herokuapp.com/superadmin/users/2673

**Comment by AndersEverett** [comment]
I reworked the logic here: 1519a15. @Saltzshaker This is in staging now.

**Comment by Saltzshaker** [comment]
oorah! usage for 1 hr demo shows up as 1 hr demo, and usage on 1 hr plan shows up for estimated usage. Ready. to. deploy. :clap: 
![screen shot 2016-02-03 at 12 40 45 pm](https://cloud.githubusercontent.com/assets/8497203/12796435/84d62ac8-ca73-11e5-925d-f6477f484ec3.png)
