### ISSUE TITLE
Promote referral program

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1341]
Ideas:
* In nav bar
* On account page
* On pricing page

**Comment by Saltzshaker** [comment]
Added to signed-in nav https://github.com/popuparchive/pop-up-archive/commit/6c108bbb966da3dd7f7742a2f4aaacc49255419f, account page https://github.com/popuparchive/pop-up-archive/commit/d7e87d497cafcff8df6b0595c41f3daa47265521, and pricing page https://github.com/popuparchive/pop-up-archive/commit/34dab3c552c555de0eafe158ca730a677117dbe2 for signed-in users. For users without accounts, I added an FAQ about the referral program on the pricing page https://github.com/popuparchive/pop-up-archive/commit/3fe230f4842bffe6c0be1cb78eec9158203a2689. 

@annewootton I didn't add any links for non-users (i.e. in the nav or pricing page) because the /refer page requires an account in order to be visible and functional. We might want to consider creating a descriptive referral program landing page for this purpose. We could also just link to a Zendesk FAQ.

The app features are ready to test. Now moving on the the drip emails in MailChimp.

**Comment by annewootton** [comment]
The only place it's missing is for paid users on the /account page.

**Comment by Saltzshaker** [comment]
Added for paid users on the /account page. Will reassign to @annewootton when it's deployed to staging: https://github.com/popuparchive/pop-up-archive/commit/82ab48da3bef901a994589f8df1e8cf6cbcf8888

**Comment by annewootton** [comment]
READY TO DEPLOY
