### ISSUE TITLE
Switch PUA over to new VB API

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1343]

**Comment by baileyspace** [comment]
@AndersEverett Looks like it's getting hung up. I created a task for file 21178 task number 446520 in staging. Look like the transcript is complete but task is still working. If I run finish_task then I get:

NoMethodError: undefined method `[]' for nil:NilClass
	from /app/app/models/tasks/voicebase_transcribe_task.rb:263:in `finish_task'
	from (irb):14
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by baileyspace** [comment]
WARNING: Can't mass-assign protected attributes for Speaker: speakerLabel
	app/models/tasks/voicebase_transcribe_task.rb:420:in `block in create_speakers'
	app/models/tasks/voicebase_transcribe_task.rb:418:in `each'
	app/models/tasks/voicebase_transcribe_task.rb:418:in `create_speakers'
	app/models/tasks/voicebase_transcribe_task.rb:350:in `block in process_transcript'
	app/models/tasks/voicebase_transcribe_task.rb:332:in `process_transcript'
	app/models/tasks/voicebase_transcribe_task.rb:278:in `finish_task'
WARNING: Can't mass-assign protected attributes for Speaker: speakerLabel
	app/models/tasks/voicebase_transcribe_task.rb:420:in `block in create_speakers'
	app/models/tasks/voicebase_transcribe_task.rb:418:in `each'
	app/models/tasks/voicebase_transcribe_task.rb:418:in `create_speakers'
	app/models/tasks/voicebase_transcribe_task.rb:350:in `block in process_transcript'
	app/models/tasks/voicebase_transcribe_task.rb:332:in `process_transcript'
	app/models/tasks/voicebase_transcribe_task.rb:278:in `finish_task'

**Comment by baileyspace** [comment]
It's something in here:

    speakers_by_name.keys.each do |n|
      times = speakers_by_name[n].collect{|r| [BigDecimal.new(r['start'].fdiv(1000).to_s), (BigDecimal.new(r['start'].fdiv(1000).to_s) + BigDecimal.new(r['length'].fdiv(1000).to_s))] }
      speakers_lookup[n] = trans.speakers.create(speakerLabel: n, times: times)
    end
