### ISSUE TITLE
Fix search bar placement

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1346]
![screen shot 2016-01-06 at 3 30 31 pm](https://cloud.githubusercontent.com/assets/8497203/12157929/745c1314-b48a-11e5-8a2b-293f6576348b.png)

Add margin

**Comment by AndersEverett** [comment]
d139163 Moved the pager row down with next/search/previous components.

**Comment by Saltzshaker** [comment]
looks good https://pop-up-archive-staging.herokuapp.com/collections/3247
![screen shot 2016-01-28 at 11 59 04 am](https://cloud.githubusercontent.com/assets/8497203/12657117/92758596-c5b6-11e5-9ff3-9312ad268804.png) 
marking ready-to-deploy
