### ISSUE TITLE
Fix height for tplayer

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1347]
It's a little funky:
http://www.cbc.ca/radio/spark/301-teaching-through-text-message-designing-connection-and-more-1.3338846/how-to-make-websites-more-accessible-for-people-who-are-deaf-1.3338862
![screen shot 2016-01-07 at 4 53 23 pm](https://cloud.githubusercontent.com/assets/8497203/12187261/44ab69e6-b55f-11e5-9f7b-6fd6b580e10c.png)

**Comment by Saltzshaker** [comment]
@baileyspace looking at link above, the player still has extra space: http://www.cbc.ca/radio/spark/301-teaching-through-text-message-designing-connection-and-more-1.3338846/how-to-make-websites-more-accessible-for-people-who-are-deaf-1.3338862

**Comment by Saltzshaker** [comment]
On Tumblr:
![screen shot 2016-03-04 at 11 02 54 am](https://cloud.githubusercontent.com/assets/8497203/13537359/68a52b9a-e1f9-11e5-9ca1-93050283f55b.png)
Note: when I go back to edit the post, the "onload" part of the embed code is stripped out (not true of WordPress though):
`<p><iframe` frameborder="0" width="100%" scrolling="no" seamless="yes" `src="https://pop-up-archive-staging.herokuapp.com/tplayer/40306"></iframe></p>`

On WordPress:
![screen shot 2016-03-04 at 11 07 24 am](https://cloud.githubusercontent.com/assets/8497203/13537366/6ff933f0-e1f9-11e5-8535-43198a1de720.png)

**Comment by baileyspace** [comment]
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://fiddle.jshell.net" from accessing a frame with origin "https://pop-up-archive-staging.herokuapp.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.

**Comment by Saltzshaker** [comment]
Looking good! Ready to deploy. ![screen shot 2016-03-04 at 3 34 34 pm](https://cloud.githubusercontent.com/assets/8497203/13543304/ccfe3742-e21e-11e5-86ec-c959a95d589f.png)
![screen shot 2016-03-04 at 3 34 26 pm](https://cloud.githubusercontent.com/assets/8497203/13543303/ccfd264a-e21e-11e5-80c1-117c21e52411.png)
