### ISSUE TITLE
Split out demo and plan usage in Superadmin

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1349]
Reflect changes made to the account page https://github.com/popuparchive/pop-up-archive/issues/1336 in superadmin view

**Comment by AndersEverett** [comment]
I added a basic table to superadmin to track premium community transcript usage. There isn't anything currently in the monthly usage summary class that makes this a seamless addition. It may need further work for full integration. Testing will tell. 4f081d0

**Comment by Saltzshaker** [comment]
User uploaded 65.6 minutes to the demo plan, then more on the 10 hour plan. Demo usage split out as expected.
![screen shot 2016-03-01 at 1 18 04 pm](https://cloud.githubusercontent.com/assets/8497203/13442283/44c6898a-dfb0-11e5-9a81-6b5476c51ab4.png)
I'm good with deploying this for now, then I can spot-check it further where we have more complex usage histories.

**Comment by annewootton** [comment]
IT DOES WHAT I NEED HALLELUJAH THANK YOU EVERYONE
