### ISSUE TITLE
Write rake task to get usage info for Mixpanel retroactively

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1352]
https://github.com/popuparchive/pop-up-archive/issues/1333 will log the usage activity of users going forward, but we also need to run a rake task to update the info in mixpanel to include past upload activity.

We want to see all audio uploaded by each user, and whether they're over their limit at any given time.

**Comment by Saltzshaker** [comment]
@baileyspace looking at mixpanel. looks like the rake task got most people. any idea why some still have blank info? https://mixpanel.com/report/566281/explore/#list/filter:(conjunction:and,filters:!()),sort_order:descending,sort_property:'$last_seen',sort_property_type:datetime

**Comment by baileyspace** [comment]
The rake task would only work for users in the pua staging database, so any
test users/other users somehow not accounted for in the database would not
receive the new values.
