### ISSUE TITLE
[Referral Program] Notify paid users of discount when their invitee signs up 

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1353]
Users on paid plans get a 20% discount on their next month when someone they refer signs up for a paid plan. Create email alerting the paid user when they get the discount.

---

From: edison@popuparchive.com
Subject: You just earned a discount for your Pop Up Archive plan! 
Email: Hi {Username},

Someone you invited to Pop Up Archive just signed up for a paid plan. That means we'll knock off 20% from your Pop Up Archive bill next month. Enjoy your discount, and we'll see you in the archive!

Best,
The Pop Up Archive Team

**Comment by AndersEverett** [comment]
Added the mailer in 0c20e47.

**Comment by AndersEverett** [comment]
The referral credit and the mailer are kicked off in a session belonging to the new referred user. I think we'd have to add a referral credit flag to the database to get the message back into the referrer's account page in a different session. Do we want to add that for a one-time discount, or is the email enough?

**Comment by Saltzshaker** [comment]
Ah. Yeah, that sounds complicated. In that case, I'm good with just the email, unless @annewootton or @baileyspace feel strongly otherwise.

Question: when the users, either new referring or referred, are discounted in Stripe, did you add a specific message describing their discount in their receipt for the month? If not, this might be nice to add. (i.e. on Feb 1 if a referring user gets a discount because their friend signed up, their receipt says something like "20% Discount for Referral Program")

**Comment by AndersEverett** [comment]
@Saltzshaker , Does the receipt come from us or stripe? I can see it in the stripe invoice summary.

**Comment by Saltzshaker** [comment]
It comes from Stripe. When we charge manually at least, I know we can add custom description text to the receipt.

**Comment by AndersEverett** [comment]
It lists the discount explicitly in the summary, so I'm guessing it will show up on their receipt.

**Comment by Saltzshaker** [comment]
Cool. I'll check it out when I test it in production.

**Comment by Saltzshaker** [comment]
Since sign up works for new users in staging (just not for changing plans), I was able to test this. The existing 1-hr monthly plan customer 'edison+mat@popuparchive.com' invited a new user 'emily+newsignup@popuparchive.com' Using the email link, 'emily+newsignup@popuparchive.com' then signed up for a 1-hr monthly plan. 

'edison+mat@popuparchive.com' got confirmation of sign up: 
![screen shot 2016-01-28 at 1 00 12 pm](https://cloud.githubusercontent.com/assets/8497203/12658650/2200abfc-c5bf-11e5-8762-798548599bbf.png)

Ready-to-deploy!

**Comment by Saltzshaker** [comment]
@AndersEverett Referring users should only get a discount when new custys sign up for a *paid* plan. The discount email is sent even when an invitee signs up for the 1-hr demo.

**Comment by AndersEverett** [comment]
f283acd Email to referrrer now triggers only if referred plan is paid.

**Comment by Saltzshaker** [comment]
Hm, I tried signing up two new invited users, one for a paid plan, and one for a demo. The referrer got two email notifications that they earned a discount. 

@AndersEverett The referrer should only get one discount email for the paid plan sign up. Also, regardless of the plan of the new users, the referrer should also only ever get max one email per month anyway, since the discount only applies max once per month. (Let me know if this is confusing, there are so many scenarios it gets hard to talk about!)

**Comment by AndersEverett** [comment]
Per your message today, aren't we allowing unlimited discounted months: "it looks like we decided on a max of one referral discount per user per month"?

Are you saying you want the emails spaced out, 1/month?

**Comment by Saltzshaker** [comment]
Stripe says: "An invoice can only have one coupon applied–it’s not possible to stack two or more coupons onto an invoice." The referring customer should only *get* the discount once per month, so they should only get one email for that discount. Beyond that, they're not discounted. 

For example, if I'm on a 5hr plan and invite 3 people to sign up in February, and two of them sign up for paid plans, I can only get one 20% discount. The other one does not apply. If I wanted another discount, I would have to wait until the next invoice period and get another new person to sign up for a paid plan.

**Comment by AndersEverett** [comment]
@Saltzshaker Yes, the stripe part is clear. What I'm wondering is about the email frequency to the referrer. I think the simplest solution would be to amend the outgoing email to explain that multiple successful references equals one 20% discount a month. So if they get 3 in a row, they'll know what to expect.

**Comment by AndersEverett** [comment]
Rewrite email with disclaimer for one referral discount/month. Grab new user's name and send in referrer notice.

**Comment by AndersEverett** [comment]
82ec230 revises email with personalized message and disclaimer.

**Comment by Saltzshaker** [comment]
Email looks good. No longer sends when new user signs up for the demo plan. Ready to deploy
