### ISSUE TITLE
www.popuparchive.org doesn't work

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1354]
Have we discussed this before?

If it can't be fixed easily, we should change the website linked from https://itunes.apple.com/us/podcast/popcast/id970535981?mt=2 because people have contacted me to say it's broken.

**Comment by Saltzshaker** [comment]
I changed the website to popuparchive.com in SoundCloud feed. The iTunes page should update soon. I'll check tomorrow.

**Comment by Saltzshaker** [comment]
Podcast website link now points to popuparchive.com. Assigning to @baileyspace to deal with underlying .org issue

**Comment by annewootton** [comment]
popuparchive.org redirects to https://www.popuparchive.com. We can't redirect from https://www.popuparchive.org or www.popuparchive.org without getting a separate SSL certificate for popuparchive.org. We're not going to do that, so I'm closing this!
