### ISSUE TITLE
UI Changes for Referral Program

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1355]
View changes:

* Users invited to sign up should see this when they click on a plan: "Your #PopUpFriend discount will applied to your first invoice. Thanks! Total: $ discounted plan amount" (following same model in the screenshot above for #DemoDiscount)
* Delete "Enter 3+ emails and press send to see your promo code!" Replace with "Make sure you're ready to redeem your discount as soon as you send the invites! You can only redeem your discount immediately after sending."
* Add header on pricing page that says ""Get 20% off now with our #PopUpFriend discount!" for new users trying to redeem the #PopUpFriend discount after clicking on the email link.
* Update email:

---

from: edison@popuparchive.com
subject: {Referrer's first name} sent you a discount for automatic transcription from Pop Up Archive
Hey there,

Your friend {referrer's name} just invited you to join Pop Up Archive, a service that makes audio searchable with high-accuracy automatic transcripts. Pop Up Archive can help save you tons of time transcribing, and allows you to search for exact words and phrases within audio files.

Click here to get 20% off of your first month with our #PopUpFriend discount: pop-up-archive.dev/pricing?ui=1048. There's also a free demo you can try out. Learn more at popuparchive.com/about.

Thanks! 
The Pop Up Archive Team

---

**Comment by AndersEverett** [comment]
Email updated with : 5b347a3
UI updates for paying referrers: 8067773
Modal renders discount for new #PopUpFriend users: ee45a26

**Comment by Saltzshaker** [comment]
Email looks good. Some extra spaces snuck in there, which I removed here: https://github.com/popuparchive/pop-up-archive/commit/5329e0fe91881ff04d8d717331c383e6848d822e
UI updates for paying referrers also look good.
![screen shot 2016-01-28 at 10 28 01 am](https://cloud.githubusercontent.com/assets/8497203/12655293/11e03074-c5ad-11e5-8672-25d34efdf275.png)

Two issues with proposed changes:
* Modal renders discount for #PopUpFriend users with existing accounts, but not for new users without accounts. When new users without accounts click on the referral link, there is no indication of a discount until they click on a plan:
![screen shot 2016-01-28 at 10 29 51 am](https://cloud.githubusercontent.com/assets/8497203/12655377/7fcedb62-c5ad-11e5-8050-e1d0c4cc26de.png)

**Change: Users without accounts should also see the "Get 20% off now with our #DemoDiscount!" header**




* Also, it looks like #PopUpFriend referrers (i.e. paying users who only get a discount when another user signs up) are immediately directed to the pricing page with #PopUpFriend discount messaging after sending emails. 
![after-20for20-existinguser](https://cloud.githubusercontent.com/assets/8497203/12655321/38300fec-c5ad-11e5-97b1-670de7c0548e.png)
**Change: Since they don't get the discount until someone signs up, change the pricing page header to say: 
"Thanks for referring! You'll get 20% off your plan when a friend signs up with your promo code."**

**Comment by AndersEverett** [comment]
First change completed with : 5251c75.
Second change completed with : a625c5923cd9455f535c1d837ae9e19f61e4b4b6.
