### ISSUE TITLE
[Mixpanel] Make sure 'monthly usage' & 'hours remaining' properties don't get reset for demo users

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1363]
Rewrite the 'monthly usage' and 'hours remaining' properties so that they don't reset each month for demo users. 

While this is what we want for paid plans, it messes up targeting for demo plan users, where the hour limit is fixed for all time. For example, when I try to target demo users who signed up in the last 30 days & haven't uploaded any audio with an email is to encourage them to upload audio, the list includes users who uploaded audio in January and haven't uploaded audio in February.

**Comment by baileyspace** [comment]
Took a peek at this, and it looks like it should have been resolved by the fix for #1368. Assigning to @Saltzshaker to verify.

**Comment by Saltzshaker** [comment]
Yep! Looks like users who have uploaded 1+ hours (either for the current month or in past months) are showing up with a property of "True" for "Is over their monthly limit" in Mixpanel. Supposedly only 137 plans are in this state, which seems low, but plausible? @baileyspace do you need to run a new Rake task or anything to make sure this property is updated for all users?

**Comment by Saltzshaker** [comment]
Mixpanel: "It actually looks like your account is well within the Free threshold for the people plan so you should have no trouble accessing the People section of Mixpanel currently. In general, though, you can always import data to your project and it will be collected normally even while you're blocked - it's just accessing the reports that is restricted until the following month."

So @baileyspace, you can go forth and rake

**Comment by baileyspace** [comment]
running rake users:mixpanel_update

**Comment by Saltzshaker** [comment]
Cool. It's now up to 330. Spot-checked some recent over-limit users and took a look at the demo conversion spreadsheet and everything looks pretty legit. Closing, since it's already live
