### ISSUE TITLE
1 hr demo limit resets each month

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1368]
1 hr demo users should only be able to upload 1 hr ever. However, it looks like the hour limit resets every month. For example, https://www.popuparchive.com/superadmin/users/3226 uploaded over an hour in January, and now is able to upload again without any over limit messaging.

**Comment by AndersEverett** [comment]
Write an rspec test and use time gem for time advancement.

**Comment by Saltzshaker** [comment]
Confirmed in staging: https://pop-up-archive-staging.herokuapp.com/superadmin/collections/5814/. I uploaded two 30 sec file to an account that had used their full time on the 1 hr demo plan in October. Both new files went through with processing. No illegal status, or over-limit banner.

**Comment by AndersEverett** [comment]
6780cbe & ab8909a

**Comment by Saltzshaker** [comment]
Test for account that has used up 1+ hr on demo in previous month. User's account page should show that it's over the limit and over-limit banner should show up

**Comment by Saltzshaker** [comment]
This user uploaded 1+ hr to the 1hr demo in March and is now over her limit: https://pop-up-archive-staging.herokuapp.com/superadmin/users/3836
![screen shot 2016-04-19 at 4 06 55 pm](https://cloud.githubusercontent.com/assets/8497203/14658543/5fbf96e0-0649-11e6-947e-6cb2ec83e087.png)

![screen shot 2016-04-19 at 4 06 45 pm](https://cloud.githubusercontent.com/assets/8497203/14658540/580e3712-0649-11e6-89b5-468a056ac94a.png)

Usage shows correct 1hr demo usage, but 0/1hr usage for this month. @annewootton do you think this is confusing implies that the user have 1 more hr for the current month, even though they've already used their 1hr all-time total? Wondering if we should 1) hide "This Month" usage for demo users and just show demo usage, or 2) have This Month usage match the all-time usage for demo users.

**Comment by annewootton** [comment]
I agree that it could be confusing. Let's hide "this month" for demo users.
ᐧ

**Comment by AndersEverett** [comment]
2434807 'this month' hidden from community plan account pages.

**Comment by Saltzshaker** [comment]
👍 
![screen shot 2016-04-21 at 11 52 46 am](https://cloud.githubusercontent.com/assets/8497203/14725086/d2d6f994-07ce-11e6-91d0-d0c07cc9e496.png)
