### ISSUE TITLE
Prevent two VB jobs from being created simultaneously

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1369]
See files: 56704, 56750, 56685

Start with quick look and identify the files where this has happened (all jobs with multiple VB tasks created within a minute of each other). Move out if not obvious.

Might be race condition, which could be very tricky, or even wontfix. Also check when tasks are created—might be at same time nudger is run.

**Comment by Saltzshaker** [comment]
This is tricky, and seems rare enough that we're moving it forward.

**Comment by annewootton** [comment]
Won't fix.
