### ISSUE TITLE
Replace "Premium transcript" with "Automatically generated transcript"

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1370]
Replaced on pricing page plans and pricing faq, faq, zendesk, the enterprise page, premium transcript complete status (now "Transcript complete"), and premium transcript labels (now reads "Pop Up Archive Transcript"; I left the Basic label in but changed the description to direct people to an FAQ about our "new" transcription software)

**Comment by Saltzshaker** [comment]
More changes here: https://github.com/popuparchive/pop-up-archive/commit/7432547b2ee8a94360b34c9db2e26cb348ba6d7c when deployed to Sally, will reassign @annewootton to test

**Comment by annewootton** [comment]
Looks good on:
-Pricing page plans 
-Pricing faq
-Enterprise page
-Transcript status alert on My Collections page (now "Transcript complete")
-Text in label once I click "Premium transcript" label on item page
-FAQ
-Zendesk

Marking ready-to-deploy!
