### ISSUE TITLE
For edited speakers, don't show/print the same speaker consecutively

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1383]
For example, after assigning what was once S11, S2, S8 (etc.) all to speaker "DB" (David Bowie), he shows up multiple times in a row. DB should only show up the first time until the next speaker change.

Also applies to transcript downloads.
![screen shot 2016-03-01 at 5 01 12 pm](https://cloud.githubusercontent.com/assets/8497203/13447323/81b876b8-dfcf-11e5-83f5-1d5bef4e4e9e.png)

**Comment by annewootton** [comment]
Won't fix pending integration of American Archive editor.
