### ISSUE TITLE
Add low-priority Sidekiq queue for batch jobs

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1384]

**Comment by Saltzshaker** [comment]
@AndersEverett should talk to @baileyspace about this, and do this before AA import (https://github.com/popuparchive/pop-up-archive/issues/1392)

**Comment by AndersEverett** [comment]
Low priority queues necessary for both fixer and pua.

**Comment by AndersEverett** [comment]
388b6fe adds this to the pua side. Don ticket #1417 will address fixer side queue once I have my fixer dev environment set up.

**Comment by Saltzshaker** [comment]
@AndersEverett will check to see if the new Sidekiq queue shows up in Sidekiq dashboard after running the American Archives rake task

**Comment by AndersEverett** [comment]
Sidekiq queue for low-priority batching is now visible in dashboard with : 5017d8d

**Comment by AndersEverett** [comment]
I removed ready-to-deploy from this. While the batch queue is populating with tasks from newly created items, these tasks aren't completing in staging. More testing needed.

**Comment by AndersEverett** [comment]
Will test in production.

**Comment by AndersEverett** [comment]
Fixed with 7ee54ef
