### ISSUE TITLE
Files stuck in “processing” with a complete VB task (no transcript in UI)

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1385]
This is distinct from the status mismatch issue https://github.com/popuparchive/pop-up-archive/issues/1381 because the VB task is not returned in the UI, despite being "complete" with a transcript text in the callback in superadmin. task.finish_task returns 'nil'

Happened for several files here (which have since been pushed through manually): 
https://www.popuparchive.com/superadmin/items/52116
https://www.popuparchive.com/superadmin/items/52114
https://www.popuparchive.com/superadmin/items/52115

**Comment by baileyspace** [comment]
All clear for the last 12 hours. Closing.
