### ISSUE TITLE
Collection pages show incorrect number of results

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1387]
For example: https://pop-up-archive-staging.herokuapp.com/collections/938
![screen shot 2016-03-03 at 7 55 27 pm](https://cloud.githubusercontent.com/assets/8497203/13517624/ef383060-e179-11e5-8640-df2687fa5201.png)

**Comment by AndersEverett** [comment]
d82c1f9 should have fixed it.

**Comment by Saltzshaker** [comment]
Indeed. Ready to deploy.
![screen shot 2016-03-04 at 12 46 09 pm](https://cloud.githubusercontent.com/assets/8497203/13539756/29994388-e207-11e5-9029-33ac2e7608f0.png)

**Comment by Saltzshaker** [comment]
@AndersEverett Ah, just noticed that private collections are showing up with 0 items
https://pop-up-archive-staging.herokuapp.com/collections/1937
![screen shot 2016-03-04 at 2 21 07 pm](https://cloud.githubusercontent.com/assets/8497203/13541953/5dcb7484-e214-11e5-9ac6-fe8c01280483.png)

**Comment by Saltzshaker** [comment]
Private collection now shows items. Ready to deploy.
![screen shot 2016-03-04 at 3 47 29 pm](https://cloud.githubusercontent.com/assets/8497203/13543497/88f6dd54-e220-11e5-8f8b-8da6abd21c64.png)
