### ISSUE TITLE
Item images broken on collection page

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1388]
Looks fine on the item page itself, but broken on collection page. 
See https://www.popuparchive.com/collections/431:

![screen shot 2016-03-04 at 1 19 29 pm](https://cloud.githubusercontent.com/assets/1718286/13540493/c1918930-e20b-11e5-9edc-6faa9c006bc0.png)

**Comment by annewootton** [comment]
@shindostrz has a potential fix for this, but when he pulled a fresh database and reindexed his dev environment, the problem went away. so, we should do the same in staging and confirm if the issue persists.

**Comment by Saltzshaker** [comment]
@AndersEverett assign this to me to test when staging is done reindexing

**Comment by Saltzshaker** [comment]
The file from @annewootton's screenshot above is no longer in the Meyerson collection, but another Meyerson file still has a broken image, both on the collection results page and the item page: https://pop-up-archive-staging.herokuapp.com/collections/431
![screen shot 2016-04-20 at 12 44 52 pm](https://cloud.githubusercontent.com/assets/8497203/14688098/be1a1182-06f5-11e6-9385-9598d22a95bf.png)

Searched around some more and also saw that Popcast images were broken on the collection results page and the item page. Not sure if this is the same issue https://pop-up-archive-staging.herokuapp.com/search?page=1&query=collection_id:%224425-Popcast%20by%20Pop%20Up%20Archive%22

Assigning back to @shindostrz

**Comment by Saltzshaker** [comment]
Initial 'challenger' file is showing up now, and has an image, but the 'jim wright' file above, along with a new file (see screenshot) have broken images on item and collection pages. 
https://pop-up-archive-staging.herokuapp.com/collections/431
popcast is also still showing broken images on item and collection pages, even though they're working in production https://pop-up-archive-staging.herokuapp.com/collections/4425
![screen shot 2016-04-20 at 6 24 02 pm](https://cloud.githubusercontent.com/assets/8497203/14695321/e52ebe8c-0725-11e6-8d49-6b89c46ef58c.png)
![screen shot 2016-04-20 at 6 22 19 pm](https://cloud.githubusercontent.com/assets/8497203/14695324/e8ea3ee8-0725-11e6-8c28-63f6ccb16b29.png)

**Comment by shindostrz** [comment]
The Popcast images appeared broken because we had the wrong CDN URL in staging. They're fixed now.

**Comment by Saltzshaker** [comment]
@shindostrz cool, thanks! did you look into the other broken Meyerson images? (Live from the Heartland and U.S. House Speaker Jim Wright?)

**Comment by annewootton** [comment]
As of today's standup he was fixing Meyerson manually, probably as we speak, and also taking care of the Cloudfront issues once and for all (#1407)

**Comment by Saltzshaker** [comment]
Ah, right. @shindostrz, you're fixing the Meyerson images manually in production I take it? Meaning this is ready-to-deploy?

**Comment by annewootton** [comment]
Checked with @shindostrz — let's wait till Meyerson is fixed; he'll mark ready-to-deploy.

**Comment by shindostrz** [comment]
The timeout solution works, but there's some intermediate broken-looking image stuff happening before it automatically refreshes that we might want to try and get rid of so we don't confuse people.

**Comment by annewootton** [comment]
Great; this speaks to #1407 as well. We can open a separate ticket for the intermediate broken-looking image stuff.

**Comment by annewootton** [comment]
Telling Meyerson to re-upload "Live From The Heartland" which is the one image that got lost in this shuffle.
