### ISSUE TITLE
Problem transcribing recent transcoded m4a files

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1394]

**Comment by Saltzshaker** [comment]
5+ hours in and still processing the ~6 min files. All files were transcoded successfully shortly after upload and play. 2/7 in the collection completed on their own: https://www.popuparchive.com/superadmin/collections/7367 Refired VB tasks and wrote to VB with the job ids.

**Comment by Saltzshaker** [comment]
https://www.popuparchive.com/superadmin/collections/7367 files pushed through by VB. Note: I had to run finish_task to get them to show up
