### ISSUE TITLE
Why is error email sending multiples for vb empty speaker hash task cancellation notice?

### ISSUE THREAD

**Issue by AndersEverett** [popuparchive/pop-up-archive#1396]
Email fires to edison when an empty speaker hash / no speaker hash is returned from vb. The task is set to 'cancelled,' but email is sending multiple times over several hours. Check on methods that occur in vb task 'finish_task' from line 298 to end of method.

**Comment by annewootton** [comment]
Check this out right now for live-action evidence! https://www.popuparchive.com/superadmin/tasks/498236

**Comment by AndersEverett** [comment]
563a8a7
