### ISSUE TITLE
URLs not found at archive.org

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1400]
As noted for this file (https://www.popuparchive.com/superadmin/audio_files/59677), PUA is trying to find file at http://archive.org/download/napolitano-2-way-mp3.r7E38U.popuparchive.org/Napolitano_2_way.mp3 and failing, but file does exist here (all-caps MP3): http://archive.org/download/napolitano-2-way-mp3.r7E38U.popuparchive.org/Napolitano_2_way.MP3

A RuntimeError occurred in background at 2016-03-15 00:16:46 UTC :

  URL not found yet, try again: http://archive.org/download/napolitano-2-way-mp3.r7E38U.popuparchive.org/Napolitano_2_way.mp3
  /app/app/workers/check_url_worker.rb:20:in `block in perform'

  -------------------------------
Backtrace:
-------------------------------

  /app/app/workers/check_url_worker.rb:20:in `block in perform'
  /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
  /app/app/workers/check_url_worker.rb:12:in `perform'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
  /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
  /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-unique-jobs-4.0.7/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/logging.rb:22:in `with_context'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:108:in `stats'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:47:in `block in process'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:86:in `do_defer'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:37:in `process'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

-------------------------------
Data:
-------------------------------

  * data: {:message=>
    {"retry"=>25,
     "queue"=>"default",
     "class"=>"CheckUrlWorker",
     "args"=>
      [498397,
       "mp3",
       "http://archive.org/download/napolitano-2-way-mp3.r7E38U.popuparchive.org/Napolitano_2_way.mp3"],
     "jid"=>"d74e86b11d636c44adfeb498",
     "enqueued_at"=>1458000153.9388301,
     "error_message"=>
      "URL not found yet, try again: http://archive.org/download/napolitano-2-way-mp3.r7E38U.popuparchive.org/Napolitano_2_way.mp3",
     "error_class"=>"RuntimeError",
     "failed_at"=>1458000167.0876951,
     "retry_count"=>5,
     "retried_at"=>1458001006.878166}}

**Comment by AndersEverett** [comment]
convert it to lowercase in angular item cleaner.

**Comment by Saltzshaker** [comment]
Assigning to myself to write to IA and see if they can redirect links with different caps to proper item

**Comment by Saltzshaker** [comment]
Well, IA says "The site is case sensitive and I have no reason to expect that to change. If you want you can rename the file to have lower case .mp3" ('tude, much?)

@annewootton @baileyspace lemme know what we should do with this ticket

**Comment by annewootton** [comment]
Oh, I think it's fair for them to say that. How hard would it be for us to
do this @baileyspace @anderseverett?

**Comment by annewootton** [comment]
Run a task to check how many IA items have uppercase file extensions in their URLs. Then probably change them to lowercase.

**Comment by AndersEverett** [comment]
53313c4

**Comment by Saltzshaker** [comment]
For testing: Create IA collection in staging and upload an all-caps mp3.

Go to detect derivatives task in superadmin, make sure there's no error that says 1 version not found. should have mp3 and ogg and detected_at timestamp

**Comment by Saltzshaker** [comment]
I uploaded "01_ZeppsXmasGreeting.MP3" (all-caps) to an IA collection. PUA recorded it with lower caps in the extras hash, so problem likely not solved. It will likely fail/cancel itself, since IA will be storing it with all-caps because the initial file has all-caps. @AndersEverett's fix was supposed to store it in the hash with the upper cases. Since it's not, it looks like it’s getting downcased somewhere else. He's investigating.

**Comment by AndersEverett** [comment]
2723a14 should downcase all extensions on item creation and prevent the case diff with IA.

**Comment by Saltzshaker** [comment]
https://pop-up-archive-staging.herokuapp.com/superadmin/tasks/521112

Detect_derivatives has mp3 and ogg and detected_at timestamps and no errors. Marking ready-to-deploy
