### ISSUE TITLE
Broken images uploaded to items

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1407]
All images newly uploaded to PUA display as broken images.
Examples:
https://www.popuparchive.com/superadmin/items/46562
https://www.popuparchive.com/superadmin/items/48232

Original complaint was for: https://www.popuparchive.com/superadmin/items/53605 (broken image has since been deleted)

**Comment by Saltzshaker** [comment]
@shindostrz, given your closeness to image issues, we thought you could take a pass at this

**Comment by shindostrz** [comment]
The image uploads fine but the thumbnail isn't being created or stored properly

**Comment by shindostrz** [comment]
After more investigation, we realized that actually everything is being uploaded just fine, but it takes Cloudfront a few minutes to pick the assets up from the S3 bucket. We are going to ask AWS how to fix this.

**Comment by annewootton** [comment]
@shindostrz is either going to have images bypass Cloudfront entirely or try to force a short delay before we try to grab the image from Cloudfront, so it doesn't error and cache the error.

**Comment by annewootton** [comment]
See #1388.
