### ISSUE TITLE
Ensure new vb task is fired when job status is 'failed' at vb.

### ISSUE THREAD

**Issue by AndersEverett** [popuparchive/pop-up-archive#1419]
When a VB task returns 'failed' status, make sure we fire a new transcript, since apparently that didn't happen for these three files from 4/13-4/14? All were stuck in 'working' until I [@saltzshaker] manually fired new transcribe tasks. When I ran 'finish_task' on the initial working tasks, they returned the error: "Cannot finish task where VB status != finished (failed)"
https://www.popuparchive.com/superadmin/tasks/519441
https://www.popuparchive.com/superadmin/tasks/519733
https://www.popuparchive.com/superadmin/tasks/519722

**Comment by AndersEverett** [comment]
This seems like a situation where vb failed at the moment the nudger broke. The first task has retrieved the failure message from the vb media object, but the second and third never did. So, it looks like recover was called by the nudger on the first item, but then the transcript_check rake never hit any of them. I've added check_task to the recover method so that the audio files with the failed/rejected jobs don't have to wait for the transcript_check to proceed with processing. This will need to be tested to make sure it won't result in multiple jobs being fired off at once. f61558d

**Comment by Saltzshaker** [comment]
@AndersEverett is going to test this, cuz he knows what's up
