### ISSUE TITLE
Make sure users' buckets are all 'www-prod-popuparchive'

### ISSUE THREAD

**Issue by shindostrz** [popuparchive/pop-up-archive#1421]
Meyerson's collection contained storage configurations with old buckets that no longer exist.

**Comment by AndersEverett** [comment]
Find all audio files with old bucket storage and see if they are available.

**Comment by AndersEverett** [comment]
There were 4 audio files with dead bucket names ('pop-up-archive'). Two of these (7879,  7886) are 404 pages. The third, 7885, plays(from IA)/has ts, and there's no copy of it in www-prod-popuparchive. The last, 48759, didn't play; but once the token and bucket were set correctly, it was fixed. Closing ticket.

**Comment by annewootton** [comment]
Check image files too plz!

**Comment by AndersEverett** [comment]
All images with bad buckets pointed to 'www-prod-popuparchive.'
