### ISSUE TITLE
Old audio from feeds processing due to URLs with underscores now being accepted

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1422]
Customer alerted us that they received dozens of transcript completion alerts today — looks like many old items (i.e. from 2014) from feeds created new items and processed. See https://www.popuparchive.com/superadmin/collections/4263/items/57529 for example. 

@baileyspace Upon further inspection, looks like these items all have underscores in the URLs. So: probably because of the fix we put in to account for URLs with underscores, yeah?

I think new items stopped being created only because customer hit monthly limit — hesitant to up their limit until we can figure out how many more items would get created as a result.

**Comment by annewootton** [comment]
Options:

1) Mark these collections transcribe_false for a day while any additional items come in?
2) Run the rake task without actually creating items and see how many more items we risk creating if we up their limit?

**Comment by baileyspace** [comment]
Put in an argument for oldest entry for monitor feed. @Saltzshaker, so you should be able to up the user's limit now.
