### ISSUE TITLE
Crazy org usage on account page

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1424]
Viewing as an org member, I noticed that the org monthly usage numbers are very odd. @AndersEverett can you look into where these numbers are coming from?
![screen shot 2016-04-25 at 12 42 46 pm](https://cloud.githubusercontent.com/assets/8497203/14796760/d5f457d0-0ae3-11e6-8171-48ee60634f79.png)

Viewing as https://www.popuparchive.com/superadmin/users/1075
(looked the same on the 100 plan too)

**Comment by AndersEverett** [comment]
3f40b64 & 83c081f

**Comment by Saltzshaker** [comment]
Tested on a few org member account pages and looked good to me!

**Comment by Saltzshaker** [comment]
@AndersEverett deployed straight to master
