### ISSUE TITLE
Duplicate customers in Stripe

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#389]
Beyond Bailey's bazillion customer ids, which we already knew about, a good number of new accounts created have duplicate customer ids in Stripe. Hmm...

**Comment by annewootton** [comment]
This isn't critical for the Community Plan milestone because we can get a list of current subscribers to the Community Plan without deleting Stripe dupes. However, it's a headache to have the Stripe database full of dupes so I'm moving it to TBD, assigning high priority, and giving it to @pkarman.

**Comment by pkarman** [comment]
test would be:

* sign up with new user
* verify only one customer record created

there is also a clean up task for running post-deployment.

**Comment by tarakieffer** [comment]
When I used an existing email address on the sign up page, it created another customer in Stripe. Is this what is meant by "sign in from the signup page"
![screen shot 2015-08-02 at 8 14 21 am](https://cloud.githubusercontent.com/assets/9256525/9026259/85da3052-38ee-11e5-8ab0-25be12d5810c.png)

I did correctly get a message that email was already in use.
![screen shot 2015-08-02 at 8 11 23 am](https://cloud.githubusercontent.com/assets/9256525/9026261/94bf4d3c-38ee-11e5-8c48-31a0ca3c652c.png)

**Comment by pkarman** [comment]
it sounds like yes, you were repeating the buggy use case correctly.

the duplicate Stripe customer check was looking back 1 minute; from the screen shot, it looks like your customers were 2 minutes apart. I have expanded the duplicate check to 10 minutes.

I'm still not sure on the code path that reproduces this bug, since from what I can see there is only one call to Stripe::Customer.create() in the codebase and it is only called if the User has no stripe customer_id already defined. There might be some kind of race condition since things are cached pretty heavily. Hopefully the 10 minute window is wide enough now to prevent this duplication.

**Comment by tarakieffer** [comment]
So this will catch folks that are doing this right after signing up, but will not catch folks that maybe forgot they had signed up for an account on a previous day?

**Comment by pkarman** [comment]
If you can duplicate that use case (multiple Stripe customers for same email address, days apart) I would be very interested in the exact steps to reproduce. IME, this was only happening on initial sign-up.

**Comment by tarakieffer** [comment]
I completed the sign up form again.
![screen shot 2015-08-05 at 8 33 51 am](https://cloud.githubusercontent.com/assets/9256525/9086857/c069d280-3b4c-11e5-9442-f8ed43fdef59.png)

Also, not a necessarily a duplicate, but stripe accounts are getting created even when the sign up form is incomplete
-For the community plan, entering just the email address (tarakieffer612+popup15@gmail.com -cus_6jvspbSRreVKsW)
-For a paid plan, entering CC and email address (tarakieffer612+popup16@gmail.com - cus_6jvw5giF88sTqZ)
-Entering Name and Password (TaraK - cus_6jw0WjukUrTqoN)

**Comment by pkarman** [comment]
ok that's helpful, thanks. I've pushed a couple fixes to prevent Stripe customers from being created unless the User object looks complete.

**Comment by tarakieffer** [comment]
Stripe account not creating until all details are completed for sign up.

Stripe account not created when completing sign up form with duplicate email address.
