### ISSUE TITLE
Search results page: make facets collapsable, option to show more than 10

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#526]
On both collection page and search results partial.

**Comment by Saltzshaker** [comment]
collapse existing. mixpanel event on initial expand.
-how many more would there me if we showed all of them? what fields are people clicking? which people?
-add "show 10 more" button and see who clicks on it in Mixpanel

**Comment by baileyspace** [comment]
"Facets are deprecated and will be removed in a future release. You are encouraged to migrate to aggregations instead."
http://www.elastic.co/guide/en/elasticsearch/reference/1.x/search-aggregations.html

**Comment by tarakieffer** [comment]
1. Should 'Show 10 more' display even when there is not 10 more to show? Items can belong to only one collection, right?

![screen shot 2015-05-04 at 3 06 34 pm](https://cloud.githubusercontent.com/assets/9256525/7461390/765d0eee-f26f-11e4-92eb-7e53517190a2.png)

2. Clicking 'Show 10 more' refreshes the page or looks like nothing is happening.  

In mixpanel, '10 more facets' increments when 'Show 10 more' is clicked and 'Facet expand' is incrementing when facet header is clicked.

**Comment by baileyspace** [comment]
We're tracking to see if users are interested in this feature, so it's not
yet active. I'll add a little alert to make that clear.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-05-04 13:13 GMT-07:00 Tara Kieffer <notifications@github.com>:
