### ISSUE TITLE
Update detect_derivatives_task and related logic to copy files to S3

### ISSUE THREAD

**Issue by zealoushacker** [popuparchive/pop-up-archive#556]
### Current: when a new audio file is created, we are done:

* After an `AudioFile` is created, `AudioFile#process_file` is invoked
* `AudioFile#transcode_audio` is invoked as the last step of the above invocation
* When the file is marked for storage on IA (`storage.automatic_transcode?` returns true at [app/models/audio_file.rb#L212](https://github.com/PRX/pop-up-archive/blob/master/app/models/audio_file.rb#L212)), `AudioFile#start_detect_derivative_job` is invoked
* The above, in turn makes a new `Tasks::DetectDerivativesTask.new(identifier: 'detect_derivatives')`
* The task is added to the `self.tasks` relation

### Proposed: copying files to S3 after audio file is created and detect derivatives completes

Based on a couple of conversations with @baileyspace and based on her discussions with @kookster and his suggestions, after I had opened #532, here's what I think we can do:

* Write a new `Tasks::CopyToS3Task`, which would be spawned by `Tasks::DetectDerivativesTask` 
* The above task would be spawned from `DetectDerivativesTask#finish_if_all_detected` after `complete?` is true
* `Tasks::CopyToS3Task` would in turn spawn off a worker `CopyFilesToS3Worker`, which would be responsible for actually copying the files from IA to S3. 
Note: This would create a sort of dependency between the two tasks. I am not sure if this is ideal... 

### Questions for @baileyspace and/or @kookster :

Firstly, what do you think of the above approach? My first concern would be creating a dependency between the tasks, but I don't think that's a huge issue... just checking?

Where in the JS codebase do we poll an `AudioFile`'s tasks and their completion to allow the user to play back the file? Is there some sort of progress indicator?

Or do we not poll, and if a user attempts to play back a file that isn't there, it just fails gracefully?

**Comment by pkarman** [comment]
Looking at this now, a year later, what makes the most sense to me is to simply stop firing the DetectDerivatives task altogether, and instead simply transcode everything ourselves.

**Comment by pkarman** [comment]
nm. the way storage works vis-a-vis fixer, fixer would write the transcoded files to IA anyway. original plan here is best.

**Comment by pkarman** [comment]
testing strategy:

* upload a new audio file to a collection with IA storage
* once transcript is complete, verify that MP3 file URL points at S3, not IA

**Comment by tarakieffer** [comment]
Confirmed with @pkarman's assistance.
