### ISSUE TITLE
Batch edit has 'chris, Nan' as label for one of the date groups

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#703]
On Batch Edit: https://stage.popuparchive.com/collections/edit when sorted by date, one of the groupings is displaying as 'chris, NaN'  What does this mean?

![screen shot 2014-11-06 at 9 43 58 pm](https://cloud.githubusercontent.com/assets/9256525/4948122/21a9b134-65fe-11e4-92b2-a346d3f6bbff.png)

I see this in production as well.
![screen shot 2014-11-06 at 9 46 52 pm](https://cloud.githubusercontent.com/assets/9256525/4948145/7ffdbd0c-65fe-11e4-9971-4eecb6df1905.png)

**Comment by pkarman** [comment]
Yes, it did have something to do with Chris.

Happened to find this while looking for something else. Fixed in 93ea29f for dolly.

**Comment by tarakieffer** [comment]
In reviewing the accounts I have set up in stage, all have dates.  Perhaps I have deleted all the files that had no unknown date.
