### ISSUE TITLE
upgrade to Rails 4

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#707]
We have an increasing number of Rails 3 dependencies (gems) with security patches available. That will only increase over time. Better to bite the bullet and upgrade to Rails 4 sooner than later, and get ahead on the patch curve.

**Comment by pkarman** [comment]
http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0

**Comment by pkarman** [comment]
running *bundle upgrade* will now completely break the app, because there are upstream dependencies that now require Rails 4.

**Comment by pkarman** [comment]
this is all about regression testing for everything in the app: superadmin, normal user workflows, etc.

**Comment by tarakieffer** [comment]
I believe this is looking okay.  All regressions identified have been fixed.  I tested search, uploading/creating audio files/images, some superadmin, editing a transcript, account page, and analytics.
