### ISSUE TITLE
Usage for Community plan?

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#815]
How should the usage be tracked for a community plan?  The plan is 1 hour of processing, so does that mean the user can upload 30 files in a month?  Right now nothing is counting in usage because preview transcripts are not counted.

**Comment by Saltzshaker** [comment]
To-do: Rethink Community plan in general

**Comment by annewootton** [comment]
I think the main question here is: should we let people get 1-min premium transcripts instead of the current basic transcript setup?

**Comment by annewootton** [comment]
And if so, to @tarakieffer's point, we should actually meter/limit usage.

**Comment by annewootton** [comment]
Consensus is to offer premium transcript samples. Should we still call it a "plan" if people aren't getting a reusable benefit? How long should the samples be, and is it for one month or forever?

**Comment by annewootton** [comment]
No more basic transcripts for anyone. One hour total upload limit. We'll transcribe the entire hour (or smaller clips if the user chooses to upload them).

**Comment by baileyspace** [comment]
@annewootton  Do we need to account for grandfathering accounts?

**Comment by annewootton** [comment]
Good call. Seems like there will be users who are on existing community
plans but want to take advantage of the new community plan, and it would be
awkward to require them to sign up with a new email address. Could we
switch them all over to the new plan, where they'll be entitled to one hour
of upload/premium transcript, regardless of what they've already uploaded
through the old community plan? (They should also retain any audio they
already uploaded/basic transcripts they got on the community plan.)
ᐧ

**Comment by baileyspace** [comment]
So that means everyone will be migrated over, no one will remain on the current community plan and therefore no one will get basic transcripts?

**Comment by annewootton** [comment]
I believe so, yes. Unless of course anyone can think of objections or
reasons that is a bad idea.
ᐧ

**Comment by annewootton** [comment]
This is now addressed by the Community Plan milestone, which @baileyspace has taken ownership of.
