### ISSUE TITLE
Users associated with Orgs on Professional plan - should they have the option to choose between Basic and Premium without credit card?

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#823]
Organization is set up with Professional Plan.
User is not the owner and does not have a credit card on file.

Should this user be able to choose at time of upload between Basic and Premium?  Currently the user is not able to.  It defaults to basic transcript type.  I presume because there is logic to not display the choice if there is no credit card on file.  

I am not sure how likely this scenario is to occur and it might be the desired behavior, just thought I would confirm because I could see it going either way.

**Comment by annewootton** [comment]
This shouldn't be an issue going forward because all orgs are getting premium transcripts, so no need for basic/premium option. There's also a separate ticket for handling whether org members can keep uploading after the monthly limit has been reached.
