### ISSUE TITLE
Remove transcript comparison on pricing page

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#837]
Transcript comparison shows outdated speaker id system. Can wait on @baileyspace's second-pass at speaker flow, if these might change more.

**Comment by annewootton** [comment]
Moving this to the Community Plan milestone.

**Comment by Saltzshaker** [comment]
See https://github.com/popuparchive/pop-up-archive/issues/1168

**Comment by tarakieffer** [comment]
Transcript compare no longer displays on pricing page.
![screen shot 2015-08-18 at 1 07 20 pm](https://cloud.githubusercontent.com/assets/9256525/9338435/585df014-45aa-11e5-9a30-352741478a23.png)
