### ISSUE TITLE
original file url must have protocol

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#850]
for feed parser and CSV importer, make sure URLs have explicit protocol (http or https, default to http) since fixer requires one.

https://www.popuparchive.com/superadmin/tasks/298091

w/o this, CopyTask will fail.

**Comment by annewootton** [comment]
Hey @pkarman, how do I check to find a recent item from this feed (http://feeds.feedburner.com/mediatwits?format=xml) that doesn't have an explicit protocol, to see if it's now importing successfully? From what I can tell, all the URLs start with http.

**Comment by annewootton** [comment]
(And seems like they're all importing successfully, i.e. https://www.popuparchive.com/collections/3722/items/29925).

**Comment by annewootton** [comment]
Though we do have some duplicates, probably from an earlier bug that is now fixedm i.e. https://www.popuparchive.com/collections/3722/items/28993 & https://www.popuparchive.com/collections/3722/items/28261. I can open another ticket for that...

**Comment by annewootton** [comment]
Hmm. Any better way to test this?

**Comment by pkarman** [comment]
since there do not seem to be any regressions, I'm inclined to just close this and worry about it if we see any more systemic failures.
