### ISSUE TITLE
Optimize /collections endpoint for site performance

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#851]

**Comment by pkarman** [comment]
fyi: the slowness is due to the 'recent_files' attribute, in particular calculating the status for each one. That scales linearly, since it will fetch 5 most recent for each collection.

**Comment by pkarman** [comment]
first pass in de3a091f1a38244745be86c9ab051e3603a2db6c and 713d1e39fc9d1fa4b8ded4fa5c5803da093d33b1

**Comment by pkarman** [comment]
the optimize-endpoints branch has this and more.
