### ISSUE TITLE
Feed ingest not catching dupes

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#875]
There are duplicate items in this NPR feed: http://www.npr.org/rss/podcast.php?id=510075 and we aren't catching duplicates (see https://www.popuparchive.com/collections/3246 for evidence).

The relevant code is in models --> feed_pop_up.rb

**Comment by pkarman** [comment]
merged to master in #886

**Comment by pkarman** [comment]
deployed Monday night.

confirmed still a problem as of Sunday night: https://www.popuparchive.com/search?page=1&query=%22Experts%20Weigh%20In%20on%20the%20State%20of%20State%22

will test again once that particular RSS feed has new content.

**Comment by pkarman** [comment]
this appears to be fixed now. Only one entry created for
https://www.popuparchive.com/search?page=1&query=%22Is%20the%20Tech%20Boom%20the%20New%20Gold%20Rush%22

but there are at least 2 items in the feed of that title.
