### ISSUE TITLE
register our oembed service with embed.ly

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#880]
http://embed.ly/providers/new

**Comment by baileyspace** [comment]
See https://github.com/popuparchive/audiosear.ch/issues/474

**Comment by baileyspace** [comment]
Put a ticket in with Prerender

**Comment by baileyspace** [comment]
This should be up and running. @Saltzshaker try embedding this to see if it's working. You can also test to see if a particular url is working using http://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fwww.popuparchive.com%2Fplayer%2F48019

**Comment by Saltzshaker** [comment]
Not working with the url or iFrame code. No clear answer from googling. @baileyspace, do you think you could email and ask the person you've been talking to at embed.ly what they know about wordpress.com integration?

**Comment by annewootton** [comment]
Embedly embed codes don't work with Wordpress.com hosted sites. Emily is looking into moving our Wordpress.com-hosted blog over to our own hosted install (#1284).

**Comment by Saltzshaker** [comment]
@baileyspace I have the Embedly plugin set up on WordPress, and other embeds from sites like The New York Times work, but ours still isn't showing up. I tried out the link in the validator, and it looks right to me. Any thoughts/ideas? http://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fwww.popuparchive.com%2Ftplayer%2F48972

**Comment by baileyspace** [comment]
Should be 'player' instead  'tplayer'

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-10-28 14:41 GMT-07:00 Emily Saltz <notifications@github.com>:

**Comment by Saltzshaker** [comment]
Aha. Now a card is showing up, but there's no transcript: http://blog.popuparchive.com/?p=438
