### ISSUE TITLE
Loading mask doesn't go away after uploading a file.

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#898]
Testing #884 

Uploading from a file from the My Collection page or the Collection page itself, loading mask continues to display even when the upload is complete.

![screen shot 2014-12-20 at 9 48 09 am](https://cloud.githubusercontent.com/assets/9256525/5515406/954e0f5c-882e-11e4-83e8-b3b699a79d7a.png)

**Comment by shindostrz** [comment]
This bug seems to have disappeared without any direct intervention.

**Comment by tarakieffer** [comment]
I am no longer seeing this issue in the #884 branch.
