### ISSUE TITLE
Not able to upload after reaching monthly limit.

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#900]
Plan FAQs indicate pay-as-you-go should be available after reaching the limit.  Currently, when trying to upload an audio item a message displays 'You are over your monthly limit' with no option to choose pay as you go.

![screen shot 2014-12-22 at 12 24 39 pm](https://cloud.githubusercontent.com/assets/9256525/5529082/8a210dc0-89d5-11e4-96da-360f203b1431.png)

**Comment by annewootton** [comment]
Solution: allow users over their limit to upload additional hours, with large warning that they will be charged $22/hr for all audio in excess of their limit.

**Comment by Saltzshaker** [comment]
Something like this, on both upload forms:
![screen shot 2015-01-12 at 4 20 34 pm](https://cloud.githubusercontent.com/assets/8497203/5714009/c62e2962-9a77-11e4-8d34-6f4508f59c4d.png)
![screen shot 2015-01-12 at 4 25 33 pm](https://cloud.githubusercontent.com/assets/8497203/5714010/c62eee60-9a77-11e4-99e4-960b122da408.png)

**Comment by pkarman** [comment]
let me know when you would like this in stage

**Comment by tarakieffer** [comment]
The 'Create an Audio item' is a little understated compared to warning mocked up above.  

![screen shot 2015-01-22 at 9 48 48 am](https://cloud.githubusercontent.com/assets/9256525/5859239/7c459296-a21e-11e4-9ef3-fa0fa89b0428.png)

If this is acceptable, then I think this is ready for production.  

This is the Upload form message.
![screen shot 2015-01-22 at 6 05 20 am](https://cloud.githubusercontent.com/assets/9256525/5859298/012d55de-a21f-11e4-93f0-94ba0bc77a0f.png)

Messages display when limit is reached.  Tested with a Premium Professional user (1 premium hour/month) and a Professional user (5 basic hour/month) for the message after limit.  Tested with Small Business and Organization user for regression tests before monthly limit is reached.

**Comment by tarakieffer** [comment]
message updated

![screen shot 2015-01-22 at 1 39 47 pm](https://cloud.githubusercontent.com/assets/9256525/5863692/0bbd14fe-a241-11e4-831e-7e2156b4f59f.png)
