### ISSUE TITLE
Not able to edit items after monthly limit has been reached

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#901]
Makes sense to prevent a user to not be able to upload additional files to an existing item, but shouldn't they be able to edit the data related to the item?

![screen shot 2014-12-22 at 12 25 50 pm](https://cloud.githubusercontent.com/assets/9256525/5529096/b1f61aa2-89d5-11e4-9424-49e9e07e9d6e.png)

**Comment by annewootton** [comment]
Escalating this because we heard from Jack Brighton/Illinois Public Media and they're stymied by it.

**Comment by pkarman** [comment]
I have a fix in a local branch and will push to stage after june branch is merged to master tomorrow.

**Comment by pkarman** [comment]
@tarakieffer let me know when you are ready to test this and we can mock up the necessary data.

**Comment by tarakieffer** [comment]
I am able to edit the item when over a limit.

But the message when I tried to upload is blank.  
![screen shot 2015-04-28 at 11 41 47 am](https://cloud.githubusercontent.com/assets/9256525/7375061/b2c56044-ed9b-11e4-807a-f5ce30d22026.png)

**Comment by pkarman** [comment]
fix pushed to stage.

**Comment by tarakieffer** [comment]
![screen shot 2015-04-29 at 8 07 31 am](https://cloud.githubusercontent.com/assets/9256525/7391588/f4c44fe4-ee47-11e4-88ce-320662d81a3f.png)

This is the message/form displaying now when trying to upload.

**Comment by pkarman** [comment]
fix deploying now to stage.

**Comment by annewootton** [comment]
Users who have uploaded their limit on the free 1hr plan are not able to edit items.

This is a problem for users who have also been on paid plans, then downgraded, and are no longer able to edit transcripts they paid for.

**Comment by AndersEverett** [comment]
Transcript editing is available to those over limit by clicking on item title blue link from /collections. General item editing is not available from top edit button on /collections/col_id/items/item_id, so focusing on that fix.

**Comment by AndersEverett** [comment]
Added a separate div to separate uploads from editing in angular for users over their limit.

**Comment by tarakieffer** [comment]
Confirmed I am able to edit transcripts when I am over the limit.
![screen shot 2015-10-30 at 10 51 21 pm](https://cloud.githubusercontent.com/assets/9256525/10861732/51424102-7f59-11e5-8b70-c5ff86f26fd2.png)

I am not able to edit the item details.  I am getting an over the limit message. 
![screen shot 2015-10-30 at 10 51 28 pm](https://cloud.githubusercontent.com/assets/9256525/10861733/56e5e064-7f59-11e5-8b64-54ea04193e6f.png)

**Comment by baileyspace** [comment]
Needed to redeploy. Should be ready to go now.

**Comment by tarakieffer** [comment]
Almost.  I am seeing the fields that can be edited, but I don't have a 'Save' button.  When I click 'Close' and re-open, it looks like my changes have been saved.  Then when I refresh the page, my changes do not display on the item.

![screen shot 2015-11-02 at 9 20 38 pm](https://cloud.githubusercontent.com/assets/9256525/10900603/c3166c68-81a7-11e5-8b30-04142a5a2d82.png)

**Comment by AndersEverett** [comment]
@tarakieffer Let me know if you get error redirects with this fix when you save edits as a user in staging. I was getting them, but they existed both before and after the fix (with users not over their limit), so I'm hoping it's an environment issue.

**Comment by tarakieffer** [comment]
I am able to edit the item now when over limit and edit persists.
