### ISSUE TITLE
Saving a edit to an item, page reloads with 404 message

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#902]
Signed in as tarakieffer612@gmail.com.  Editing an existing item in production, I get 404 error after saving.

1) From item page, click 'Edit Item'
2) Modify a field (for example, add tag)
3) Click 'Save'

Page reloads with 404 error.  Reloading page, the item page does display with edit saved.

![screen shot 2014-12-22 at 2 39 54 pm](https://cloud.githubusercontent.com/assets/9256525/5530698/97326f8c-89e8-11e4-8562-08ee3445f569.png)

**Comment by pkarman** [comment]
I am not able to duplicate this. As it's been a month, it may have been "fixed" -- @tarakieffer can you confirm this is still an issue?

**Comment by tarakieffer** [comment]
I now seem to be getting this only when changing the collection the item is in.

**Comment by tarakieffer** [comment]
Tested in Tammy branch - Item page displays without error and in the expected collection after editting an item to change the collection
