### ISSUE TITLE
Lag time in transcript editor

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#904]
Multiple customers (e.g. Grace from Studs Terkel, Madeleine from CCPOH) have said that the delay while moving around the transcript editor, as well as typing and seeing what you've typed, is the single biggest thing preventing them from using the editor. 

In the example above, I remember they were using up-to-date Chrome and Safari browsers, so not sure what the problem is. Maybe we could have @tarakieffer test out performance in different ways? Any thoughts, @baileyspace @pkarman

**Comment by tarakieffer** [comment]
Some quick tests show @pkarman is on to something with the duration being a factor.  8-10 minute duration seem to be fairly smooth.  The one I tried with a duration of about 80 minutes had a noticeable delay.  This was in stage and with both Chrome and Firefox.  I will do a little more testing with Firebug at report back what I find, just thought I would give a quick status.

**Comment by tarakieffer** [comment]
Screenshots below for clicking 'Edit Text' then using arrows to move up and/or down between the lines

32 min file
![screen shot 2015-02-04 at 5 53 03 pm](https://cloud.githubusercontent.com/assets/9256525/6052337/4c44b67a-ac97-11e4-9f05-6032dc1a8f79.png)

80 min file
![screen shot 2015-02-04 at 5 56 39 pm](https://cloud.githubusercontent.com/assets/9256525/6052345/6c422444-ac97-11e4-9da7-06b6f9c0206f.png)

Also when moving from line to line the loading mask displays. Keyboard inputs still seem to be accepted while the mask displays, but the loading mask probably does not encourage this.

**Comment by baileyspace** [comment]
@shindostrz take a look at this. We should avoid displaying the edit mask during transcript editing.
