### ISSUE TITLE
Remove duplicates from feed collections

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#906]
KQED Forum is one:
https://www.popuparchive.com/search?page=1&query=%22Experts%20Weigh%20In%20on%20the%20State%20of%20State%22

Also Mediatwits:
https://www.popuparchive.com/collections/3722/items/28993 https://www.popuparchive.com/collections/3722/items/28261

**Comment by pkarman** [comment]
is this purely a data cleanup issue? or is there still a dupe problem in the code?

**Comment by annewootton** [comment]
Just data cleanup. We need to remove duplicates and flag duplicates billing = false so they don't count toward KQED's total.

**Comment by pkarman** [comment]
I have identified by 2400+ duplicate items, with identical collection, title and date_broadcast values.

Do we have collections originating from feeds flagged somehow?

Should I be removing all duplicates, regardless of whether they originated in a feed?

I can provide a list if that is helpful.

**Comment by annewootton** [comment]
Yes, a list would be very helpful! That seems like a lot.

Collections originating from feeds are not flagged but are listed in the
Heroku scheduler...

**Comment by pkarman** [comment]
@annewootton list sent via email

**Comment by annewootton** [comment]
Looked over the list, thanks. If possible, it seems like a good place to start would be removing all duplicates that originated from a feed. Could we check to see if the item has a premium transcript, and if not, delete it?

**Comment by pkarman** [comment]
Are those 2 statements connected? I.e. the way of identifying that an Item originated from a feed is that it does not have a premium transcript?

**Comment by annewootton** [comment]
Unfortunately, no. If there's no way to determine which items came from a feed, then I would default to the second statement: delete all duplicates as long as they don't have premium transcripts (it seems unlikely that we'll have any duplicate items where both items got premium transcripts, but let's cross our fingers and find out). From looking over the list you sent, it's mostly feeds.

**Comment by pkarman** [comment]
for future reference, the only way I have found to get all the jobs from the Heroku scheduler is to login via the web site, and then save the page locally, and run something like this:

```
grep on-edit Heroku\ Scheduler.html | grep command | grep rake | perl -n -e 'm/\"(rake .+?)\"/; print $1,$/'
```

**Comment by pkarman** [comment]
limiting the collections to those originating with feeds trims the dupes down to <2k.

for the record, here's the list of collection ids

```
438
799
676
800
801
810
810
1573
1574
1575
1586
1587
1588
1654
1596
1705
1633
1653
1655
1656
1657
1686
1687
1703
1754
1780
1781
1782
1785
1868
1928
1975
2082
2088
2064
2594
3246
3247
3653
3722
3758
1673
4239
3626
4258
4261
4262
4263
4264
4265
4266
2347
```

**Comment by annewootton** [comment]
I've gone through all of these collections. I'm fine to delete the duplicates and favor premium transcripts. 

NB: If there are multiple premium transcripts, or no premium transcripts, can we favor the older item? (There are a few of these collections — 1633, 1703, 1754, 1785, 1975, 4239 — where the owner has edited some transcripts for the older items.)

Also, I see no record of collection 3758. Also, I noticed in this list you included 438 but not in the list you emailed — just a heads up.

**Comment by pkarman** [comment]
I see these items from collection 438 as duplicates in the list I emailed:
```
Dupe: From The Vault, Fri, December 06, 2013:438:2013-12-06 {:count=>2, :ids=>[7245, 7247]}
Dupe: From The Vault, Mon, December 09, 2013:438:2013-12-09 {:count=>2, :ids=>[7338, 7339]}
Dupe: From The Vault, Fri, December 20, 2013:438:2013-12-20 {:count=>2, :ids=>[7405, 7406]}
Dupe: From The Vault, Wed, August 20, 2014:438:2014-08-20 {:count=>5, :ids=>[20687, 20688, 20689, 20690, 20691]}
Dupe: From The Vault, Fri, September 26, 2014:438:2014-09-26 {:count=>2, :ids=>[22704, 23355]}
Dupe: From The Vault, Fri, October 10, 2014:438:2014-10-10 {:count=>3, :ids=>[24612, 24613, 24614]}
Dupe: From The Vault, Fri, January 02, 2015:438:2015-01-02 {:count=>2, :ids=>[30132, 30914]}
Dupe: From The Vault, Fri, January 16, 2015:438:2015-01-16 {:count=>2, :ids=>[31680, 31681]}
```

Collection 3758 apparently has no duplicates in it.

**Comment by pkarman** [comment]
I will go ahead and add logic to prefer the oldest premium transcript, and run it against a recent db snapshot. Assuming there are no problems, I will then run it in production.

**Comment by pkarman** [comment]
run against local snapshot finished with 2591 deletions. I will plan to run this against production on Saturday night, so that the Sunday index rebuild gets all the changes.

**Comment by annewootton** [comment]
Just making sure: this will save the oldest premium transcripts and, in
absence of premium transcripts, oldest basic transcript?

Thanks!

**Comment by pkarman** [comment]
yes. will keep oldest premium or oldest basic.

**Comment by pkarman** [comment]
2774 duplicate items have been soft-deleted.

It took a few tries to finish the task because of redis timeouts in the production environment (probably because there are IndexerWorker tasks created for every delete) so it overlapped with the weekly index rebuild. I therefore ran a manual rebuild of the index to catch any stragglers.
