### ISSUE TITLE
Change logos on homepage/user stories

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#912]
Currently: KCRW, Hoover, WFMT, StoryCorps, KALW, KQED, Pacifica Radio Archives, Princeton Theological Seminary, Center for Investigative Reporting, CUNY, Illinois Public Media

Should be: KCRW, Hoover, WFMT, StoryCorps, KQED, CUNY, CBC, Radiotopia, Center for Investigative Reporting, GW University, Snap Judgment?

**Comment by pkarman** [comment]
already in master.
