### ISSUE TITLE
Owner of organization displays as member

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#917]
Owner for Tara Test Org is Peter Karman
![screen shot 2015-01-09 at 1 50 15 pm](https://cloud.githubusercontent.com/assets/9256525/5686203/a74b3508-9806-11e4-8f95-8b4f3b6ef94b.png)

But on the organization page displays merely as member - https://stage.popuparchive.com/organization
![screen shot 2015-01-09 at 1 50 34 pm](https://cloud.githubusercontent.com/assets/9256525/5686218/c6238d22-9806-11e4-96ce-74569c4697dc.png)

**Comment by pkarman** [comment]
fix in #914

**Comment by tarakieffer** [comment]
Displaying as expected. 

![screen shot 2015-01-13 at 3 51 17 pm](https://cloud.githubusercontent.com/assets/9256525/5729948/0aeca6ea-9b3c-11e4-9f65-ba6c06185b28.png)
