### ISSUE TITLE
OpenGraph data missing for certain items?

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#923]
From customer (Wisconsin Historical Society):

Here is a screen shot of the share that does not include the open graph content.  This is on the page with the Premium Transcript, located here: https://www.popuparchive.com/collections/4166/items/22583.
![image005](https://cloud.githubusercontent.com/assets/1718286/5731402/bd3f8736-9b37-11e4-8f64-c8879d571d69.jpg)

Interesting thing is that the other interviews display fine:
![image006](https://cloud.githubusercontent.com/assets/1718286/5731403/c199efec-9b37-11e4-89f2-518f7e2b563a.jpg)

**Comment by shindostrz** [comment]
That item is private so there wouldn't be any open graph data generated by Prerender. The mystery is why the Facebook share button is showing up at all since it shouldn't for private items.

**Comment by annewootton** [comment]
Weird! That item looks like it used to be private and was moved into a public collection. Opening separate ticket for that.
