### ISSUE TITLE
Phantom item remains after deletion through UI

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#929]
https://www.popuparchive.com/collections/4052/items/31560

(Didn't unindex it intentionally, but happy to.)

**Comment by pkarman** [comment]
that URL is 404 because it is flagged as deleted in the database.

Was their a particular search URL that turned it up?

**Comment by annewootton** [comment]
No, it was deleted but still shows on the collection page https://www.popuparchive.com/collections/4052 (without play button).

**Comment by pkarman** [comment]
I could not reproduce (deleting an Item always seems to fire a corresponding IndexerWorker) so I have just manually removed from index

```
> IndexerWorker.perform_async(:delete, 'Item', 31560)
```

Now that we have the ability to build indexes in the background w/o service interruption, I think we should enable a regular (daily? weekly?) cron to catch issues like this.

**Comment by baileyspace** [comment]
Agreed. How about we start with weekly?

**Comment by pkarman** [comment]
I have enabled it for Sunday mornings at midnight.

**Comment by pkarman** [comment]
the index completed successfully. took 8 hours.
