### ISSUE TITLE
allow for entry of remote URLs into collection Add Item

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#931]
In addition to uploading local audio files, it would be helpful if users could paste in a URL instead. This would be a one-off version of what the CSV import currently does.

**Comment by kookster** [comment]
wait, didn't that already get added? maybe that was just image files...

**Comment by pkarman** [comment]
yes it was just image files.

**Comment by tarakieffer** [comment]
Adding item from URL is available through the upload form -
![screen shot 2015-01-23 at 7 17 18 am](https://cloud.githubusercontent.com/assets/9256525/5875180/f7636910-a2cf-11e4-8f9b-3b5ca411c87c.png)

After uploading one file, the url stays populated the next time the form is opened.  @pkarman Can this be removed?


Edit item screen no longer has the "Add Files to Item" option.  Has this been intentionally removed with this enhancement?
![screen shot 2015-01-23 at 7 27 21 am](https://cloud.githubusercontent.com/assets/9256525/5875302/505b5fa4-a2d1-11e4-9e3b-983960e757c0.png)

Also, after clicking 'Save' button, there is no indicator it is actually being saved.  I am returned to the My Collections page or collection page without the item in the list until I refresh the page.

**Comment by tarakieffer** [comment]
Three items in the previous comment have all been addressed.

1) URL doesn't stay in form
2) 'Add files to item' is back.  Files can be added locally.  #949 has been logged to add the ability to enter a URL
3) Page refreshes after clicking 'Save'

I am not seeing any other issues.  I think this is ready for production.

**Comment by pkarman** [comment]
merged and pushed
