### ISSUE TITLE
Item moved from private to public collection not displaying

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#932]
Other public items created in collection 4166 are displaying. This item is not: https://www.popuparchive.com/collections/4166/items/22583. Additional context (note the is_public flag is set to false):
```
#<Item id: 22583, title: "Rubie Bond Interview, February 18, 1976", episode_title: nil, series_title: "Beloit Bicentennial Oral History Project Interviews...", description: "<p>Interview of Rubie Bond by Clem Imhoff, February...", identifier: "637A/1", date_broadcast: nil, date_created: "1976-02-18", rights: nil, physical_format: nil, digital_format: "WAV", physical_location: "Wisconsin Historical Society, Sound Archives", digital_location: nil, duration: nil, music_sound_used: nil, date_peg: nil, notes: nil, transcription: nil, tags: ["Beloit", "Wisconsin", "Wisconsin Historical Society", "African-American History", "Oral History", "Beloit College", "Mississippi"], geolocation_id: nil, extra: {}, created_at: "2014-09-19 16:57:42", updated_at: "2015-01-13 16:48:16", csv_import_id: nil, collection_id: 4166, token: "sadie-bell-interview.sbBlKX.popuparchive.org", storage_id: nil, is_public: false, language: "en-US", deleted_at: nil, image: nil, transcript_type: "basic">
```
(And thus has broken OpenGraph data for social sharing.)

**Comment by annewootton** [comment]
@Saltzshaker noticed that when she's logged in (even if she doesn't have access to collection 4166) she can see this item.

It's only when users are not logged in that they cannot see this item (even though the collection and the rest of its items are public.)

Hey @pkarman, any ideas? Customer amazingly noticed and is asking about it. Also, I learned that the is_public flag is actually a method and just checks the visibility of the collection... which is public.

**Comment by pkarman** [comment]
in the short term I would just reindex that time.

in the longer term, there seems to be a bug where changing the flag on the collection does not trigger re-indexing of all its child items.

**Comment by annewootton** [comment]
Hmm, just reindexed but no one can see this item when they're logged out... can you? https://www.popuparchive.com/collections/4166/items/22583

**Comment by pkarman** [comment]
I cannot view it anonymously. That is as it should be.

Item.is_public is a column on the Item table, not simply a method that calls through to the parent Collection. That particular Item has is_public set to false.

Here's what I did just now:

```
irb(main):001:0> item = Item.find 22583
irb(main):002:0> item.is_public
=> false
irb(main):006:0> item.is_public = true
=> true
irb(main):008:0> item.save!

```

Now it is visible.

**Comment by annewootton** [comment]
Thanks! I guess what we meant about the is_public flag was that it gets set by the collection setting... and perhaps is not updating when an item gets moved between collections. Which is not as it should be as far as the user is concerned...

**Comment by pkarman** [comment]
Individual items can be flagged as public/private, separately from their parent collection. Should changing the parent collection of an item always automatically override whatever the item's is_public flag is set to?

Are we making it easy enough to toggle public/private on a per-item basis?

**Comment by pkarman** [comment]
looping in @baileyspace @Saltzshaker for some UX feedback.

**Comment by baileyspace** [comment]
I think it makes the most sense to inherit the item privacy setting from
the collection-level. Otherwise, you could have private collections
containing public items, which I find confusing.

An alternative would be to remove the privacy setting from the collection
level entirely and force the user to make all privacy decisions at an item
level.

I think we modeled this after Flickr, but as Flickr has recently made it
impossible to sign in, I can't be sure.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-01-22 10:45 GMT-08:00 Peter Karman <notifications@github.com>:

**Comment by Saltzshaker** [comment]
I like the collection model. Agree that allowing privacy changes at the item level gets confusing, and would force us to rethink some things. 

To me it makes the most sense to just let users change the collection privacy setting after creation. (There was just a CBC guy who asked to be able to make his public collection private, in fact.) 

This would be in addition to being able to move items between collections, as users currently can. 

Emily

Emily Saltz / @saltzshaker
c: (323)-896-0860
emily@popuparchive.com
Pop Up Archive / popuparchive.com

**Comment by Saltzshaker** [comment]
> Individual items can be flagged as public/private, separately from their parent collection. Should changing the parent collection of an item always automatically override whatever the item's is_public flag is set to?

I think yes.

> Are we making it easy enough to toggle public/private on a per-item basis?

One thing we could do is make it more clear from the item page what is public or private. It could be clickable, and say “Item belongs to X Private Collection. Edit Item to another collection." (Right now the only place you see it is on the my collections page ribbon, and I’ve seen people get confused and not spot it at first.) 


Emily Saltz / @saltzshaker
c: (323)-896-0860
emily@popuparchive.com
Pop Up Archive / popuparchive.com

**Comment by annewootton** [comment]
One thing to keep in mind, that Bailey/Andrew/I talked about a lot when we
first set this up, is that if you want to enable people to change the
privacy setting of an entire collection, it has implications for archive.org
storage.

What if someone changes a public archive.org collection to be private? What
happens to those items?

I'm comfortable limiting privacy changes to moving items between
collections. No individual public/private flag for items separate from
their collection, and no changing privacy settings of collections once
they're created. (In that scenario, the user could create a new collection
with desired privacy setting and move the needed items. That's what we
created Batch Edit for... womp womp.)
ᐧ

**Comment by pkarman** [comment]
To minimize db schema churn, I'm going to put a before_save hook on Item to always set is_public based on the parent Collection. Then I'll create a rake task to iterate through all items and make sure the flag is set correctly.

**Comment by pkarman** [comment]
The item.handle_collection_change method already takes some pains to do this (set is_public based on parent collection). The exceptions are for storage differences.

So I'm not sure there is anything to do, except write more tests and see if any of them can fail.
