### ISSUE TITLE
Playback issues for audio items from search results/collection listing

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#934]
From customer:

This issue does not appear when the individual item record is viewed, only from the results list.  From the results list, clicking on the play button opens the player at the bottom of the page but the audio never plays.  However, audio items from other collections play correctly. Examples where we see the issue:
 
https://www.popuparchive.com/collections/2458   This is our collection.  Clicking on the play button for any of these items does not play the audio.
 
https://www.popuparchive.com/search?page=1&query=rubie%20bond  This search result includes WHS audio and other audio.  Other audio, lower in the search result, plays fine.  The WHS audio does not play.
 
https://www.popuparchive.com/search?page=1&query=vanderbilt  Similar to above.  This includes WHS audio and other audio.
 
Our testers have been using Chrome and Firefox.  The Rubie Bond upload format was WAV, the Vanderbilt was MP3.

**Comment by pkarman** [comment]
The player seems to be asking for the .wav file, not the .mp3. I would expect the .wav takes a really long time to download and since it does not stream, the player has to wait for the entire download before starting.

The audio has been transcoded. Any idea why the code asks for .wav instead of .mp3 or .ogg?

**Comment by pkarman** [comment]
Could be because the search results use the .wav url.

e.g. https://www.popuparchive.com/api/search?query=collection_id:2458

**Comment by pkarman** [comment]
Is the expectation that a user can play audio immediately after it is uploaded? Or is there an expectation that "some time" passes, so that it can be transcoded if necessary?

**Comment by pkarman** [comment]
looping in @baileyspace

**Comment by annewootton** [comment]
Just a thought: sometimes playback issues have to do with the file missing
a transcoded_at value and/or a duration. This file seems to have a
transcoded_at value but no duration?
ᐧ

**Comment by annewootton** [comment]
I think we play the audio from the "original" (i.e. WAV) uploaded location
until the transcoding (if necessary) finishes. Not sure what the
trigger/indicator for that is.

ᐧ

**Comment by pkarman** [comment]
d39831b6c3a2062f9f09506384d5543f667565f9 should fix this. merged to master. requires deploy and re-index.

**Comment by annewootton** [comment]
Let me know when this is deployed/re-indexed so I can alert the customer — thanks!

**Comment by pkarman** [comment]
ok. I plan to do that tonight.

**Comment by pkarman** [comment]
deployed.
