### ISSUE TITLE
Storage as a meter on account page not useful?

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#939]
Is there an upper limit for storage or is billing just based on processing time?  

This is a screenshot of an account page for a user with no uploads for the current month.  The storage indicates they are over the 5 hour/month limit.  

![screen shot 2015-01-20 at 2 01 32 pm](https://cloud.githubusercontent.com/assets/9256525/5855464/1f88c8c2-a1fe-11e4-85c7-0c268f4cb825.png)

Either the meter should be reset or the meter no longer applies because of the enhancements to track the processing of the transcripts.

**Comment by pkarman** [comment]
I reworked that page to emphasize storage is cumulative, not against a monthly plan. It's mostly an FYI for the customer.

**Comment by tarakieffer** [comment]
Meter is now on usage - under limit example

![screen shot 2015-01-22 at 2 28 17 pm](https://cloud.githubusercontent.com/assets/9256525/5863995/b37deec8-a243-11e4-8aa6-a4e31940a771.png)

Over limit example
![screen shot 2015-01-22 at 2 19 40 pm](https://cloud.githubusercontent.com/assets/9256525/5863987/a5be350e-a243-11e4-8399-ac40cc6888cc.png)
