### ISSUE TITLE
Total cost and monthly premium cost not in agreement

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#940]
This is from the account user Ashley (1461)

She has the Premium Professional plan (1 hr/month).  The total cost seems like it is accurate for $22 for each hour of overage.  However, the monthly cost is only $1.59.

![screen shot 2015-01-22 at 9 31 02 am](https://cloud.githubusercontent.com/assets/9256525/5858565/c8fd414c-a219-11e4-9025-f3594bb58a86.png)

Frederick (1451) user with the old Professional plan (5 basic hr/month) does not seem to have the same issue.
![screen shot 2015-01-22 at 9 42 24 am](https://cloud.githubusercontent.com/assets/9256525/5858805/99820040-a21b-11e4-9cb8-18ef549cb763.png)

**Comment by pkarman** [comment]
this was an edge case. The Ashley user switched plans mid-month, and the 1.59 amount was an on-demand charge for premium transcript while under a basic plan.

The actual overage was 47.48

When you add 47.48 and 1.59 you get 49.07 (the overall total).

I have changed the calculator to avoid double-billing for ondemand and overage transcripts. Overage will take precedence.

**Comment by tarakieffer** [comment]
Not double charging for the premium on demand.

![screen shot 2015-01-22 at 2 36 57 pm](https://cloud.githubusercontent.com/assets/9256525/5864057/28ff3882-a244-11e4-9293-8262b64f598d.png)

**Comment by annewootton** [comment]
Cool. Based on this, at the end of January would we charge this customer
$1.59 + $51.81?

ᐧ

**Comment by pkarman** [comment]
No, $51.81.

That's the fix: the total now shows the actual total, with no mental math necessary.

**Comment by annewootton** [comment]
Gotcha. Might be helpful to add the words (or break out numbers for both) "overage charge" and "on-demand charge." If I were this customer, I'd be confused about the relationship between $1.59 and $51.81, or why my 2015-01 history doesn't explain where the total charges in excess of that $1.59 come from. Does that make sense?

**Comment by pkarman** [comment]
yes, the small amount on the monthly detail is misleading, I agree. I've added some explanatory text to the overall total when there is an overage, to describe the math involved. I think #942 will further help.

**Comment by annewootton** [comment]
Great. Per-file details will definitely help, too. Thanks.
ᐧ

**Comment by tarakieffer** [comment]
This is what I am seeing now.
![screen shot 2015-01-22 at 3 09 16 pm](https://cloud.githubusercontent.com/assets/9256525/5864563/ab59e076-a248-11e4-9b68-f31753ab45a4.png)

**Comment by annewootton** [comment]
Hmm... so if History never reflects overage charges, can we clarify that
it's only for on-demand charges?

Also, if 2.355 overage hours * $22/hr = $51.81, where is the $1.59 within
that?
ᐧ

**Comment by pkarman** [comment]
The 1.59 is being consciously ignored. Otherwise we bill 2x for the same transcript.

I really think this whole page needs some re-thinking. The chief problem (IMO) is that plans can change mid-month (which is what happened here) and we do not keep a history of the plan changes and apply them to transcripts.

E.g. if a user upgrades from Basic to Premium mid-month, or from Premium 1hour to 5hours, we apply the new plan limits to the existing transcripts for that month. It's retroactive. That's as it should be. We should not penalize customers for upgrading their plans.

However it becomes tricky from a bookkeeping standpoint to show the monthly usage details (as in this case).

**Comment by pkarman** [comment]
I'd vote to not let this particular edge case (upgrade mid-month with exiting ondemand charges) de-rail this PR however. Let's get this released, and then think about how we want to present account details/charges in a later iteration.

**Comment by annewootton** [comment]
Agree about getting this released! Seems like what you've come up with is
the best solution for now.

And now I understand the nuance of tracking mid-month plan changes. I think
the way we apply new plan limits makes sense. Definitely open to rethinking
the page. We could tweak the way we report the usage — as a user (and it's
true, we've been telling people they can upgrade/downgrade at will), I
expect something like:

2015-01 - premium transcripts
Usage: 3.355 hrs / 1 hr
On-demand charges (.072 hrs): $1.59
Overage charges (2.283 hrs): $50.02
Total premium charges (2.355 hrs): $51.81

And get rid of the basic transcript section altogether.

ᐧ
