### ISSUE TITLE
expose more collection fields via UI

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#943]
Should we expose more collection fields via the UI so that users can edit them?

Examples:

* items_visible_by_default
* copy_media

Esp with #931 and #932 it seems like giving edit power to users is important.

**Comment by annewootton** [comment]
I'm not sure about copy_media, particularly as it relates to
https://github.com/popuparchive/pop-up-archive/issues/931. Maybe?

I'm concerned about making items_visible_by_default editable given the
archive.org storage questions raised in
https://github.com/popuparchive/pop-up-archive/issues/932.
ᐧ

**Comment by pkarman** [comment]
understood about items_visible_by_default -- I agree it should be editable at collection creation only (as it is today).

re: copy_media, I think that is set in conjunction with the IA storage option at creation time right now, but in theory it could be set independently, like we are doing for the AS project. Could/should we add that as an separate radio button option at both create and edit time in the UI?

I'm thinking particularly of public media customers should want to host their own audio but also want transcripts and do not want PUA to have a copy of the audio hosted, publicly or privately.

**Comment by pkarman** [comment]
lemme know when you want this pushed to stage.

**Comment by tarakieffer** [comment]
Store Media is available at time of Creating Collection - default is 'Yes'
Store Media is also available when Editing Creation

![screen shot 2015-02-27 at 3 45 23 pm](https://cloud.githubusercontent.com/assets/9256525/6421780/bc3cd374-be97-11e4-94b4-c730521cc4fe.png)
