### ISSUE TITLE
replace/add embed code for tplayer in UI

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#946]
the Embed code currently points at the older jplayer. Let's make it (also) point at the tplayer and reduce the complexity of using the tplayer.

**Comment by pkarman** [comment]
let me know when you'd like this sent to staging

**Comment by tarakieffer** [comment]
![screen shot 2015-01-30 at 1 56 39 pm](https://cloud.githubusercontent.com/assets/9256525/5983381/55df4f32-a892-11e4-8dad-32cedda10cf5.png)

Help Link: https://github.com/popuparchive/pop-up-archive/wiki/Transcript-Player#embed-the-tplayer

both iframe examples on tumblr
![screen shot 2015-01-30 at 3 05 22 pm](https://cloud.githubusercontent.com/assets/9256525/5983387/68971a06-a892-11e4-83b6-5f7f2b4869fa.png)

didn't test embedding oembed, but did confirm correct item id in the code.

opened #971 for embedding the JS version on tumblr
