### ISSUE TITLE
403 authz error for user in org

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#954]
user 688 in org 10

**Comment by pkarman** [comment]
The problematic collection is 1444 (My Uploads) which I discovered by logging in as that user and watching the FF firebug requests for the 403 error.

So the problem is that there is no grant for the personal collection to the parent organization. This will be fixed in the long term by #951 but in the short term I have deleted the collection since it is empty.

**Comment by annewootton** [comment]
Gotcha... and I had the same experience as user 867 with my own My Uploads  collection. I'm confused about why this is happening, since we've been adding users with My Uploads collections to orgs and they haven't been having this experience.

```GET https://www.popuparchive.com/api/collections/1946
403 Forbidden	304ms applica...918d.js (line 306)
GET https://www.popuparchive.com/assets/items/form.html
200 OK	395msapplica...918d.js (line 306)
GET https://www.popuparchive.com/assets/error/403-1f23d364caac8a9c313bcd1cae6722f4.html	
200 OK	778ms```

**Comment by pkarman** [comment]
I'm sure it started happening when the API responses started having 4xx responses instead of just being empty. That was an API change late last fall.

**Comment by annewootton** [comment]
But we've added dozens of people with My Uploads collections to orgs in the past few days, and none of them have had issues.

**Comment by pkarman** [comment]
can you point me at an example of such a User?

**Comment by annewootton** [comment]
Sure, any user on the BBC org (39; i.e. users 1679, 1682) or CBC (32; i.e. users 1613, 1627).

**Comment by pkarman** [comment]
ok the bug seems to be limited in scope to Organizations that do not have a collection granted to them where the collection_grant.uploads_collection is true. BBC and CBC do have such a collection. TAL does not. That seems to be triggered according to the workflow when the org is/was created. It may not affect newer Organizations.

**Comment by annewootton** [comment]
Aha, got it! Weird that orgs have to have an uploads collection grant. I guess just older orgs though. Shouldn't be a big issue going forward.

**Comment by annewootton** [comment]
Also, to confirm: you were able to work around this for organization 10 by deleting the My Uploads collection that belonged to the user in question, correct? I'm having that experience when I delete the My Uploads collection associated to my user — i.e. I can see stuff again. Another fix for this org would be to create a grant to a My Uploads for the org, correct?

**Comment by pkarman** [comment]
correct and correct

**Comment by pkarman** [comment]
this is ready for testing in #958

**Comment by tarakieffer** [comment]
Tested in Tammy branch.  After Ashley was added to the organization Tara Test Org, I was able to sign in as Ashley without error.
