### ISSUE TITLE
Feeds not ingesting for KCRW

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#957]
I've added nine feeds over the past week. Five seem to be working. Four are not (at least not fully; the first one has one item but the feed contains more):
http://feeds.kcrw.com/kcrw/de --> Collection 4263
http://feeds.kcrw.com/kcrw/pp --> Collection 4265
http://feeds.kcrw.com/kcrw/lr --> Collection 4266
http://feeds.kcrw.com/kcrw/ww --> Collection 2347

Let me know if I should be troubleshooting further in a particular direction. These are currently set up as rake tasks (monitor:feed) in Heroku scheduler.

**Comment by annewootton** [comment]
Oh! One more:
http://feeds.kcrw.com/kcrw/bw --> Collection 4264

**Comment by pkarman** [comment]
I suspect the problem was this: 1faa29c840d1829765123b852903b69ffffe48fc

I have deployed the fix and we can check tomorrow.

**Comment by pkarman** [comment]
that appears to have fixed it. I am seeing lots of items in each collection now.
