### ISSUE TITLE
Get rid of "over limit" flickering image

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#960]
Re: Zendesk complaint from Robin at SoundVision org: "I just logged out and back in. Saw a message at the top saying we're over our limit but it quickly went away."

I get this too sometimes. It seems like the "over limit stuff" loads automatically, and then gets checked against account info, when it disappears (or not, if you're actually over your limit). Can we set it to load later?

**Comment by pkarman** [comment]
fixed and deployed

**Comment by Saltzshaker** [comment]
Cool, that was fast!
