### ISSUE TITLE
File won't reprocess as premium

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#962]
This is not urgent. It was uploaded out of good will by someone who wanted to preserve it at the Internet Archive and I offered to comp them a premium transcript since it's MLK audio!

https://www.popuparchive.com/collections/4267/items/31923

Can't tell if Bailey's fix should have helped with this one. The canceled detect_derivatives task seems like a problem though.

**Comment by baileyspace** [comment]
I think I know what's up. On it.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-01-28 17:43 GMT-08:00 annewootton <notifications@github.com>:

**Comment by baileyspace** [comment]
Ok, I think I got it. It's reprocessing now.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-01-28 19:09 GMT-08:00 Bailey Smith <bailey.r.smith@gmail.com>:

**Comment by pkarman** [comment]
it has finished processing.
