### ISSUE TITLE
add CDN in front of S3

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#969]
We need to optimize the playback of our s3 audio content. In particular it would be nice to stream and/or do segments.

Cloudfront is an obvious choice.

**Comment by pkarman** [comment]
regression testing, really. as long as audio keeps playing, we're ok.

note that in stage there might be issues with playing audio that originally was uploaded in the production env, because there are different CDN base URLs per environment.

test should be: upload new audio in stage, verify it can play back.

**Comment by tarakieffer** [comment]
New audio is playing.

**Comment by Saltzshaker** [comment]
@tarakieffer can you test the experience for clicking around transcript lines in playback and edit mode? I've had experiences in the past where the page gets stuck with the loading mask, and want to make sure you don't experience that now
