### ISSUE TITLE
Improve Client side JS player display on tumblr

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#971]
Not sure there is anything to do here, but in case there is....

Here is how it displays on tumblr
![screen shot 2015-01-30 at 3 07 27 pm](https://cloud.githubusercontent.com/assets/9256525/5983307/bcce3da8-a891-11e4-87f4-4f4103c75613.png)

code used
```<script type="text/javascript" async="1" data-pua="29391" data-main="https://stage.popuparchive.com/assets/tplayer-embed" src="https://stage.popuparchive.com/assets/require.js"></script>```

**Comment by pkarman** [comment]
this is dependent on #992 so moving out till that is complete.

**Comment by baileyspace** [comment]
Check and see if this is a problem now that we've incorporated new tplayer styles.

**Comment by tarakieffer** [comment]
It is improved.

However, the twitter button doesn't display as a button.  And when clicked the tumblr url is populated. Is this expected?

For the line tweet, nothing is populated.

![screen shot 2015-06-04 at 7 53 39 am](https://cloud.githubusercontent.com/assets/9256525/7984436/e6423bd0-0a8e-11e5-95d8-b4263113f57e.png)

**Comment by pkarman** [comment]
this may be specific to popuptara.tumblr.com as there is another js error on that page.

I have it working correctly here: http://karpet007.tumblr.com/

**Comment by tarakieffer** [comment]
Tweet button displays correctly.

The transcript line tweet still does not pre-populate with anything.  What is expected to populate in this scenario?  Are we able to prepopulate the text from the line or the timestamp portion of the audio?

![screen shot 2015-06-05 at 4 48 38 pm](https://cloud.githubusercontent.com/assets/9256525/8015919/c5947ce4-0ba2-11e5-9319-1c291c8e73c3.png)
