### ISSUE TITLE
Tweak on-demand report + superadmin view of user accounts/metering/billing

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#974]
For example, this guy: https://www.popuparchive.com/superadmin/users/1618 (see related email chain from January 9).

We know that storage is measured in audio files, and billable time is measured in transcripts, and those are different units of measure. But if this user got 2h37min of premium transcripts, it doesn't make sense to us that his metered storage could be less than that. 

Also, the Retail Cost included in the on demand billing report is charging this user again for the 1hr of premium transcripts included on his Professional plan. Instead of charging him for 2h37min of on-demand transcripts, we should charge him for 1h37min of on-demand transcripts. (It's tricky also because while on the plan, he uploaded beyond the 1hr limit due to our inability to check durations before upload. So what we did was take his $57.62 charge and subtract the $22 he was unnecessarily charged for the 1hr from his premium plan. That way we were able to charge him for the overage on the 1hr plan as well as the on-demand transcripts.)

Maybe @pkarman and I can take a quick stab at this next week. I don't want to sink much time on this but it would be nice for us to all understand it going forward.

**Comment by Saltzshaker** [comment]
@pkarman Where did we land on altering the account UI view? I know we talked about:
1) Adding org usage for past months 
2) Getting rid of "storage summary" view
Just to confirm, are these both part of your changes?

**Comment by pkarman** [comment]
yes they are part of the changes.

**Comment by Saltzshaker** [comment]
Great, thanks!

**Comment by tarakieffer** [comment]
I still see the Storage Summary panel in the account history.  This should no longer display, correct?
![screen shot 2015-02-12 at 12 34 16 pm](https://cloud.githubusercontent.com/assets/9256525/6174311/8eee771e-b2b3-11e4-8937-445a402871b0.png)

**Comment by pkarman** [comment]
that's a good question. I have removed it from the superadmin view, but left it in the customer view because it still seemed useful as an overall snapshot of what they are storing with us. 

@annewootton @baileyspace @Saltzshaker do you have opinions?

**Comment by Saltzshaker** [comment]
I think the customer would have the same questions about how storage numbers relate to processing numbers as we do. 

I would vote either to get rid of it or change it to "Processing Summary," showing the time processed to date? Would definitely get rid of the Internet Archive storage summary, as this confuses people. @baileyspace @annewootton ?

**Comment by annewootton** [comment]
I think storage vs. processing is too confusing for users.

I would remove storage completely.

I do see that it could be useful to see a "Processing Summary" but that
would be for all transcripts processed since the beginning of time,
regardless of storage.

**Comment by pkarman** [comment]
I have removed that panel completely.

**Comment by tarakieffer** [comment]
Superadmin view looks good.  
 - Summary no longer displays
 - Monthly usage details available down to the items for organization and users.  

Customer account view no longer has summary panel
