### ISSUE TITLE
"Hidden Kitchens" search query returns "This Page is Private"

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#980]
This is strange because
1) Hidden Kitchens is a public collection
and 2) even if it wasn't, shouldn't it just return 0 results?
https://www.popuparchive.com/error/403?was=https:%2F%2Fwww.popuparchive.com%2Fsearch%3Fpage%3D1%26query%3D%2522hidden%2520kitchens%2522

**Comment by pkarman** [comment]
Item 8836 was flagged as public though its parent collection 1666 is private. That has been corrected, along with all the other Item mismatches, with the running of this task:

```
rake items:check_public VERBOSE=1
```
