### ISSUE TITLE
Change persistent player to display item name instead of filename?

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#985]
Filenames are often not very informative (especially coming from feeds/CSV import).

**Comment by pkarman** [comment]
The way I read the code, the persistent player is already using the item.getTitle() method for display. It looks at:
```
item.title || item.episode_title || item.series_title
```
in that order.

Do you have a specific example where the title is not what you think it should be?

Bear in mind that items may have filenames as titles if they are coming from CSV/feeds unless an explicit title was specified at import time.

**Comment by annewootton** [comment]
Weird... here's an example (from the customer who asked about this): https://www.popuparchive.com/collections/4166/items/31502

**Comment by pkarman** [comment]
excellent example. fixed now in loretta branch.

**Comment by tarakieffer** [comment]
Confirmed item name is used instead of file name for persistent player.
