### ISSUE TITLE
Failed CSV upload items

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#986]
Wisconsin Historical Society collection has an owner on Mechaplan who uploaded via CSV import. https://www.popuparchive.com/superadmin/organizations/17

Many items in this collection have cancelled transcript and analyze_audio tasks, plus failed analyze tasks. When you try to play, the console message is 404 for the AWS file. I also tried file.check_tasks and file.recover! but nothing changed. 

Note: the org and owner were on community plan when he used csv import, but on the mechaplan when I tried to run the above commands.

**Comment by pkarman** [comment]
which collection? I see several in that org.

**Comment by Saltzshaker** [comment]
oh whoops, meant to paste it: https://www.popuparchive.com/superadmin/collections/4345

**Comment by annewootton** [comment]
https://www.popuparchive.com/superadmin/collections/4345
<https://www.google.com/url?q=https%3A%2F%2Fwww.popuparchive.com%2Fsuperadmin%2Fcollections%2F4345&sa=D&sntz=1&usg=AFQjCNEwRHyu-tBwgrA7Z6tEKXFJBZQOBg>
ᐧ

**Comment by pkarman** [comment]
looks like the copytask claims to finish but the file is not there. e.g.
https://www.popuparchive.com/superadmin/tasks/324978

**Comment by pkarman** [comment]
fixer complains the filename is too long:
http://beta.fixer.prx.org/tasks/398939

**Comment by pkarman** [comment]
@kookster has a fix in the works.

**Comment by pkarman** [comment]
fixer is fixed.

however it appears the customer has gone in and deleted all the items/audio_files imported via CSV and is manually uploading at this point. So I don't think there's anything to do.
