### ISSUE TITLE
Change failed upload messaging from "Processing" to "Failed"

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#995]
If upload task is "cancelled" display status of "Failed: Something went wrong with your upload. Try re-uploading with a stronger internet connection."

Since we are still having uploads fail, it would be a better customer service flow if the user could be told ASAP that their upload has failed and they need to reupload.

**Comment by pkarman** [comment]
deployed 2/10 evening.

**Comment by Saltzshaker** [comment]
Great, thank you!
