### ISSUE TITLE
Account history details - clearer indication it is for a deleted item?

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#997]
From testing #994 
In the screenshot from frederick's account page, Item 20141208_2116 is deleted.  Clicking the link takes me to the 404 page.  
![screen shot 2015-02-12 at 12 17 13 pm](https://cloud.githubusercontent.com/assets/9256525/6174015/b52be788-b2b1-11e4-9f9c-1a707e70ef23.png)

It makes sense the item still needs to display in the list, but should the link be disabled?  Or perhaps some other indication the item is not available specifically because it has been deleted - rather then leaving it ambiguous?

**Comment by pkarman** [comment]
I think disabling the link, and providing an explanation-on-hover should suffice.

**Comment by tarakieffer** [comment]
And it is so. 

![screen shot 2015-02-12 at 3 04 25 pm](https://cloud.githubusercontent.com/assets/9256525/6177028/fd6c95c6-b2c8-11e4-969c-6926560ca9d4.png)
