### ISSUE TITLE
First month details for user in an org inconsistent

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#999]
Perhaps there is some set-up issue since I think the users were all "on their own" before getting added to Tara Test Org

This example shows the details of the organization for the first month, but no summary usage line
![screen shot 2015-02-12 at 1 18 15 pm](https://cloud.githubusercontent.com/assets/9256525/6175149/d6912ba6-b2b9-11e4-956a-5fe15accb221.png)

These other users show member usage, but no organization usage and no details.
![screen shot 2015-02-12 at 1 05 20 pm](https://cloud.githubusercontent.com/assets/9256525/6175150/d6925c74-b2b9-11e4-9078-3353fa8ef72d.png)
![screen shot 2015-02-12 at 12 54 09 pm](https://cloud.githubusercontent.com/assets/9256525/6175148/d690db4c-b2b9-11e4-824c-ad0a2382cb14.png)
![screen shot 2015-02-12 at 12 57 32 pm](https://cloud.githubusercontent.com/assets/9256525/6175151/d6946adc-b2b9-11e4-952e-06ea74544005.png)

**Comment by pkarman** [comment]
Yes, this is because of the way/timeline in which these users were added to the Org. 

It's also possible there are zero transcripts for any given month, in which case we should probably just hide the Details button altogether.

**Comment by tarakieffer** [comment]
Fritz - User 1460 -  For 2014-12, I expect to see the detail lines for items 33408, 33411, and 33407, but I do not see any.

![screen shot 2015-02-13 at 5 48 48 pm](https://cloud.githubusercontent.com/assets/9256525/6197346/6b2ada24-b3a9-11e4-86f6-ddb471767c37.png)

Otherwise, I think this is good.

**Comment by pkarman** [comment]
This was a legacy bug in the data, not the code. The items in question were still billable to old collections owned by Fritz, not his parent org. Once I set_owner on the collections in question, the usage all lines up.

**Comment by tarakieffer** [comment]
Great. resolved.
